CONTRIBUTING.md

Simple guidelines for contributing to tilavarauspalvelu-core repository. This file will be updated as we create new rules for contributing.

TILA-83 | Create CONTRIBUTING.md file

---

docker/api/Dockerfile
requirements.txt

Upgraded python to 3.8, removed requirement that doesn't work with > 3.6

TILA-82 Updated python to 3.8

---

applications/admin.py
applications/apps.py
applications/models.py
applications/tests.py
applications/views.py
tilanvarauspalvelu/settings.py

Created new django app for recurring reservation applications.

TILA-104 | Created applications app

---

CONTRIBUTING.md

A Draft of tilavarauspalvelu unit testing practices.
I'm not really happy about the first point `everything should be tested`: I would like to be more specific.

TILA-101 | Add information about unit testing to CONTRIBUTING.md

---

CONTRIBUTING.md
api/examples.py

Also created example file for API practices.

TILA-135 | Updated API practices for CONTRIBUTING.md.

---

api/tests/test_application_api.py
applications/apps.py

Some tests for existing code to verify nested data update/save/delete

Add tests for handling nested data update, save and delete.

---

.env.example
api/tests/conftest.py
requirements.txt
reservation_units/models.py
tilavarauspalvelu/loggers.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/utils/auditlog_util.py

TILA-81 Enable logging to elastic apm, configure logger for it.
TILA-81 Document environment variables.

TILA-81 | Add audit loggin to local database

---

spaces/migrations/0007_unit.py
spaces/migrations/0009_add_coordinates_and_unit_to_location.py

Due to the some poorly managed conflict handling by the author there were introduced migration conflicts in spaces

Fixes migration conflicts in spaces

---

api/urls.py
docker-compose.yml

This will reflect the changes made to code to the container without needing to rebuild.

Add source code folder to dev env volumes in docker-compose 

---

requirements.txt
spaces/importers/units.py
spaces/tests.py
spaces/tests/test_unit_importer.py

Adds units importer to code. 
Units are intended to be imported from https://www.hel.fi/palvelukarttaws/rest/v4/unit/.  The data source isn't restricted so this works for other sources as well.

TILA-281 | Units importer

---

spaces/importers/units.py

Log the creation and update count.
TILA-281

TILA-281 | Add creation and update counter to UnitImporter

---

applications/models.py
applications/tests/conftest.py
applications/tests/test_application_event.py
reservations/allocation_models.py
reservations/job_solver.py
reservations/tests.py
reservations/tests/conftest.py
reservations/tests/test_allocation_model.py
tilavarauspalvelu/utils/date_util.py
tilavarauspalvelu/utils/tests/test_date_util.py

This creates objects that will be used in automatic allocation and implements mapping Applications to Allocation Data. 
There will be more stuff added in the future, this is the bare minimum to start allocating applications.

Tila 299 | allocation object structure

---

applications/models.py
applications/tests/test_application_event.py
reservations/allocation_models.py
reservations/allocation_solver.py
reservations/job_solver.py
reservations/tests/conftest.py
reservations/tests/test_allocation_model.py

TILA-327 Solve simple allocation problem from actual django models.
This doesn't do much yet and contains no actual additional constraints yet, but since this involves quite a lot of refactoring etc. i think it's better to review this as is. 
This solves very minimal allocation problem from djago Application models and outputs a solution.

TILA-327 | Refactoring allocation model. Occurences by schedule id.

---

applications/models.py
applications/tests/conftest.py
applications/tests/test_application_event.py
reservations/allocation_models.py
reservations/tests/conftest.py

TILA-384 Filter by purpose age group and order number.

TILA-384 Getting application events by basket.

---

api/base.py

+ Fix non-list output from get_translatable_fields_for_model

TILA-240 | Fix OpenAPI schema for translated fields

---

api/applications_api.py
applications/models.py

previously own serializer was a bit too much.

Show aggregate data in dictionary field in API

---

applications/tests/test_application_aggregate_data.py

Was lacking test for separate applications

Add more tests for application aggregatedata

---

applications/models.py
applications/tests/test_application_event.py
requirements.txt
reservations/allocation_data_builder.py
reservations/allocation_models.py
reservations/tests/test_allocation_model.py
reservations/tests/test_allocation_solver.py

There are no functional changes here, just refactored django models out of allocation models for less tight coupling and created an intermediate builder to handle initializing AllocationData
Also refactored test cases to use assertpy.

Tila 384 allocation by basket

---

api/applications_api.py
api/reservations_api.py

Removes id from the display data of age group for rendering purposes.

Tila 421/serialize age groups to event data

---

api/space_api.py
spaces/models.py

- Register coordinates field in LocationSerializer
- Declare SRID
- Serve coordinates in nested object to be more explicit about lon/lat

Register coordinates field in LocationSerializer

---

Dockerfile
deploy/local_deps.sh
deploy/start_dev_server.sh
deploy/unregister_local.sh
docker-compose.yml

Changes made:
- added subscription-manager in order to enable the codeready-builder-for-rhel-8-x86_64-rpms repository
- added chgrp and chmod command for /tvp folder

changes to the Dockerfile

---

api/applications_api/serializers.py
api/reservation_units_api.py

Adds purpose name, ability group name and reservation unit details into application event data returned by api

TILA-426 | ApplicationEvent api data enrichment

---

spaces/models.py

Latitude and Longitude were mixed up.

Swap lat/lon

---

api/application_round_api.py
api/applications_api/views.py
api/permissions_api.py
api/reservation_units_api.py
api/reservations_api.py
api/resources_api.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/urls.py

Small changes and fixes after permission feature merge. Also disable graphql because it doesn't take permissions into account.

Take TMP_PERMISSIONS_DISABLED into account again. Disable graphql.

---

requirements.txt

Bump urllib3 to latest

---

api/applications_api/serializers.py
api/applications_api/views.py
api/urls.py

 TILA-544 | Add status edit end points for application and event

---

api/reservation_units_api.py

Add purposes to reservation_unit serializer

---

deploy/uwsgi.yml

Add static map to uwsgi conf to serve media files

---

api/allocation_results_api.py
api/common_filters.py
api/reservation_units_api.py

- common filters
- new filters to allocation results end point.

Smallish api refactor / enchancements

---

api/application_round_api.py
api/tests/test_application_round_api.py
permissions/helpers.py

I'll leave this open here, if something more is needed, let's close this and implement more stuff.

TILA-565 Add admin info to application round.

---

api/applications_api/serializers.py
api/applications_api/views.py

Also adds user as read_only in application status api
- sets the user from request

Tila 546 | Application event status permission

---

api/allocation_results_api.py
api/tests/test_application_status_api.py

Add possibility to delete results

---

allocation/allocation_data_builder.py
allocation/tests/test_allocation_model.py

Don't allocate declined or cancelled applications.

Fix application filtering.

---

api/applications_api/views.py

Previously it was created without calling super function and so it was lacking the request object

Update the ApplicationEventSerializer context

---

applications/signals.py
applications/tests/test_application_round_aggregate_data.py
applications/utils/aggregate_data.py
applications/utils/reservation_creation.py

Create  application round aggregate data on round's creation and update reservations total when reservations created.

TILA-554 | Application round aggregate data creation changes

---

api/reservations_api.py

adds also recurring reservation id and biweekly to RecurringReservatioAPI

TILA-622 | Add filter to recurring reservation api for reservation unit

---

api/application_round_api.py

Display name only for authenticated users.

TILA-569 | Add approver's name application round api.

---

api/application_round_api.py

Adds allocation result aggregate data summary info to application round
api. Renders as part of the app round's aggregated data.

TILA-640 | Add summary info from allocation results to application round api

---

permissions/api_permissions.py
permissions/helpers.py

Add application user read permissions to own application.
Managers can read as before.
TILA-641

TILA-641 | Add read permission check to applicaiton

---

api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
api/urls.py
requirements.in
requirements.txt
schema.json
tilavarauspalvelu/urls.py

Simple snapshot sanity test case to build on.

TILA-707 Graphql fetch api for reservation units.

---

api/graphql/reservation_units/reservation_unit_types.py

Import with model postfix to not confuse with type.

---

spaces/models.py

Lat and lon seemed to be mixed. Switching them a round.
TILA-728

TILA-728 | Fix lat and lon properties in Location model

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/schema.py

This is now basing the TILA-726 branch for diff's sake. When that gets merged can change the base to main.

TILA-727 | Add gql query to query reservation units by unit

---

api/space_api.py

Adds name to be charfield (for graphene mutations).
Adds parent, district and building as nullable.

SpaceSerializer field adds

---

api/graphql/base_mutations.py
api/graphql/reservation_units/reservation_unit_mutations.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/spaces/space_mutations.py
api/graphql/units/unit_mutations.py
api/reservation_units_api.py
permissions/api_permissions/graphene_permissions.py

also reservation unit mutations.
Adds permission checker class for classes based on `SerializerMutation`

TILA-730 | Terms of use to gql api 

---

api/graphql/reservation_units/reservation_unit_types.py

Sums the spaces surface areas
TILA-760

TILA-760 | Add surface area to reservation units gql api

---

api/graphql/spaces/space_serializers.py

Remove building from space mutations

---

api/graphql/spaces/space_types.py
api/graphql/units/unit_types.py

TILA-768 | unittype changes

---

api/graphql/opening_hours/opening_hours_types.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/test_reservation_units.py
api/graphql/units/unit_types.py
opening_hours/hours.py
opening_hours/tests/test_get_periods.py
opening_hours/utils/opening_hours_client.py
reservation_units/models.py
spaces/models.py

Makes possible to query opening hours for reservation unit and unit. 
- adds fetching periods also.
TILA-738 TILA-750

TILA-738 | Opening hours gql

---

opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py

TILA-750 | Fix overriding hauki origin id in openhours client

---

api/graphql/spaces/space_serializers.py
api/graphql/tests/test_spaces.py

with some validation and tests.

TILA-771 | Add name translations to space mutations

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

This is just a simple implementation. Needs to be refined further in https://helsinkisolutionoffice.atlassian.net/browse/TILA-797

Tila 703 text search

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py

TILA-782 | Add Equipment queries to gql api

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_purposes.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_purposes.py
api/graphql/tests/test_reservation_units.py

Purpose filter query to GQL schema.
TILA-809

TILA-809 | Add purposes filter to gql

---

api/graphql/reservation_units/reservation_unit_filtersets.py

TILA-778 | Add fields to be ordered in reservation unit gql api

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py

TILA-947 | Allow reservation state change to cancelled in updateMutation

---

api/graphql/reservations/reservation_serializers.py
reservations/models.py
reservations/tests/factories.py

Reservation states REQUESTED and WAITING_FOR_PAYMENT are not in use.
TILA-890

TILA-890 | Cleanup Reservation states that are not in use

---

Dockerfile

Tested locally and the build seems to work ok

Try to fix broken azure/olpenshift build as suggested

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

TILA-967 | Add isDraft filter to graphql ResevationUnitFilter

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_reservation_unit_types.py
api/graphql/tests/test_reservation_unit_types.py

TILA-966 | Add reservationUnitType gql query to query reservation unit types

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/snapshots/snap_test_reservations.py
api/graphql/tests/test_reservations.py

No cancellation rule no cancellation.
TILA-969

TILA-969 | Make reservation to be not cancellable if no rule

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

Graphene upgrade broke bit the order_by filter. This fixes it and adds
tests for testing order_by filter.

Fix order_by filter

---

requirements.txt

Builds are failing because `safety check` is finding security vulnerabilities in Celery and Kombu:
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$ …
```

Upgrade Celery to fix security issues

---

api/reservation_units_api.py
api/tests/test_reservation_unit_api.py

TILA-997 | Add reservation_units's is_draft filter to REST api

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py

TILA-1037 | Make cancellation rule nullable in res unit gql api

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py

TILA-900 | Copy buffer times from resunit to reservation in creation

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

TILA-1013 | Add resunit reservation/publish begins ends to gql api

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py

TILA-1015 | Check reservation unit's reservation begins and ends times in reservation creation

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py

TILA-1052 | Change resunit's surface to decimal fields in gql api

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/snapshots/snap_test_reservations.py
api/graphql/tests/test_reservations.py
reservations/models.py

TILA-953 | Add filter for getting reservation needed for handling

---

api/graphql/reservations/reservation_serializers.py

Fixes the metadata field validation so that it is only done in the update mutation (not in create mutation).
Otherwise the behavior stays the same.
TILA-1057

TILA-1057: Validate metadata fields in update mutation

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

This filter either filters in or out the reservation units that has
published (publish_begins & publish_ends)
TILA-1061

TILA-1061 | Add is_visible filter to reservation unit filterset

---

api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_serializers.py
api/graphql/schema.py
api/graphql/tests/test_reservations/test_reservation_approve.py

The mutation will be used for approving reservations that have state REQUIRES_HANDLING
TILA-1076

TILA-1076 | Add reservation approve mutation

---

api/graphql/reservations/reservation_connection.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_queries.py

TILA-1074 | Add custom connection class to Reservation for getting count

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

The filter didn't work as expected and this changes the logic to be what we wan't => Null values treated as visible.
Adds tests and enchance existing tests by adding bunch of data

Fix ReservationUnitFilterSet is_visible filter

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_approve.py
api/graphql/tests/test_reservations/test_reservation_deny.py

This is the way.
For now.
TILA-1129

TILA-1129 | Copy handling details on approva and deny to working memo

---

api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_serializers.py
api/graphql/schema.py
api/graphql/tests/test_reservations/test_reservation_require_handling.py

This is for the reservations which has status of CONFIRMED or DENIED
TILA-1128

TILA-1128 | Add mutation for changing reservation status to requires handling

---

api/graphql/spaces/space_types.py
api/graphql/tests/snapshots/snap_test_spaces.py
api/graphql/tests/test_spaces.py

TILA-1164 | Change SpaceType surfaceArea to be float

---

spaces/admin.py
spaces/models.py

TILA-1254 | Add UnitGroup to django admin

---

permissions/admin.py

Adds user to be searchable from roles
Adds user to be using select2 widget when creating a role (for user)
TILA-1260

TILA-1260 | Django admin role searches and filters

---

applications/models.py

Makes for e.g django admin selects more usable to display the City's name

Add __str__ method to City model

---

.gitignore
applications/management/commands/export_applications.py
applications/tests/test_application_export.py
applications/utils/export_data.py

Add Django management command to export all applications into CSV file for manual handling.
TILA-1095

TILA-1095 | CSV export of applications

---

api/applications_api/filters.py
api/tests/conftest.py
api/tests/test_application_api.py

TILA-1332 | Add unit filter to application rest end point

---

applications/models.py
applications/tests/factories.py
applications/tests/test_application_export.py
applications/utils/export_data.py
reservations/tests/factories.py

Changes:
* New fields added to export:
* Multiple CSVs are now created, one for each priority (if customers has added entries with the priority)
TILA-1325

TILA-1325 | Improvements to CSV export of applications

---

applications/tests/test_application_export.py
applications/utils/export_data.py

Aplication contact person field can be empty. Fix bug by handling the empty field.
Refs TILA-1325

TILA-1325 | Fix CSV export bug

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py

TILA-1204 | Use distinct in resunit text_search

---

applications/tests/factories.py
applications/tests/test_application_export.py
applications/utils/export_data.py

Correct application CSV export field data
Refs TILA-1352

TILA-1352 | Application csv export period field

---

README.md

* Added documentation about potential docker build issues
* Added documentation about multiple .env files and problems
* Added documentation about postgis install
Refs TILA-1291

TILA-1291 | Updated README

---

applications/tests/test_application_export.py
applications/utils/export_data.py
reservation_units/management/commands/export_reservation_units.py
reservation_units/tests/test_reservation_unit_export.py
reservation_units/utils/export_data.py

Export data of reservation units onto CSV file for easy inspection.
Refs TILA-1355

TILA-1355 | CSV export of reservation units

---

api/graphql/opening_hours/opening_hours_types.py
api/graphql/reservations/reservation_serializers.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations/test_reservation_confirm.py
api/graphql/tests/test_reservations/test_reservation_create.py
api/graphql/tests/test_reservations/test_reservation_update.py
api/tests/test_ical_api.py
opening_hours/tests/test_hauki_link_generator.py
opening_hours/tests/test_opening_hours_client.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
tilavarauspalvelu/settings.py

Changes the default time zone to europe/helsinki
TILA-1296

TILA-1296 | Change default time zone to "Europe/Helsinki"

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_queries.py

Support multiple values for state in filtering.
Refs TILA-1350

TILA-1350 | reservations gql filtering

---

tilavarauspalvelu/settings.py

- Shorter cookie age
- Secure cookie to only set cookie for https sessions
Refs TILA-1307

TILA-1307 | Login session updates

---

api/applications_api/filters.py
api/tests/test_application_api.py

Adds user filter to applications REST api for filtering applications by a user 
TILA-1408

TILA-1408 | Add user filter to Applications REST endpoint

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_cancellation.py

Send notification email when reservee cancels
TILA-1375

TILA-1375 | Send email when reservation cancelled

---

tilavarauspalvelu/tests/test_anonymization.py
tilavarauspalvelu/utils/anonymisation.py
users/admin.py

Adds anonymization functions to user application and reservation data and possibility to anonymize the data from django admin.
TILA-1390

TILA-1390 | User data anonymization capability to django admin

---

tilavarauspalvelu/utils/anonymisation.py

Also get rid off unused function for creating random text

Skipt bandit check for getting first and last name in anonymisation.

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
tilavarauspalvelu/utils/anonymisation.py

TILA-1410 | Add application_round filter to res_unit gql query

---

api/graphql/reservation_units/reservation_unit_types.py
api/reservation_units_api.py
tilavarauspalvelu/settings.py

Adds also the the link to REST api and GraphQL api
TILA-1428

TILA-1428 | Add large image size to thumbnails

---

.env.example
deploy/uwsgi.yml

* Add ENV variables to example file
* Move more variables to ENV variables

TILA-1394 | Add env variable documentation

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

Reservation units should be filterable by pk.
Refs TILA-1472

TILA-1472 | graphql filter reservation units by ids

---

tilavarauspalvelu/settings.py

Large sized images are wanted to be cropped.
TILA-1475

TILA-1475 | Crop large image

---

api/graphql/reservations/reservation_types.py

TILA-1271 | Add permission check to sensitive fields in ReservationType

---

requirements.in
requirements.txt

This PR addresses potential security vulnerabilities by upgrading Django to latest security patch.

Bump Django version for security fixes

---

api/applications_api/serializers.py
api/applications_api/views.py
api/ical_api.py
api/reservation_units_api.py
applications/models.py
permissions/api_permissions/drf_permissions.py
permissions/helpers.py
requirements.in
requirements.txt
tilavarauspalvelu/settings.py
tilavarauspalvelu/urls.py

* Permission and permission helper query performance updates
* `/v1/application/` endpoint query performance updates
Refs TILA-1488

TILA-1488 | Application api endpoint slowness

---

applications/tests/factories.py
applications/tests/test_application_export.py
applications/utils/export_data.py

* Filter out reservations from applications in "DRAFT" status
* Add "Status" column to CSV export file
* Write all priorities in one file
* Set "hakija" column to contact person when there is no organisation
Refs TILA-1487, TILA-1485

TILA-1487 | Application csv export improvements

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

TILA-1504 | Add new filter fields and order_by to res unit gql

---

api/graphql/applications/application_types.py
api/graphql/tests/snapshots/snap_test_cities.py
api/graphql/tests/test_cities.py

TILA-1453 | Add translated name fields for city type

---

applications/models.py
applications/tests/test_application_export.py
applications/utils/export_data.py

Minor "nice to have" fixes for CSV export.

TILA-1485 | CSV export improvements

---

api/graphql/application_rounds/application_round_types.py
api/graphql/tests/snapshots/snap_test_application_rounds.py
api/graphql/tests/test_application_rounds.py

TILA-1517 | Add reservation unit and application counts to ApplicationRoundType for gql api

---

deploy/uwsgi.yml

* Reload workers periodically for potential performance increases
* Better uwsgi settings for production
* Log real IP addresses instead of proxy addresses

Add uwsgi settings

---

api/graphql/tests/test_spaces.py
api/tests/test_reservation_api.py

Make tests more robust by hardening test cases and adding additional
checks.

Test improvements

---

api/allocation_api.py
api/allocation_results_api.py
api/application_round_api.py
api/applications_api/views.py
api/declined_reservation_units_api.py
api/hauki_api.py
api/ical_api.py
api/reservation_units_api.py
api/reservations_api.py
api/users_api.py
applications/models.py
reservations/models.py

Used database query optimization techniques in all REST endpoints to reduce amount of queries to the database. This should bring performance improvements for more snappy fetches.
Refs TILA-1501

TILA-1501 | Optimize REST API endpoints

---

.gitignore
README.md

Setting up the project on Mac has some quirks. I documented the steps I had to do to make everything work.
I also added pyenv configuration to `.gitignore`.

Document mac installation

---

api/graphql/applications/application_filtersets.py
api/graphql/tests/test_applications/snapshots/snap_base.py
api/graphql/tests/test_applications/test_applications_filters.py

* Order by filter to applications GraphQL query
* Tests for the different ordering types
Refs TILA-1609

TILA-1609 | Add order by to Applications

---

api/graphql/reservation_units/reservation_unit_types.py

I missed these fields from `ReservationUnitByPk` type.

Add min_persons and reservation_kind to res_unit_by_pk type

---

api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_filtersets.py

Adds name and service sector filtering to `UnitType`

TILA-1694: Allow filtering units by name and service sector

---

api/graphql/applications/application_types.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
requirements.in
requirements.txt
setup.cfg
utils/query_performance.py

Standardized utils function to optimize GraphQL queries dynamically.
Applied query optimizer for applications field as an example and testing field.

TILA-1606 | Standardized graphql query optimization

---

api/graphql/applications/application_filtersets.py
api/graphql/applications/application_types.py
api/graphql/schema.py
api/graphql/tests/test_application_events/base.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_permissions.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_permissions.py
api/graphql/tests/test_application_events/test_application_events_query.py
api/graphql/tests/test_applications/snapshots/snap_base.py
api/graphql/tests/test_applications/test_applications.py
permissions/api_permissions/graphene_permissions.py
utils/query_performance.py

First part of the application event gql api - mutations coming after this. 
TILA-1613

TILA-1613 | Add capability for querying application events to gql

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
reservation_units/enums.py
reservation_units/models.py

State is a computed field based on the following properties:
- is_draft
- is_archived
- publish_beings / publish_ends
- reservation_begins / reservation_ends

TILA-1725: Add ReservationUnit state property

---

api/graphql/applications/application_event_serializers.py
api/graphql/applications/application_mutations.py
api/graphql/applications/application_types.py
api/graphql/schema.py
api/graphql/tests/test_application_events/base.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query_permissions.py
api/graphql/tests/test_application_events/test_application_event_create.py
api/graphql/tests/test_application_events/test_application_event_delete.py
api/graphql/tests/test_application_events/test_application_event_update.py
api/graphql/tests/test_application_events/test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_query_permissions.py
api/graphql/tests/test_applications/snapshots/snap_base.py
permissions/api_permissions/graphene_permissions.py

Adds mutation end points to gql for creating, editing and deleting applicatoinEvents.
Also makes day and priority fields to be IntegerFields in applicationEventScheduleTyp
TILA-1613

TILA-1613 | ApplicationEvent mutations

---

applications/management/commands/export_application_round_stats_for_reservation_units.py
applications/utils/export_data.py

Django command for exportin csv file including reservation unit data per application round
TILA-1649

TILA-1649 | Application round statistics command

---

README.md

Happened to encounter a new issue with M1 Mac so documented the workaround.

Add OR-Tools workaround for Macs

---

api/graphql/applications/application_types.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_query.py

So that one can navigate to application from application event if want
so.
TILA-1735

TILA-1735 | Add application to ApplicationEventType

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

MaxPersons filters were updated. MinPersons filters are new.

TILA-1716: Update maxPersons and minPersons filters

---

api/graphql/applications/application_types.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py

TILA-1779 | Change allocatedDay to int

---

api/graphql/applications/application_filtersets.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_query.py

TILA-1778 | Add application status filter to ApplicationEvent query

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- reservation unit name (all languages)
- unit name (all languages)
- reservee name
Refs TILA-1775

TILA-1775: Add new reservation ordering fields

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_approve.py
api/graphql/tests/test_reservations/test_reservation_deny.py

This field should allow empty values

TILA-1806: Allow handling details to be empty

---

email_notification/tasks.py
reservations/tasks.py

TILA-1850 | Add names to celery tasks

---

email_notification/sender/email_notification_builder.py
email_notification/tests/base.py
email_notification/tests/test_notification_builders.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/utils/commons.py

TILA-1825 | New attrs to email builder

---

applications/admin.py
reservation_units/admin.py

In django admin this is.
TILA-1830

TILA-1830 | Add filter for reservation units in ApplicationRound admin

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_filtersets.py

And also fixes some issues in the unit filter as well.
TILA-1882 TILA-1883

TILA-1883 | Only with unit permission resrvation unit filter

---

reservation_units/utils/reservation_unit_state_helper.py

Make ReservationUnitStateHelper static

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

TILA-1903 | In reservationUnits filter reservationKind return always direct and season

---

api/graphql/applications/application_filtersets.py
api/graphql/tests/test_applications/snapshots/snap_test_applications_filters.py
api/graphql/tests/test_applications/test_applications_filters.py

TILA-1901 | Add filter to applications graphql to filter with pk

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_approve.py

TILA-1672: Send different email based on reservation price

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

this was missing from there.
(someday I hope we refactor away of these ByPks)

Add reservations to reservationUnitByPk

---

api/graphql/reservation_units/reservation_unit_filtersets.py

TILA-1917 | Add method for resrevationKind filter to get all kinds

---

reservation_units/tasks.py

Pass today argument to update_reservation_unit_pricings

---

reservation_units/tasks.py
reservation_units/tests/test_product_mapping.py

Well that was a stupid mistake from me 🤦‍♂️

TILA-1988: Fix product mapping removal bug

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

Much more usable this way
Refs TILA-1917

TILA-1917 | Remove reserveeDateOfBirth and add gql navigation to User from Reservation

---

.github/pull_request_template.md
api/graphql/tests/test_reservations/test_reservation_queries.py

- Fixed flaky `test_filter_by_multiple_reservation_unit` test
- Added simple pull request template

TILA-1518: Test fix and pull request template

---

api/graphql/applications/application_types.py
api/graphql/tests/base.py
api/graphql/tests/test_applications/snapshots/snap_test_applications.py
api/graphql/tests/test_applications/test_applications.py
api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py
api/graphql/users/user_types.py

- Adds ability to navigate to user from applicaiton. ApplicationType has userType.
- Remove permission check from UserType's date_of_birth field. The permission should be checked in application and reservation level when navigating to user.
Refs TILA-1990

TILA-1990 | Navigate to user from application

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_update.py

In reservation update we check the metadatafields but there is some exceptions for the required fields. As two of those exceptions for individual persons are:
- home_city is not required field even marked in metadataset
- organisation_name is not required field even marked in metadataset
Refs TILA-2025

TILA-2025 | Make changing to non-mandatory fields in metadata

---

users/utils/birthday_resolver.py

Add b"Bearer" to x-authorization header if not exist

---

users/utils/birthday_resolver.py

TILA-2053 | Catch 400 and 500 errors when quering profile info

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Adds filter for paymentType in Reservations GQL query
Refs TILA-2029

TILA-2029 | Add ability to filter reservations by payment_type

---

api/graphql/reservations/reservation_mutations.py
api/graphql/schema.py
api/graphql/tests/test_reservations/test_reservation_delete.py

Reservation can be deleted when it is in CREATED state or WAITING_FOR_PAYMENT
Refs TILA-2023

TILA-2023 | Adds mutation for deleting the reservation

---

allocation/allocation_runner.py
allocation/tests/test_allocation_model.py
api/allocation_api.py
api/graphql/tests/test_reservation_units/test_reservation_units_query.py
api/graphql/tests/test_reservations/test_reservation_create.py
api/graphql/tests/test_reservations/test_reservation_update.py
api/ical_api.py
api/tests/conftest.py
api/tests/test_allocation_api.py
api/tests/test_gdpr/test_gdpr_api.py
api/tests/test_reservation_unit_capacity.py
api/tests/test_webhook_api.py
applications/models.py
applications/tests/test_application_aggregate_data.py
applications/tests/test_application_event.py
applications/tests/test_application_round_aggregate_data.py
merchants/verkkokauppa/order/test/factories.py
merchants/verkkokauppa/tests/test_helpers.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py

There was missing timezone declaration in various places using datetimes. This adds the tzinfo to those.
Some is still missing since getting warnings but cannot found the source yet so this is the changeset for now.
- Timzones to various places

Add timezone to ones missing

---

allocation/allocation_solver.py
api/application_round_api.py
api/graphql/reservation_units/reservation_unit_mutations.py
applications/allocation_result_mapper.py
applications/models.py
applications/utils/aggregate_data.py
applications/utils/reservation_creation.py
opening_hours/hauki_request.py
opening_hours/hours.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/utils/logging.py

- Added a helper function that adds `tilavaraus` namespace to all loggers
- Made log level of `tilavaraus` namespace configurable via envs
- Changed all loggers to use the new function
- No changes required. Log level can be added when needed.

TILA-1518: Configurable log levels

---

api/graphql/reservations/reservation_serializers/confirm_serializers.py
api/graphql/tests/test_reservations/test_reservation_confirm.py

- Fixed invalid check
I changed the code so that validation logic kicks in only if price of the reservation > 0 OR reservation unit's pricing type is `PAID`. Both should be true at the same time if data has been created via UI, but just to be on the safe side I used `or` here.
This is based on #705 because I don't want to make test changes again 😅 
I'll rebase when #705 is merged.

TILA-2177: Fix payment_type validation in reservation confirm

---

tilavarauspalvelu/settings.py

- Add a new handler
- Use added handler for app and sql loggers
Logs didn't appear in the console but were written to a file.

TILA-2187: Fix app and SQL logging

---

api/graphql/reservation_units/reservation_unit_serializers.py

- Fix the filter
These filters have implicit AND and the previous code did not work. **Do not** use `and` keyword here!
The previous solution deleted all pricings without giving any warnings. 😭 

TILA-2187: Fix the filter of pricings deletion

---

api/graphql/merchants/merchant_mutations.py
api/graphql/reservations/reservation_mutations.py
api/graphql/tests/test_orders.py
api/graphql/tests/test_reservations/test_reservation_delete.py
api/tests/test_webhook_api.py
api/webhook_api/views.py
applications/models.py
merchants/pruning.py
merchants/tests/test_pruning.py
merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/requests.py
merchants/verkkokauppa/order/types.py
reservation_units/tasks.py
reservation_units/tests/test_tasks.py

- Use `capture_exception` instead of `capture_message`
- Use exception inheritance where it makes sense
- Add additional information to `capture_exception` where it makes sense

TILA-2219: Improve exception logging

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_pricing_calc.py
api/graphql/tests/test_reservations/test_reservation_create.py
email_notification/sender/email_notification_builder.py
email_notification/tests/test_notification_builders.py
tilavarauspalvelu/settings.py

- Adds subsidised price calc to reservation price calculation method
- Use the calculated price in email templates.

TILA-2133 | Add subsidised price to email template variables

---

README.md

- Updated README
This way the worker is using Django's scheduler and we can see the logs as well.
- No changes needed

TILA-1518: Improve celery command in README

---

merchants/models.py
reservation_units/models.py
reservations/models.py

- Enabled model metrics for monitoring
Enabled metrics for web shop related models, reservation units and reservations. I think these are good and often changed models to test with.

Enable model metrics

---

api/graphql/opening_hours/opening_hours_types.py
api/graphql/tests/test_reservation_units/base.py
api/graphql/tests/test_reservation_units/test_reservation_units_query.py

- Adds `is_reservable` to `OpeningHoursType`
Refs TILA-2267

TILA-2267 | Add is_reservable to OpeningHoursType

---

reservation_units/admin.py
reservation_units/tests/test_admin.py

- In ApplicationRoundAdmin show only reservation units that are seasonally bookable
Refs TILA-2246

TILA-2246 | Show only seasonally reservable reservation units in Application Round django admin

---

sonar-project.properties

Add python version to sonar confs

---

api/gdpr.py
api/tests/test_gdpr/test_gdpr_api.py
tilavarauspalvelu/tests/test_anonymization.py
tilavarauspalvelu/utils/anonymisation.py

- Remove organisation data anonymisation.
- Add reservation handling details to be anonymized.
-  Anonymize date of birth (null it) and return it within gdpr data
Refs TILA-2344

TILA-2344 | GDPR api changes

---

api/gdpr.py
api/tests/test_gdpr/test_gdpr_api.py

Adds logic to where user data anonymization is checked to be valid for execution.
Refs TILA-2365

TILA-2365 | Add check logic to user data anonymization

---

reservation_units/utils/reservation_unit_reservation_scheduler.py

So that we don't run into near midnight buggies
No refs.

Convert dates to default timezone in scheduler

---

tilavarauspalvelu/settings.py

The resolver_user path was changed within other changes/adds but the settings wasn't updates.
This updates the settings to have correct path.

Add correct resolve_user path

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/test/test_create_order_params.py

- Replaced mock data with customer data from reservation
I've done some high quality coding before... 🤦‍♂️ 

TILA-2407: Replace mock data with data from reservation

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Adds possibility to filter by recurring reservation to ReservationQuery
Refs TILA-2386

TILA-2386 | Add filtering by RecurringReservation ot Reservation gql query

---

api/graphql/tests/test_reservations/test_reservation_approve.py
api/graphql/tests/test_reservations/test_reservation_require_handling.py
reservations/email_utils.py

- Some of the emails are not needed anymore so I removed them

TILA-2170: Remove unnecessary emails

---

requirements.in
requirements.txt
reservations/admin.py
tilavarauspalvelu/settings.py

- Adds ability to export `ReservationStatistic` model to csv file (with django-import-export package)
- Makes possible to filter by spesific date range in django admin (with the django-admin-rangefilter package)
Refs TILA-2291

TILA-2291 | ReservationStatistics export from admin

---

tilavarauspalvelu/settings.py

Should fix the token expiry problem
Refs TILA-2444

TILA-2444 | Add OIDC_LEEWAY setting

---

api/graphql/reservation_units/reservation_unit_types.py

- Adds `QueryPerformanceOptimizerMixin` to `ReservationUnitType`
- Some initial configuration to the queries
Refs TILA-2442

TILA-2442 | Make QueryPerformanceOptimizerMixin to be inherited in ReservationUnitType

---

api/graphql/reservations/reservation_serializers/deny_serializers.py
api/graphql/tests/test_reservations/test_reservation_deny.py

- Allow denying reservations when in past if they're REQUIRES_HANDLING state
- Send deny notification email only for NORMAL type of reservations when the end isn't passed.
Refs TILA-2470

TILA-2470 | Allow deny for past reservations

---

api/graphql/application_rounds/application_round_filtersets.py
api/graphql/application_rounds/application_round_types.py
api/graphql/applications/application_filtersets.py
api/graphql/schema.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_query.py
api/graphql/tests/test_application_rounds/snapshots/snap_test_application_round_query.py
api/graphql/tests/test_application_rounds/test_application_round_query.py
api/graphql/tests/test_applications/snapshots/snap_test_applications_filters.py
api/graphql/tests/test_applications/test_applications_filters.py

- Adds possibility to query `Applications` with `appliedCount`
- Adds possibility to query `ApplicationEvents` with `appliedCount`
- Adds possibility to query `ApplicationRounds` with `pk`

TILA-2497 | Application and ApplicationEvent gql additions

---

users/tests/test_basic_info_resolver.py
users/tests/test_birthday_resolver.py
users/tests/test_resolve_user.py
users/utils/open_city_profile/basic_info_resolver.py
users/utils/open_city_profile/birthday_resolver.py

- Reads the user's open city profile node id regardles of the LOA level
Refs TILA-2450

TILA-2450 | Read profile node id regardless of LOA level

---

reservation_units/admin.py

Make image urls readonly

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/tests/test_helpers.py

- Fixed the invalid language selection

TILA-2545: Fix invalid language selection when webshop order is created

---

api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/reservations/reservation_serializers/staff_adjust_time_serializers.py
api/graphql/reservations/reservation_serializers/staff_create_serializers.py
api/graphql/schema.py
api/graphql/tests/test_reservations/test_reservation_staff_adjust_time.py
permissions/api_permissions/graphene_permissions.py

- Adds mutation for adjusting reservation time. For staff users only
Refs TILa-2503

TILA-2503 | Mutation for adjusting time as a staff user

---

api/graphql/merchants/merchant_types.py
api/graphql/tests/test_orders.py

- Hide `checkout_url` when order is expired
Web shop does not allow customers to continue to the payment pipeline if order is expired so there is no point providing checkout URL for expired orders.

TILA-2576: Hide checkout_url when order is expired

---

Dockerfile

- Updated repository to align with the new version
- Updated python paths to align with the new version
I'm going to merge this without review so that I can get the pipeline fixed quicker 😅 

TILA-2582: Update repository and Python paths

---

Dockerfile

- Updated package URL to the latest version
Build still failing so merging this without review.
- No changes required.

TILA-2582: Update additional package url

---

email_notification/sender/email_notification_context.py
email_notification/sender/tests/test_email_notification_context.py

- Translate unit and reservation unit names in `EmailNotificationContext`
Previously the email context didn't translate unit's nor reservation unit's names. Now it does so based on reservations or reservees language choices.
Refs TILA-2546

TILA-2546 | Use translated reservation unit and unit names in email context

---

Dockerfile.local

- Updated local dockerfile base image

TILA-2582: Update local docker python version

---

users/models.py
users/tests/test_user_str.py

Fix User __str__ erroring when user hasn't yet logged in.
Refs TILA-2547

TILA-2547 | Fix user __str__ when user hasn't yet logged in

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_pricing_calc.py

- Changed shorter pricing unit calculation to be based on 15 minutes intervals
- Changed longer pricing units to be fixed prices
Prices are calculated based on 15 minutes intervals, rounded up. This applies to price units that are less than half day. Other prices units are treated as fixed prices.

TILA-2574: Update price calculation logic

---

Dockerfile.local
README.md
docker-compose.yml
docker/entrypoint.sh
users/management/commands/ensure_admin_user.py
users/management/commands/tests/test_ensure_admin_user.py

- Added management command for creating the initial admin user
- Updated docker-compose setup so that it is easier to run
- Updated README
This should simplify things even more. Now client devs don't need to worry about migration or creating the initial user.

TILA-1518: Simplify local docker running

---

api/graphql/reservations/reservation_mutations.py
api/graphql/tests/test_reservations/test_reservation_delete.py

- Skip webshop call if order is already in `CANCELLED` state
- Log errors in web shop call, but don't prevent order cancellation/reservation deletion
Web shop API is not called if order is already cancelled. Failures in API call will not prevent reservation cancellation.

TILA-2614: Fixed order cancellation logic

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Mark more fields as private
- Update tests

TILA-2622: Mark more Reservation fields private

---

api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_serializers/staff_reservation_modify_serializers.py
api/graphql/schema.py
api/graphql/tests/test_reservations/test_reservation_staff_modify.py
permissions/api_permissions/graphene_permissions.py

- Adds mutation with serializer and permissions for modifying reservation as staff user
Time adjusting is done via different mutation. 
Refs TILA-2501

TILA-2501 | Add mutation for modifying reservation details

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/test_reservation_units/test_reservation_units_query.py

- Fixed `to` filter to include the given date
- Set reservations to be ordered by `begin` field
Reservation filter didn't work properly with `to` filter. Now it includes the given date and uses default timezone when reservations are filtered. Also, default sorting is set to be the `begin` field.

TILA-2568: Fix date filter

---

Dockerfile
README.md
allocation/allocation_models.py
api/applications_api/serializers.py
merchants/admin.py
opening_hours/hours.py

- Fixed small issues found by Sonar
- Rewrote README 🙈 
Since we discussed about the need for up-to-date and useful documentation, I spent some time trying to improve the README. Also, I went through code issues found by Sonar and tried to fix them. Hopefully this improves our reliability score.

TILA-1518: Code improvements and README rehaul

---

tilavarauspalvelu/tests/test_anonymization.py
tilavarauspalvelu/utils/anonymisation.py

- Updated string anonymization to leave empty fields empty

TILA-2617: Anonymization does not change empty fields

---

users/models.py
users/tests/test_user.py

- Added superuser check to `has_staff_permissions`
- Added unit tests for `has_staff_permissions`

TILA-2619: Consider superuser having staff permissions

---

tilavarauspalvelu/tests/test_anonymization.py
tilavarauspalvelu/utils/anonymisation.py

- Changes the anonoymized user full name as ANON ANYMIZED instead of randomly choosing some real names.
Refs TILA-2660

TILA-2660 | Assign ANON ANYMIZED to user to be anonymized

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/reservations/reservation_serializers/staff_adjust_time_serializers.py
api/graphql/reservations/reservation_serializers/staff_create_serializers.py
api/graphql/reservations/reservation_serializers/staff_reservation_modify_serializers.py
api/graphql/tests/test_reservations/test_reservation_create_staff.py
api/graphql/tests/test_reservations/test_reservation_staff_modify.py

- Updated mutations so that updated buffers are used in validation
- Fixed a bug in validation logic

TILA-2670: Fix buffer validation in staff reservation mutations

---

README.md

Refs TILA-2691
- Adds update to README.md regarding elasticsearch

TILA-2691 | Update readme

---

README.md

- Added few words about image cache to README
No changes required

TILA-2691: Add image cache to README

---

.gitattributes
deploy/uwsgi.yml

- Fixes uwsgi boot loop
- Set module instead of file path
- Use LF line endings for YAML files (don't know if necessary but cant hurt)

Fix backend bootloop in dev

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservation_units/snapshots/snap_test_reservation_units_query.py
api/graphql/tests/test_reservation_units/test_reservation_units_query.py
permissions/api_permissions/graphene_field_decorators.py

- Add `handling_details` to reservation schema, with staff access required
Jira issue: TILA-2749

Add handling_details to reservation schema

---

common/management/commands/_utils.py
common/management/commands/create_test_data.py
pyproject.toml

Fixes issues where test data generation script would use list/tuple for some enums.
Jira issue: TILA-2700

Fix issues where random.choice would return a list/tuple in test data generation

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_reservation_staff_adjust_time.py

Changed interpreted reservation intervals for staff reservations.
Jira Issue: [TILA-2780](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2780)
[TILA-2780]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change reservation intervals interpretation for staff mutations

---

.github/pull_request_template.md
.gitignore
.pre-commit-config.yaml
merchants/admin.py
merchants/tests/test_pruning.py
merchants/tests/test_validators.py
merchants/verkkokauppa/merchants/exceptions.py
merchants/verkkokauppa/merchants/requests.py
merchants/verkkokauppa/merchants/types.py
merchants/verkkokauppa/order/exceptions.py
merchants/verkkokauppa/order/requests.py
merchants/verkkokauppa/order/types.py
merchants/verkkokauppa/payment/exceptions.py
merchants/verkkokauppa/payment/requests.py
merchants/verkkokauppa/payment/types.py
merchants/verkkokauppa/product/exceptions.py
merchants/verkkokauppa/product/requests.py
merchants/verkkokauppa/tests/conftest.py
merchants/verkkokauppa/tests/test_helpers.py
merchants/verkkokauppa/tests/test_merchant_requests.py
merchants/verkkokauppa/tests/test_merchant_types.py
merchants/verkkokauppa/tests/test_order_requests.py
merchants/verkkokauppa/tests/test_order_types.py
merchants/verkkokauppa/tests/test_payment_requests.py
merchants/verkkokauppa/tests/test_payment_types.py
merchants/verkkokauppa/tests/test_product_requests.py
merchants/verkkokauppa/tests/test_product_types.py

- Fix creating a new Merchant by adding a new `paytrail_merchant_id` to Django Admin when creating a merchant.
- This field is intentionally not visible when updating an existing merchant, as it is not needed there.
- Change all Merchant app imports from relative to absolute for consistency and general good practices sake
- Update the PR template to this new amazing one with emojis 😉 
Additional notes if needed
- TILA-2766

Paytrail merchant creation fix

---

docker/entrypoint.sh

- Run celery worker in backend containers as well
- [TILA-2889](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2889)
[TILA-2889]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable celery worker in production entrypoint

---

reservation_units/admin.py

- Fixes reservation unit admin panel CSV export
- TILA-2810

Fix FileResponse not working if file closed

---

tilavarauspalvelu/settings.py

- Fixes errors when returning from Helsinki authentication by setting social auth middleware and appropriate error return URL.
Additional notes if needed
- ...

Fix erros when cancelling helsinki authentication

---

applications/migrations/0066_remove_applicationaggregatedata_application_and_more.py

- Try to fix migration errors in dev resulting from bad schedule data
- TILA-####

Try to fix migrations errors from bad schedule dates

---

reservations/migrations/0054_remove_recurringreservation_application_and_more.py

- Fixed one, out comes another! Fix recurring events migration to consider null values and make it more robust also.
Additional notes if needed
- TILA-####

Fix recurring reservation migration

---

.pre-commit-config.yaml
api/graphql/tests/test_recurring_reservations/test_recurring_reservations_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py
pyproject.toml

- Replaces black in pre-commit hooks with ruff-format 🔥
- TILA-####

Replace black with ruff format

---

actions/application_event_schedule.py
api/graphql/types/application_event_schedule/serializers.py
tests/test_graphql_api/test_application_event_schedule/test_approve.py

- See [this Slack thread](https://helsinkicity.slack.com/archives/C01E30PHAFN/p1698661693042359).
- TILA-####

Remove recurring reservation creation from schedule approve mutation endpoint

---

docker/Dockerfile

- Fix static files in docker
- TILA-####

Generate static files to correct folder in docker + other small fixes

---

api/graphql/tests/test_reservations/test_reservation_create.py
api/graphql/types/reservations/serializers/create_serializers.py
tests/factories/__init__.py
tests/factories/user.py
tests/test_graphql_api/test_reservation/helpers.py
tests/test_graphql_api/test_reservation/test_create.py
users/helauth/pipeline.py
users/helauth/utils.py
users/utils/open_city_profile/mixins.py

- Fetch token for open city profile prefill from session rather than X-Authorization
- TILA-####

Fix old X-Authorization token prefill logic with session based one

---

api/graphql/types/application_event/filtersets.py
common/filtersets.py
tests/helpers.py
tests/test_graphql_api/test_application_event/test_filtering.py

- Add new filters `priority`, `preferred_order`, `include_preferred_order_10_or_higher`, `home_city`, `age_group`, `purpose`, and `text_search` on application events.
- [TILA-2920](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2920)
[TILA-2920]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new filters to application events

---

api/graphql/types/application_event/filtersets.py
applications/querysets/application_event.py
tests/test_graphql_api/test_application_event/test_filtering.py

- Make the application event status filter accept multiple statuses
- TILA-####

Make application event status filter accept multiple statuses

---

tests/test_utils/test_jwt_decoding.py
users/helauth/utils.py

- Fix ID token decoding
- TILA-####

Fix profile token decoding and add test

---

api/graphql/types/application_event/filtersets.py
applications/querysets/application_event.py
tests/test_graphql_api/test_application_event/test_filtering.py

- Make application_status filter multiple choice in the application event endpoint
- TILA-####

Make application_status filter on application event multiple choise

---

Makefile
docker/entrypoint.sh
poetry.lock
pyproject.toml
tilavarauspalvelu/settings.py

- Configure Redis broker for celery
- TILA-2938

Celery redis config

---

applications/exporter.py
tests/test_csv_exporters/test_application_export.py

- Adds new requested columns to application round export
- TILA-2956

Add new columns to application round export

---

.github/workflows/approve.yml
.github/workflows/test.yml

- Change the if condition variables to use configuration variables in the `approve` workflow.
- This pipeline should not email me, since I'm not one of the bots, and thus the auto approve step is skipped
- TILA-####

Fix approve pipeline by using configuration variables

---

api/graphql/schema.py
api/graphql/types/application_event_schedule/filtersets.py
api/graphql/types/application_event_schedule/types.py
applications/querysets/application_event.py
applications/querysets/application_event_schedule.py
applications/querysets/helpers.py
tests/test_graphql_api/test_application_event_schedule/helpers.py
tests/test_graphql_api/test_application_event_schedule/test_query.py
tests/test_graphql_api/test_application_event_schedule/test_query_permissions.py

- Add application event schedule endpoint with new filters
- [TILA-2972](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2972)
[TILA-2972]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add application event schedule endpoint & new filters

---

tests/gql_builders.py
tests/helpers.py
tests/test_graphql_api/test_application/helpers.py
tests/test_graphql_api/test_application_event/helpers.py
tests/test_graphql_api/test_application_event_schedule/helpers.py
tests/test_graphql_api/test_application_round/helpers.py
tests/test_graphql_api/test_reservation/helpers.py
tests/test_graphql_api/test_reservation_unit/helpers.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_time_spans.py
tests/test_graphql_api/test_spaces/helpers.py
tests/test_graphql_api/test_user/helpers.py

- Add ability to build field filters with 'build_query' test helper
- TILA-####

Add ability to build field filters with 'build_query' test helper

---

spaces/models.py

- Update the whole Space tree if a partial update fails
- Should fix errors in the testing environment, come back to this if not
- [TILA-2974](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2974)
[TILA-2974]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix space hierarchy updating

---

email_notification/email_tester.py
email_notification/tests/test_email_tester.py

- Add unit name after reservation unit name in admin email testing forms.
- Can test locally, or manually once in dev/test env
- [TILA-2757](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2757)
[TILA-2757]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add unit name after res unit name in admin email tester

---

api/graphql/extensions/base_types.py
api/graphql/types/application/filtersets.py
api/graphql/types/application_event/filtersets.py
api/graphql/types/application_event_schedule/filtersets.py
applications/querysets/application_event_schedule.py
common/db.py
tests/test_graphql_api/test_application/test_filtering.py
tests/test_graphql_api/test_application_event_schedule/test_query.py

- Add new filters to applications and application event schedules according to the ticket specifications (application events already had everything)
- [TILA-2985](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2985)
[TILA-2985]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new filters to application and application event schedule endpoints

---

merchants/verkkokauppa/order/test/test_order_from_json.py
merchants/verkkokauppa/order/types.py
merchants/verkkokauppa/tests/test_order_requests.py
merchants/verkkokauppa/tests/test_order_types.py

- Change verkkokauppa order checkout url to `loggedInCheckoutUrl`
- Test in test server when this is deployed there
- [TILA-2946](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2946)
[TILA-2946]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change webstore order checkout url

---

reservation_units/querysets.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py

- Fixes [this bug](https://helsinkicity.slack.com/archives/C04CVT9KPSN/p1704186260482789). Regression test made to prove fix.
- TILA-####

Fix bug in time search with application rounds

---

actions/application_event_schedule.py
api/graphql/types/reservation_units/types.py
opening_hours/models.py
opening_hours/querysets.py
reservation_units/querysets.py
reservation_units/utils/reservation_unit_reservation_scheduler.py
tests/test_querysets/reservable_time_span.py

- Fixes validation for reservable times when making reservations. Validator now expects to find a reservable time that fully fills the given reservation's period, partially overlapping or too short reservable times do not count.
- TILA-####

Fix validation for reservable times when making reservations

---

reservations/querysets.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py
tests/test_querysets/test_reservation_querysets.py

- Ignore cancelled and denied reservations in first reservable time deduction
- TILA-####

Ignore cancelled and denied reservations in first reservable time deduction

---

api/graphql/types/application_event_schedule/types.py

- Add application event to application event schedule node (frontend requires this)
- No need for tests
- TILA-####

Add application event to application event schedule node

---

permissions/admin.py

- Add new columns and filters to unit role admin page for units, unit groups and service sectors
- Manual tests done during GetTogether
- TILA-####

Add filters and new columns for unit roles

---

reservation_units/admin/reservation_unit.py

- Add filter for "is_archived" and "is_draft" to admin panel
- Manual testing done during GetTogether
- TILA-####

Add two new filters to reservation unit admin page

---

tilavarauspalvelu/middleware.py
tilavarauspalvelu/settings.py

- Have Sentry issues be raised from GQL errors
- For now all exceptions raise an error, we may want to filter some of those away later
- Setup Sentry to local env and make a GQL request that raises an exception
- TILA-2976

Add Sentry logging for GQL requests

---

api/graphql/tests/test_resources.py
api/graphql/types/resources/serializers.py
common/fields/forms.py
common/management/commands/create_test_data.py
pyproject.toml
resources/choices.py
resources/models.py
spaces/admin.py
spaces/models/space.py
terms_of_use/admin.py

- Various improvements to how admin panel shows data:
Show term type in terms of use list. Add filtering by term type:
Show payment merchant and accounting in units list. Add filtering by them as well.
Show unit counts for unit groups and service sectors in list views
Improve unit selection in unit groups and service sectors, and add selected unit count to edit view:
Show unit after reservation unit in the reservation unit list
Show space and space unit after resource in the resource list:
- The admin panel still works, will get feedback from users and fix if something broke
[//]: # "This pull request resolves all or …

Admin panel improvements

---

opening_hours/utils/time_span_element.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py

- Fixes non-even first reservable time
- TILA-####

Fix non-even start time

---

api/graphql/types/application_event_schedule/filtersets.py
tests/test_graphql_api/test_application_event_schedule/test_filtering.py

- Add `accepted` and `declined` filters to application event schedules (requested by frontend)
- TILA-####

Add accepted and declined filters to application event schedules

---

api/graphql/types/application_event_schedule/filtersets.py
tests/test_graphql_api/test_application_event_schedule/test_filtering.py

- Add `unallocated` filter to application event schedules (requested by frontend)
- TILA-####

Add unallocated filter to application event schedules

---

api/graphql/types/reservation_units/filtersets.py
tests/test_graphql_api/test_reservation_unit/test_filter_equipment.py
tests/test_graphql_api/test_reservation_unit/test_text_search.py

- Fix reservation unit text search not accounting for previous filters
- TILA-####

Fix reservation unit text search

---

api/graphql/schema.py
api/graphql/types/application_event_schedule/mutations.py
api/graphql/types/application_event_schedule/serializers.py
applications/choices.py
tests/test_graphql_api/test_application_event_schedule/helpers.py
tests/test_graphql_api/test_application_event_schedule/test_reset.py
tests/test_graphql_api/test_application_event_schedule/test_reset_permissions.py

- Add a way to reset ApplicationEventSchedule through the GQL API
- [TILA-2989](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2989)
[TILA-2989]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Application Event Schedule Reset Mutation

---

api/graphql/types/application_event/types.py
tests/test_graphql_api/test_application_event/test_filtering.py

- Allow filtering for schedules by priority in application event endpoint
- Slack

Allow filtering for schedules by priority in application event endpoint

---

applications/choices.py
tests/test_graphql_api/test_application_event_schedule/test_approve.py

- This is done to make more than one approval possible for an event.
- TILA-####

Allow schedules to be approved when event is already approved

---

applications/migrations/0001_initial.py
reservation_units/migrations/0092_alter_equipment_options_and_more.py
reservation_units/models/qualifier.py
reservations/migrations/0059_alter_abilitygroup_options_alter_agegroup_options_and_more.py
reservations/models/reservation_statistic.py
resources/migrations/0008_alter_resource_options_alter_resource_table.py
resources/models.py
services/migrations/0003_alter_service_options_alter_service_table.py
services/models.py
spaces/migrations/0035_alter_building_options_alter_location_options_and_more.py
spaces/models/space.py

- Fix migrations created in PR #1082. Previous migrations [created error in dev](https://console-openshift-console.apps.arodevtest.hel.fi/k8s/ns/hki-kanslia-aok-tilavarauspalvelu-dev/pods/tilavarauspalvelu-core-1136-hook-mid/logs).
- Local migration tests done, was able to create previous errors
- Automated test
- TILA-####

Fix migration `db_table` names

---

actions/application_event.py
api/graphql/types/application_event/types.py
common/db.py
common/querysets/mptt.py
reservation_units/models/reservation_unit.py
reservation_units/querysets.py
reservation_units/tests/test_reservation_unit_first_reservable_time.py
reservation_units/utils/first_reservable_time.py
tests/conftest.py
tests/factories/application.py
tests/factories/application_event.py
tests/test_actions/test_application_events.py
tests/test_graphql_api/test_application_event/test_query.py
tests/test_graphql_api/test_application_event_schedule/test_approve.py
tests/test_querysets/test_reservation_units_with_common_hierarchy.py

- Add field to application events endpoint for fetching "related application events", i.e. events that have allocated schedules to any reservation unit sharing a common space hierarchy or resource, and which overlap with the events allocation time.
- [TILA-3064](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3064)
[TILA-3064]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Related application events

---

email_notification/admin.py
opening_hours/admin.py

- Add `extra_context` to all admin extra buttons since that is added to each request for showing the release version. Otherwise the buttons just dont work
- Tested locally that the buttons now work
- TILA-####

Fix admin extra buttons

---

api/graphql/tests/test_reservation_units/test_reservation_units_update_draft.py
api/graphql/tests/test_reservation_units/test_reservation_units_update_not_draft.py
api/graphql/types/reservation_units/mutations.py

- When ReservationUnit is set as archived through the GQL API, force the `is_draft` value as `True`
- [TILA-3053](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3053)
[TILA-3053]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ReservationUnit archiving sets it as draft too

---

api/graphql/extensions/filters.py
api/graphql/types/reservations/filtersets.py
api/graphql/types/reservations/types.py
common/date_utils.py
tests/test_graphql_api/test_reservation/test_filtering.py

- Change Reservation `begin` and `end` filters to `beginDate` and `endDate`
- ‼️ This is a breaking change and requires frontend changes
- Manual testing in the Admin UI on pages that call the `/reservations/` endpoint
- [TILA-3095](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3095)
[TILA-3095]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reservation begin and end date filters

---

merchants/verkkokauppa/tests/test_merchant_requests.py
merchants/verkkokauppa/tests/test_order_requests.py
merchants/verkkokauppa/tests/test_product_requests.py
merchants/verkkokauppa/verkkokauppa_api_client.py
opening_hours/utils/hauki_api_client.py
utils/external_service/base_external_service_client.py

- The endpoints which URLs are only VERKKOKAUPPA_*_API_URL should have a '/' at the end
- Manual testing without mock verkkokauppa
- TILA-3066

Fix verkkokauppa API urls

---

api/graphql/types/reservations/filtersets.py
permissions/getters.py
tests/factories/__init__.py
tests/factories/user.py
tests/test_graphql_api/test_reservation/test_filtering.py

- Add a new permission filter for reservations with handling permissions
- [TILA-3132](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3132)
[TILA-3132]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new filter for reservations with handling permissions

---

api/graphql/types/reservations/serializers/mixins.py

Ignore start intervals longer than 30 minutes for staff reservations

---

permissions/helpers.py
tests/test_graphql_api/test_reservation/test_query_permissions.py

- Fixes check for reservation non-public fields
- [ TILA-3237](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3237)

Switch `needs_staff_permissions` check around

---

reservation_units/utils/first_reservable_time_helper.py
tests/test_utils/test_first_reservable_time_helper.py

> Esimerkki:
Aloitusintervalli = 3h
Min pituus = 1h  →  3h
Max pituus = 14h  →  12h (3h*4 = 12h)
- [TILA-3229](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3229)
[TILA-3229]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Consider the reservation unit start interval in reservation min and max duration for first reservable time calculation

---

api/graphql/types/reservation_unit/filtersets.py
tests/test_graphql_api/test_reservation_unit/test_filtering.py

- Adds `tprek_id` and `tprek_department_id` filters to `reservationUnit` endpoint
- [TILA-2960](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2960)
[TILA-2960]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add TPRekID filter

---

users/helauth/pipeline.py
users/helauth/typing.py

- Fixes login in certain cases where ID token is not found from user. See [this](https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/11597/?environment=DEV&project=18&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) sentry ticket.
- Test login in dev server

Fix login with missing ID token

---

.github/release.yml
api/graphql/types/reservation/permissions.py
api/graphql/types/reservation_metadata/permissions.py
api/graphql/types/reservation_unit_option/filtersets.py
tilavarauspalvelu/urls.py

- Make preferred order filter on reservation unit options to accept lists of preferred orders as well
- Change permissions on reservation and metadata endpoint to allow all users to fetch them, not just authenticated ones.
- Adds a `csrf` view for getting CSRF token for frontend to use. Getting this token should be protected by CORS.
- TILA-####

Required changes for frontend due to refactor

---

tilavarauspalvelu/urls.py

- Make the CSRF view redirect to given path (or root by default) after setting the token to cookies
- Add the CSRF token to a `NewCSRFToken` header in the response for frontend to pick it up during local development
- Frontend should integrate with this and check that it boots in dev env.

Make CSRF view redirect to path (or root if not given)

---

tilavarauspalvelu/logging.py
tilavarauspalvelu/settings.py

- Add URL, headers, and user id to log output if request info is included in the logger call. Useful for debugging issues regarding failing requests.
-  Test in dev with frontend

Add more info to log output

---

permissions/helpers.py

- Add missing permission check for viewing recurring reservations that was mistakingly removed during a recent refactor.

Add missing general permission check to recurring reservation view

---

.github/pull_request_template.md

-
- None
- [TILA-][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-

Add dependencies to PR template

---

.github/workflows/test.yml

- Revert CI fix from #1172, as the repo seems to be fixed now
- None

Revert CI fix from #1172

---

applications/migrations/0089_migrate_old_application_data.py

- Fixes migration skipping some schedules that begin before midnight and end at midnight not being migrated. Still catch cases where duration would be zero.
- None
- [TILA-3221][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3221
[TILA-3221]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3221?atlOrigin= …

One more batch of fixes to application migration

---

api/graphql/types/reservation/serializers/create_serializers.py
api/graphql/types/reservation_unit/types.py
tests/test_graphql_api/test_reservation/test_create.py
tests/test_graphql_api/test_reservation_unit/test_query.py

- See title.
- None
- [TILA-3318][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3318
[TILA-3318]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude `SEASONAL` type reservations from user max reservations per unit

---

api/graphql/types/reservation_unit/types.py
opening_hours/tests/test_hauki_link_generator.py
opening_hours/utils/hauki_link_generator.py
tests/test_graphql_api/test_reservation_unit/test_hauki_integration.py

- Don't return a Hauki link for reservation units that are not connected to any `OriginHaukiResource`
- None
- [TILA-3342][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3342
[TILA-3342]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

ReservationUnit Hauki-link

---

api/graphql/types/unit/types.py

- Frontend PR https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1184 unit query added a field and requires higher complexity.
- None
- [TILA-][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-

increase unit query complexity for frontend

---

actions/recurring_reservation.py
applications/tasks.py
tests/test_utils/test_generate_reservations_from_allocations.py

- Generate rejected occurrences when closing handling for seasonal booking allocation
- None
- [TILA-3412][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3412
[TILA-3412]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

Generate rejected occurrences

---

api/graphql/types/recurring_reservation/types.py
tests/test_graphql_api/test_recurring_reservation/test_query.py

- Adds allocated time slots to recurring reservation node in GraphQL schema.
- Adds permission checks to access this field.
- None
- [TILA-3366][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3366
[TILA-3366]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

Add allocated time slot to recurring api

---

api/graphql/types/unit/filtersets.py
reservation_units/enums.py
tests/test_graphql_api/test_unit/test_query.py

- Fixes issues with some unit endpoint filters resulting in duplicate units
- None
- [TILA-3431][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3431
[TILA-3431]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

Resolve issues with unit endpoint duplication

---

tilavarauspalvelu/middleware.py

- Import test-only deps inline so that middleware still work in production.
- None
- None

Fix issue with profiler middleware deps

---

api/graphql/types/purpose/types.py
common/tasks.py
tests/test_utils/test_query_logging_middleware.py
tilavarauspalvelu/middleware.py
tilavarauspalvelu/settings.py

- Add thresholds for when query logging creates logs based on total request time, body length, and request query count.
- Fix an issue with optimizing purpose images.
- None
- None

Query log for long requests

---

applications/admin/forms/application_section.py
applications/choices.py
applications/models/application_section.py
locale/fi/LC_MESSAGES/django.po
pyproject.toml
tests/factories/application_section.py
tests/test_factories/test_application_round.py
tests/test_factories/test_application_section.py
tests/test_graphql_api/test_allocated_time_slot/test_create.py
tests/test_graphql_api/test_application_section/test_delete.py
tests/test_models/test_application_section.py

- `ApplicationSectionStatusChoice`
- Add `REJECTED` status
- Remove `FAILED` and `RESERVED` statuses
- Modify the way `HANDLED` is defined
- None
- [TILA-3380][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3380
---
This is a re-opened PR of https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1231 …

Application section rejected status

---

applications/tasks.py
locale/fi/LC_MESSAGES/django.po
opening_hours/utils/time_span_element_utils.py
reservation_units/utils/first_reservable_time_helper/first_reservable_time_reservable_time_span_helper.py
reservation_units/utils/first_reservable_time_helper/first_reservable_time_reservation_unit_helper.py
spaces/querysets/unit.py
tests/test_external_services/test_hauki/test_merge_overlapping_time_span_elements.py
tests/test_graphql_api/test_unit/test_ordering.py
tests/test_graphql_api/test_unit_group/test_query.py
tests/test_helauth/test_pipeline_additions.py
tests/test_utils/test_generate_reservations_from_allocations.py
tilavarauspalvelu/settings.py
utils/sentry.py

- Improves null safety in generating reservations from allocations
- Reverts some optimizations to FRT calculation causing issues that prevent release to prod. These will be fixed later and reapplied then.
- Fixes an issues with unit reservation unit count counting archived reservation units
- Adds some missing fields to generated reservations from applications
- None
[//]: # "This pull request resolves all or …

Fix regressions and issues introduced in v0.51.0

---

applications/tasks.py

- Task cannot start due to using a set as an input, so use a list instead.
- None
- None

Convert pk list to set for serialization to statistics task

---

api/graphql/types/reservation/types.py

- See title. Required by frontend.
- None
- None

Increase ReservationNode.Meta.max_complexity to 22

---

api/graphql/types/reservation_unit/filtersets.py
reservation_units/querysets.py
reservation_units/utils/first_reservable_time_helper/first_reservable_time_helper.py
tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py

- Full explanation will be written as an ADR.
- Required frontend changes to make pagination work, but can be merged before those are done, and it will still make the page much faster to load due to cached results.
- [TILA-3480](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3480)
[TILA-3480]: …

Fix FRT pagination optimization & use caching to make it faster

---

merchants/verkkokauppa/order/types.py
tests/test_external_services/test_verkkokauppa/test_create_order_params.py
tests/test_external_services/test_verkkokauppa/test_order_types.py

- Send VAT decimal part to verkkokauppa
- This should also be tested on the test server with verkkokauppa integration
- None
- [TILA-3481](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3481)
[TILA-3481]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

Send VAT decimal part to verkkokauppa

---

api/graphql/types/application_round/types.py

- Use subqueries to count applications and reservation units for application rounds
- None
- [TILA-3455](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3455)
[TILA-3455]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix application round application and reservation unit counts

---

reservations/migrations/0077_alter_reservationstatistic_reservee_type.py
reservations/migrations/0079_fix_reservation_price_net.py

- Migration re-calculates net prices for reservations due to mistake in calculation formula in the frontend
- Requires frontend to correct the used formula. (https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1333)
- [TILA-3463](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3463)
[TILA-3463]: …

Add migration to correct net prices on reservations

---

.github/workflows/build.yml

- Enhanced metadata should be used to fetch the correct container from ghcr.io in Azure Pipelines.
- None
- None

Enrich metadata in dockerfile built to ghcr.io

---

reservation_units/tasks.py
tests/test_models/test_reservation_unit_pricing_updates.py
tilavarauspalvelu/settings.py

- Fix the task failing on servers due to auditlogging
- Fix tests being flaky when running them in parallel
- None
- None

Fix updating reservation unit pricing tax percentage task

---

azure-pipelines-dev.yml
azure-pipelines-release.yml

- Changes triggers for dev and release builds to the new pipelines
- Test that triggers work, and that pipelines work in all environments
- None
- [TILA-3469](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3469)
[TILA-3469]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

New azure pipelines

---

.github/workflows/build.yml

- Push images built in PRs to ghcr.io for use in Azure Pipelines if fast-forward merges are used.
- None
- None

Push to registry on PR

---

.github/workflows/build.yml

Explicitly set 'push: true' to actually push the image

---

poetry.lock
pyproject.toml
tilavarauspalvelu/settings.py

- Release notes: https://docs.djangoproject.com/en/5.1/releases/5.1/
- Also update rest of dependencies to latest versions
- Require adding workaround for thumbnails: https://github.com/SmileyChris/easy-thumbnails/issues/641
- None
- None

Update to Django 5.1.

---

applications/admin/application_round/admin.py
applications/admin/application_section/filters.py

-  See title. Fixes a crash in admin panel application round view.
- None
- None

Remove target group from application round admin panel view

---

permissions/models/general_role.py
permissions/models/unit_role.py

- See title. Helps in the admin panel
- None
- None

Add better `__str__` methods to permissions models

---

api/graphql/types/unit/filtersets.py

- Don't show units to the notification manager when using `units.only_with_permissions`-filter, since they don't work with units directly
- None
- None

Don't show units to the notification manager with perms filter

---

permissions/migrations/0029_migrate_permissions_to_new_models.py

- Improves permissions migration to work better in production by looking at the role codes. Technically role codes can be anything, but these were the ones during the migration in production, which is the most critical part.
- None
- None

Update the permissions migration to look at role names

---

reservation_units/admin/reservation_unit/admin.py

- Django Admin: Add missing payment_product field in ReservationUnitAdmin
- None
- [TILA-3536](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3536)
[TILA-3536]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Django Admin: Add missing payment_product field in ReservationUnitAdmin

---

api/graphql/types/reservation/serializers/create_serializers.py

- Fixes a regression in creating reservations where user was not saved, leading them not being able to update the reservation later.
- None
- None

Fix reservation user not being saved on create

---

common/management/commands/data_creation/create_reservations.py
locale/fi/LC_MESSAGES/django.po
reservation_units/admin/reservation_unit/admin.py

- Fixes broken data generation due to `price_net` having been converted to a property
- Fixes reservation unit admin page due to state having been changed to publishing state
- None
- None

Fix admin pages & test data generation

---

tilavarauspalvelu/settings.py

- New environment allows sending errors to sentry from pod creation mid hooks, as well as to use sentry to log errors or for migration operations.
- New migration for removing sessions from redis during keycloak migrations require this.
- None
- None

Add new environment for pod deployment mod hooks

---

users/helauth/pipeline.py

Match emails case-insensitively in Tunnistamo -> Keycloak migration

---

tests/test_helauth/test_pipeline_additions.py
users/admin/user.py
users/helauth/pipeline.py

- Migrate reservation notification info
- Mark older users as inactive so that migration doesn't run again
- Rename inactive users to make management easier
- Add new filters to user admin panel view
- None
- None

Improve Keycloak migration

---

users/helauth/clients.py
users/helauth/pipeline.py
utils/sentry.py

- See title. This is to better be able to diagnose issues when profile auth fails
- None
- None

Log HelsinkiProfileClient exceptions to sentry

---

api/gdpr/views.py
tests/test_gdpr_api/test_gdpr_api.py
tilavarauspalvelu/settings.py

- Only log when exceptions are raised: e.g. auth or permissions fail. This should make it easier to debug possible failures in the GDPR API.
- Does not log about known errors like "has open payments".
- None
- None

Add better logging for GDPR API

---

api/gdpr/views.py
tests/test_gdpr_api/test_gdpr_api.py

- Add more details to GDPR permission failures to diagnose issues.
- Manual tests in dev server
- None
- None

Add better logging for permission errors in GDPR requests

---

api/gdpr/views.py
tests/test_gdpr_api/helpers.py
tests/test_gdpr_api/test_gdpr_api.py
tilavarauspalvelu/settings.py

- See title.
- Manual testing in DEV.
- None
- None

Change to correct `API_AUTHORIZATION_FIELD` & dump claims to sentry data

---

Makefile
docker/worker.sh

- Fixes celery location in scripts so that it can start normally.
- None

Fix celery config

---

tilavarauspalvelu/admin/user/admin.py

- See title. Went missing after the one-app migration.
- None
- None

Fix user admin page not loading due to missing read-only fields

---

tests/test_email/test_email_sender_reservation.py
tests/test_rest_api/test_ical_api.py
tilavarauspalvelu/api/rest/views.py
tilavarauspalvelu/models/reservation/actions.py
tilavarauspalvelu/utils/email/email_builder_base.py
tilavarauspalvelu/utils/email/email_builder_reservation.py
tilavarauspalvelu/utils/email/email_sender.py

- Attach an `.ical` file to reservation email notifications
- Manual testing to make sure the file appears **correctly** in the sent email
- None
- [TILA-3056](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3056)
[TILA-3056]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

Add ical file to reservation emails

---

.github/workflows/build.yml

- This is to fix builds being created for the wrong SHA in PRs.
- None
- None

Set build SHA based on actual PR head sha

---

tests/test_email/test_email_sender_reservation.py
tests/test_rest_api/test_ical_api.py
tilavarauspalvelu/api/rest/views.py
tilavarauspalvelu/models/reservation/actions.py
tilavarauspalvelu/utils/email/email_builder_base.py
tilavarauspalvelu/utils/email/email_builder_reservation.py
tilavarauspalvelu/utils/email/email_sender.py

- Add `.ics` file to reservation email notifications
- None
- [TILA-3549](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3549)
[TILA-3549]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Email calendar attachment file

---

tilavarauspalvelu/utils/helauth/clients.py

- Fixes an issue where Helsinki profile token was refreshed incorrectly if profile refresh token was used.
- Requires manual tests, but might be hard to make due to timing. Maybe just see if the error in sentry keeps happening?
- None
- [TILA-3605](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3605)
[TILA-3605]: …

Fix Helsinki profile token refreshing

---

tests/test_integrations/test_email/test_email_service.py
tests/test_integrations/test_email/test_find_recipients.py
tilavarauspalvelu/integrations/email/find_recipients.py
tilavarauspalvelu/integrations/email/main.py

- Send staff emails in staff user's preferred language
- Don't send emails if the user's unit role is not active
- None
- None

Fix issues with staff emails

---

tests/test_graphql_api/test_reservation_unit/test_query.py
tilavarauspalvelu/api/graphql/types/reservation_unit/types.py
utils/date_utils.py

- User reservation count is now only affected by NORMAL type reservations
- None
- [TILA-3635](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3635)
[TILA-3635]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

User reservation count is now only affected by NORMAL type reservations

---

tilavarauspalvelu/api/graphql/types/application/filtersets.py

- See title
- None
- [TILA-3571](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3571)
[TILA-3571]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `sent_date` as an option for ordering applications

---

tests/test_graphql_api/test_application_section/test_filtering.py
tests/test_graphql_api/test_reservation/test_create.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/create_serializers.py
tilavarauspalvelu/api/graphql/types/reservation_unit/types.py
tilavarauspalvelu/models/reservation/queryset.py

new reservations. Any other reservation type should not be counted.
- Include only NORMAL reservations towards reservation count when creating
- None
- [TILA-3635](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3635)
[TILA-3635]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

Include only NORMAL reservations towards reservation count when creating

---

tilavarauspalvelu/utils/verkkokauppa/helpers.py

- Fixes admin URL reverse accessor used for mock order `receipt_url`
- None

Fix mock verkkokauppa reverse accessor name

---

tilavarauspalvelu/api/graphql/types/rejected_occurrence/filtersets.py

- See title. Required for frontend
- None
- None

Add rejected occurrence unit name filter

---

tests/test_graphql_api/test_application_round/test_filtering.py
tilavarauspalvelu/api/graphql/types/application_round/filtersets.py

- Add new `ongoing` filter to ApplicationRound GQL Endpoint
- None
- [TILA-3623](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3623)
[TILA-3623]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `ApplicationRound` ongoing filter to the GQL endpoint

---

tilavarauspalvelu/admin/reservation_unit/admin.py

- Fix link in Django Admin pointing to the old app name
- None
- [TILA-3659](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3659)
[TILA-3659]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Django Admin OriginHaukiResource ReservationUnit link

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
tests/test_integrations/test_email/test_email_service.py
tests/test_integrations/test_email/test_permission_context.py
tests/test_integrations/test_email/test_render_html.py
tests/test_integrations/test_email/test_render_text.py
tilavarauspalvelu/integrations/email/template_context/permissions.py

- See title.
- None
- [TILA-3636](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3636)
[TILA-3636]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update translations for permission and anonymization emails

---

tests/test_integrations/test_email/test_email_service.py
tilavarauspalvelu/models/application/queryset.py

- Fix the handled email send condition to look for applications in the `RESULTS_SENT` state instead of `HANDLED`
- None
- [TILA-3617](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3617)
[TILA-3617]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Fix application round handled email send condition

---

tests/factories/application.py
tests/test_actions/test_application_round_actions.py
tilavarauspalvelu/enums.py
tilavarauspalvelu/models/application_round/actions.py

- See title
- None
- [TILA-3618](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3618)
[TILA-3618]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow resetting application rounds in `RESULT_SENT` from admin panel

---

config/health_checks.py
config/settings.py

- Replaces `RedisHealthCheck` with a custom `RedisSentinelHealthCheck` that works with our platta redis sentinel setup
- Test in dev when merged (I've tested manually that the method should work)
- None
- None

Switch redis health check for custom sentinel check

---

.github/workflows/test.yml
config/settings.py
docker/Dockerfile
poetry.lock
pyproject.toml

- Updates project to Python 3.13
- Some dependencies have been updated
- New build dependencies added to Dockerfile
- Should test that local setups can be created for backend developers
- Windows is currently missing some pre-built wheels for Postgres, Redis, and uWSGI
- Ubuntu seems to work, and that can be used through WSL on windows
- Mac seems to work with small issues in GDAL which can be handled
- None …

Move project to python 3.13

---

tilavarauspalvelu/api/graphql/types/application_section/serializers.py
tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py

Fix not allowing blank details on mass reservation cancel and deny endpoints

---

.github/workflows/test.yml
tests/factories/origin_hauki_resource.py
tests/test_admin/test_django_admin_site.py
tests/test_external_services/test_hauki/test_hauki_resource_hash_updater.py
tests/test_external_services/test_tprek/test_tprek_unit_hauki_resource_importer.py
tests/test_graphql_api/test_reservation_unit/test_hauki_integration.py
tests/test_graphql_api/test_reservation_unit/test_query_permissions.py
tests/test_graphql_api/test_reservation_unit/test_update_timeslots.py
tests/test_models/test_application_section.py
tilavarauspalvelu/admin/helpers.py
tilavarauspalvelu/admin/request_log/admin.py
tilavarauspalvelu/admin/reservation_metadata_field/admin.py
tilavarauspalvelu/admin/reservation_statistic/admin.py
tilavarauspalvelu/admin/sql_log/admin.py

- Add tests for Django Admin
- None
- [TILA-3557](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3557)
[TILA-3557]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add tests for Django Admin

---

tilavarauspalvelu/migrations/0048_reservationunit_search_terms.py
tilavarauspalvelu/migrations/0049_populate_reservation_unit_vectors.py
tilavarauspalvelu/migrations/0050_change_reservation_unit_vectors_to_non_null.py

- Fixes wrong order of migration in recent postgres FTS update
- None
- None

Fix order or migrations

---

tilavarauspalvelu/api/graphql/schema.py

- See title, frontend request
- None
- None

Add application section relay node entrypoint

---

tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py

- See title. Required for tests to pass in other PRs
- None
- None

Fix two tests that broke after new year change

---

templates/email/html/seasonal_reservation_modified_series.jinja
templates/email/html/seasonal_reservation_rejected_series.jinja
tests/test_integrations/test_email/test_email_service.py
tilavarauspalvelu/admin/email_template/utils.py
tilavarauspalvelu/admin/recurring_reservation/admin.py
tilavarauspalvelu/integrations/email/template_context/common.py
tilavarauspalvelu/integrations/email/template_context/reservation.py

- Misc fixes related to recently added Seasonal Reservation emails
- None
- [TILA-3668](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3668)
[TILA-3668]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Seasonal Reservation Email Fixes

---

tests/test_graphql_api/test_reservation_unit/test_filtering.py
tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py

- Add `personsAllowed` filter for Reservation Units endpoint
- None
- [TILA-3738](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3738)
[TILA-3738]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Reservation Unit persons allowed filter

---

tilavarauspalvelu/integrations/email/template_context/common.py

- See title and commit.
- None
- [TILA-3760](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3760)
[TILA-3760]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix bug in sending email for reservation series with multiple weekdays

---

tilavarauspalvelu/management/commands/data_creation/create_reservations.py

- Fixes small error in test data
- None
- None

Create series reservations as BEHALF instead of NORMAL

---

tilavarauspalvelu/migrations/0063_clean_newlines_from_rich_text_fields.py

- In some cases the extra newlines were not removed. Patch the migration so extra newlines will be cleaned in staging and prod environments correctly
- None
- [TILA-3714](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3714)
[TILA-3714]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3714?atlOrigin=eyJpIjoiNWRkNTljNzYx …

Fix removing extra newlines in database migration

---

locale/fi/LC_MESSAGES/django.po

- Fixes translation for `access_type_end_date` help text in Finnish.
- None
- [TILA-3769](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3769)
[TILA-3769]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix one translation in admin panel

---

utils/utils.py

- Improve language detection for unauthenticated user by looking at the request referer header first if it exists
- None
- [TILA-3767](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3767)
[TILA-3767]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

Update text search language detection to look at referer header

---

docker/uwsgi.yml

- Fixes core server not booting in dev due to some env variables conflicting with uWSGI:s `strict` setting
- See if server boots in dev
- Need to change few env variables in Azure
- None

Don't use prefixed uWSGI settings due to `strict: true`

---

tests/factories/reservation.py
tests/test_graphql_api/test_reservation/test_cancel.py
tests/test_graphql_api/test_reservation/test_delete.py
tests/test_graphql_api/test_reservation/test_deny.py
tests/test_tasks/test_prune_inactive_reservations.py
tests/test_tasks/test_prune_reservation_with_inactive_payments.py
tilavarauspalvelu/api/graphql/types/reservation/mutations.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/cancellation_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/deny_serializers.py
tilavarauspalvelu/models/recurring_reservation/queryset.py
tilavarauspalvelu/models/reservation/queryset.py
tilavarauspalvelu/models/reservation_statistic/queryset.py
tilavarauspalvelu/services/pruning.py
tilavarauspalvelu/tasks.py
tilavarauspalvelu/typing.py

- Delete access code in Pindora if:
- Tentative reservation expires
- Unpaid reservation is not paid on time
- User cancels tentative reservation
- Handled reservation is denied
- Confirmed Reservation is canceled by the user
- Refactor some scheduled task code to not create import loops
- None
- …

Delete access code on cancellation, delete, deny, or inactive prune

---

tests/test_graphql_api/test_reservation/test_query.py
tilavarauspalvelu/api/graphql/types/reservation/types.py
utils/date_utils.py

- Make Pindora reservation info available from the ReservationNode GraphQL type.
- None
- [TILA-3788](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3788)
[TILA-3788]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Pindora info to Reservation API

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
tilavarauspalvelu/admin/reservation/admin.py
tilavarauspalvelu/admin/reservation/form.py
tilavarauspalvelu/admin/reservation_unit/admin.py
tilavarauspalvelu/admin/reservation_unit/form.py

- Add reservation unit UUID to reservation units for setting up a reservation unit in Pindora
- Add Pindora info to the admin panel for reservations
- Add Pindora info to the admin panel for reservation units
- None
- [TILA-3803](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3803)
- …

Access code admin panel stuff

---

config/settings.py
config/urls.py
tests/factories/payment_order.py
tests/factories/reservation.py
tests/plugins.py
tests/test_frontend_testing_api/test_reservation.py
tilavarauspalvelu/api/frontend_testing_api/helpers.py
tilavarauspalvelu/api/frontend_testing_api/reservation.py
tilavarauspalvelu/api/frontend_testing_api/serializers.py
tilavarauspalvelu/api/frontend_testing_api/urls.py
tilavarauspalvelu/api/frontend_testing_api/viewsets.py

- Framework for creating endpoints for Frontend Testing API
- Endpoint for creating testing data for a single reservation
- None
- [TILA-3746](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3746)
- [TILA-3775](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3775)
[TILA-3746]: …

Frontend Testing API

---

.github/workflows/test.yml

- Fix artifact downloading of test durations
- None
- None

Fix artifact download for test durations

---

config/settings.py

- Fix environment variables for Local and Docker
- None
- [TILA-3746](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3746)
[TILA-3746]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix FRONTEND_TESTING_API_ENABLED setting for Local and Docker envs

---

.github/workflows/test.yml

- Fixes [test runs not working in main](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/actions/runs/13153576738/job/36705587532) due to invalid artifact naming
- None
- None

Fix invalid artifact name for coverage results

---

tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py

Update created at when adding new reservation to series

---

.dockerignore
docker-compose.yml

- Fixes new testing API in Docker env by including factories and test plugins (`setup_now_tt`) in the docker file
- None
- None

Fix frontend testing API in Docker environment

---

backend/tilavarauspalvelu/api/graphql/types/reservation/mutations.py

Only delete tentative reservation from Pindora if using access code

---

.github/actions/poetry/action.yml
backend/tilavarauspalvelu/api/graphql/types/application_section/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/reservation/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py

- See title. Just for convenience when developing.
- Fix some cache keys in CI
- None
- [TILA-3815](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3815)
[TILA-3815]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ID/UUID filters to some GraphQL types

---

.github/pr-labeler.yml
.github/workflows/approve.yml
.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
.github/workflows/build-ui-docker.yml
.github/workflows/fast-forward.yml
.github/workflows/pr-labeler.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend-e2e.yml
.github/workflows/test-frontend.yml
.github/workflows/update_test_durations.yml
Dockerfile.final
README.md

- Fix and refactor various things related to the monorepo changes
- Fixes frontend not building in Azure due to incorrect Dockerfile.final after monorepo move
- None
- None

Monorepo fixes

---

apps/admin-ui/azure-pipelines-release.yml
apps/ui/azure-pipelines-release.yml
backend/azure-pipelines-dev.yml
backend/azure-pipelines-release.yml

- Don't start backend Azure dev builds if backend not changed
- Allow separate backend release builds using `-core` suffixed tags
- None
- None

Small fixes for Azure build pipelines

---

apps/ui/components/ExternalScripts.tsx

- Fix: matomo not loading due to unnecessary cookie check (the script is removed from dom if cookies are not accepted).
- Manual testing: check prod? that the tracking script pings if all cookies are accepted.
- None

fix: matomo tracking

---

apps/ui/components/ExternalScripts.tsx
apps/ui/pages/_app.tsx
apps/ui/public/init-matomo.js

- Fix: loading external tracking scripts.
- Manual testing: check that Matomo is loaded and is collecting data
- None

fix: external script loading

---

apps/ui/public/init-matomo.js

- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1560
- None

fix: matomo script name

---

apps/ui/components/reservation/Step1.tsx

- Fix for: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1537
- Fix: incorrect translation for a pay button.
- Manual testing.
- None
-  None

fix: incorrect translation key for pay button

---

backend/tests/test_graphql_api/test_reservation/test_working_memo_update.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/memo_serializers.py

- See title
- None
- [TILA-3832](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3832)
[TILA-3832]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow empty working memo in reservation memo update

---

apps/ui/middleware.ts
apps/ui/pages/reservations/[id]/cancel.tsx
apps/ui/pages/reservations/[id]/edit.tsx
apps/ui/pages/reservations/[id]/index.tsx
apps/ui/public/locales/en/errors.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/errors.json

- Fix: url accessing reservations that are in `Created` state. Redirect to funnel.
- Fix: url accessing reservations that are part of an application (edit / cancel). Redirect to application.
- Fix: block url accessing `admin` created reservations in `ui`.
- Manual testing: non typical reservations should have reasonable redirects / 404 and vice versa.
- None
[//]: # "This pull request resolves all or part of the following …

Fix redirect invalid reservations

---

apps/ui/middleware.ts

- Fix: reservation middleware for regular users.
- Fix for https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1574
- None
- None

fix: middleware checks for regular users

---

apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/spa/application-rounds/[id]/review/ApplicationsTable.tsx
apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/spa/my-units/[id]/index.tsx
apps/ui/components/application/ApplicationPage.tsx
apps/ui/components/application/module.ts
apps/ui/components/applications/ApplicationCard.tsx
apps/ui/pages/applications/[id]/preview.tsx
apps/ui/pages/applications/[id]/sent.tsx
apps/ui/pages/applications/[id]/view/index.tsx
apps/ui/public/locales/en/application.json
apps/ui/public/locales/en/applicationCard.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/fi/applicationCard.json
apps/ui/public/locales/sv/application.json
apps/ui/public/locales/sv/applicationCard.json
packages/common/src/components/StatusLabel.tsx
packages/common/src/components/statuses/ApplicationStatusLabel.tsx
packages/common/src/components/statuses/index.ts
packages/common/styles/global.scss
packages/common/styles/util.ts

- Fix: supplementary buttons should be black (same as secondary)
- Add: application status label to all applications (sent / unsent) same as in the card.
- Refactor: move application status to common.
- Fix: incorrect application for translation key.
- Fix: align status labels to top of title text `admin`
- Fix: calculate final (sent) step state based on backend status, not form status.
- Manual testing: with other application creation / modifications tests.
[//]: # "e.g. This PR breaks X and is waiting for …

Fix application creation

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/ReservationUnit/edit/SeasonalSection.tsx
apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx
packages/common/src/components/form/ControlledCheckbox.tsx
packages/common/src/components/form/ControlledRadioGroup.tsx
packages/common/src/components/form/index.ts

- Add: seasonal only reservation unit edit fields.
- Fix: seasonal error message.
- Manual testing: reservation unit edit `admin`
- None
- [TILA-3755](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3755)
[TILA-3755]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

Add editing seasonal only reservation unit

---

.github/dependabot.yml

- Daily schedules causes too much noise in the repo
- None
- None

Change dependabot to weekly schedule

---

backend/tilavarauspalvelu/api/graphql/types/reservation/filtersets.py

- Don't use a different implementation for `reservee_name`
- None
- [TILA-3855](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3855)
[TILA-3855]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use consistent `reservee_name` implementation

---

backend/config/settings.py

- Palvelukartta needs this to support their new dynamic subdomains in dev
- None
- None

Add `CORS_ALLOWED_ORIGIN_REGEXES`

---

backend/tilavarauspalvelu/models/reservation_unit_access_type/model.py

- See title. Regression tests to be added later.
- None
- None

Fix access type `end_date`

---

backend/pyproject.toml
backend/tests/factories/_base.py
backend/tests/helpers.py
backend/tilavarauspalvelu/management/commands/data_creation/utils.py
backend/tilavarauspalvelu/translation.py
backend/utils/date_utils.py
backend/utils/db.py
backend/utils/utils.py

Enable new preview rules from 0.9.0...0.9.9

---

backend/tests/test_actions/test_application_round_actions.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_create_missing_access_codes.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_update_access_code_is_active.py
backend/tilavarauspalvelu/api/graphql/types/application_section/serializers.py
backend/tilavarauspalvelu/api/graphql/types/application_section/types.py
backend/tilavarauspalvelu/integrations/keyless_entry/service.py
backend/tilavarauspalvelu/models/allocated_timeslot/queryset.py
backend/tilavarauspalvelu/models/application_round/actions.py
backend/tilavarauspalvelu/models/application_section/actions.py
backend/tilavarauspalvelu/models/application_section/model.py
backend/tilavarauspalvelu/models/application_section/queryset.py
backend/tilavarauspalvelu/models/recurring_reservation/queryset.py
backend/tilavarauspalvelu/models/reservation/queryset.py
backend/tilavarauspalvelu/models/reservation_unit_option/queryset.py
backend/tilavarauspalvelu/tasks.py

- Create access codes for series and seasonal bookings in the background
- Update access code is active for series and seasonal booking in the background
- None
- [TILA-3838](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3838)
- [TILA-3833](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3833)
[TILA-3838]: …

Series and sections Pindora tasks

---

backend/tests/test_graphql_api/test_recurring_reservation/helpers.py
backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code.py
backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code_permissions.py
backend/tilavarauspalvelu/api/graphql/mutations.py
backend/tilavarauspalvelu/api/graphql/schema.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/mutations.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/repair_access_code.py

- Add repair series access code endpoint to GraphQL schema
- None
- [TILA-3847](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3847)
[TILA-3847]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add series repair access code endpoint

---

backend/config/settings.py
backend/tests/test_integrations/test_hauki/test_hauki_api_client.py
backend/tests/test_integrations/test_hauki/test_hauki_resource_hash_updater.py
backend/tests/test_integrations/test_hauki/test_reservable_time_spans_client.py
backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py
backend/tilavarauspalvelu/integrations/opening_hours/reservable_time_span_client.py
backend/tilavarauspalvelu/models/origin_hauki_resource/model.py
backend/tilavarauspalvelu/models/recurring_reservation/validators.py

- Fixes an issue where sometimes new opening hours were not created, but old ones were deleted when `HaukiResourceHashUpdater` was run
- None
- [TILA-3901](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3901)
[TILA-3901]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Fix HAUKI opening hours fetching

---

backend/tests/test_integrations/test_hauki/test_hauki_resource_hash_updater.py
backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py
backend/tilavarauspalvelu/integrations/opening_hours/reservable_time_span_client.py
backend/tilavarauspalvelu/models/origin_hauki_resource/model.py

This reverts commit d970cc54a1eba9e849c6d2c5d39dd5ae7b3c6f99.
- Revert last commit due to unexpected bug to prevent production release
- None

Revert HAUKI Rewrite

---

apps/ui/components/LoginFragment.tsx
apps/ui/components/recurring/StartApplicationBar.tsx
apps/ui/hooks/useRemoveStoredReservation.ts
apps/ui/modules/util.ts
apps/ui/pages/recurring/[id]/index.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/browserHelpers.ts

- fix: include all query params when redirecting to login
- refactor: new reservation login redirect to SSR only
- Manual testing: see ticket (and the same for new reservations).
- None
- [TILA-3817](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3817)
[TILA-3817]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3817?a …

fix: new application redirect non logged users

---

apps/admin-ui/gql/gql-types.ts
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/reservationUnit.ts
packages/common/gql/gql-types.ts
tilavaraus.graphql

- fix: show reservation price on confirmation page based on subvention not handling state. 
- Manual testing: check Jira ticket.
- None
- [TILA-3792](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3792)
[TILA-3792]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

Fix confirmed price without subvention

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/my-units/recurring/RecurringReservationForm.test.tsx
apps/admin-ui/src/spa/my-units/recurring/WeekdaysSelector.tsx
apps/ui/components/reservation-unit/RelatedUnits.tsx
packages/common/src/components/form/ControlledNumberInput.tsx

- fix: incorrect price icon in related unit card `customer`
- fix: invalid aria role / pressed in recurring form `admin`
- fix: invalid translation key in number input `customer` (missing translation)
- None
- None

Fix aria issues

---

apps/ui/components/application/OrderedReservationUnitCard.tsx
apps/ui/components/common/Navigation.tsx
apps/ui/public/locales/fi/reservationUnitList.json
apps/ui/styles/variables.css
packages/common/src/components/Card.tsx
packages/common/styles/buttonCss.ts

- fix: set expand buttons (multiple) inside a card
- fix: tab z-index over mobile navigation
- fix: Finnish translation of a button
- Manual tests
- None
- None

Fix card button styling

---

apps/ui/gql/gql-types.ts
apps/ui/modules/reservationUnit.ts
apps/ui/modules/search.ts
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/test/test.gql.utils.ts

- fix: empty `""` persons allowed param bombing search query.
- fix: show subvented price range till reservation is handled.
- Automated tests: e2e robot
- None
- [TILA-3927](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3927)
- [TILA-3928](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3928)
[TILA-3927]: …

fix: filter out empty persons allowed param

---

apps/ui/hooks/useSearchQuery.tsx
apps/ui/test/recurring/[id]/index.test.tsx

- fix: broken fetch more button on search pages.
- disable tests that require search cache for now.
- Manual testing: search pages show more results.
- None
- [TILA-3931](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3931)
[TILA-3931]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

fix: search fetch more

---

backend/tests/factories/reservation_unit.py
backend/tests/factories/reservation_unit_access_type.py
backend/tilavarauspalvelu/management/commands/data_creation/create_caisa.py
backend/tilavarauspalvelu/management/commands/data_creation/create_reservation_units.py
backend/tilavarauspalvelu/management/commands/data_creation/utils.py

- Improve test data generation by adding access types
- Add access types to all reservation units
- Add some access code access types matching pre-defined [Pin Pad lists](https://admin.test.ovaa.fi/keypadlists) in Pindora
- None
- [TILA-3915](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3915)
[TILA-3915]: …

Add access types to test data

---

backend/tests/test_graphql_api/test_reservation/test_refund.py
backend/tilavarauspalvelu/models/reservation/validators.py

- Allow reservations that end in the future to be refunded
- None
- [TILA-3881](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3881)
[TILA-3881]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow reservations that end in the future to be refunded

---

backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py
backend/tilavarauspalvelu/models/origin_hauki_resource/actions.py
backend/tilavarauspalvelu/models/origin_hauki_resource/model.py

- Fix saving ReservationUnit due to Hauki error raised when already had latest opening hours
- Refactor code to OriginHaukiResource actions
- None
- [TILA-3939](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3939)
[TILA-3939]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Fix saving ReservationUnit due to Hauki error

---

backend/locale/fi/LC_MESSAGES/django.po
backend/locale/sv/LC_MESSAGES/django.po
backend/tilavarauspalvelu/admin/__init__.py
backend/tilavarauspalvelu/admin/origin_hauki_resource/admin.py
backend/tilavarauspalvelu/admin/payment_order/admin.py
backend/tilavarauspalvelu/admin/recurring_reservation/admin.py
backend/tilavarauspalvelu/admin/recurring_reservation/form.py
backend/tilavarauspalvelu/admin/reservation/admin.py
backend/tilavarauspalvelu/admin/reservation/filters.py
backend/tilavarauspalvelu/admin/reservation/form.py
backend/tilavarauspalvelu/admin/reservation_unit/admin.py
backend/tilavarauspalvelu/admin/reservation_unit/form.py
backend/tilavarauspalvelu/admin/reservation_unit_access_type/admin.py
backend/tilavarauspalvelu/admin/reservation_unit_pricing/admin.py
backend/tilavarauspalvelu/admin/unit/admin.py
backend/tilavarauspalvelu/admin/unit_role/admin.py

- See title, commits, and the ticket for details
- None
- [TILA-3878](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3878)
[TILA-3878]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new fields and filters to the Django admin panel

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/reservations/[id]/ReservationKeylessEntrySection.tsx
apps/admin-ui/src/spa/reservations/[id]/queries.tsx
apps/ui/components/recurring/RecurringCard.test.tsx
apps/ui/components/recurring/RecurringCard.tsx
apps/ui/components/reservation-unit/Head.tsx
apps/ui/components/search/SingleSearchReservationUnitCard.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/search.ts
apps/ui/test/test.gql.utils.ts
backend/tests/test_graphql_api/test_reservation/test_create.py
backend/tests/test_graphql_api/test_reservation/test_staff_create.py
backend/tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py
backend/tilavarauspalvelu/api/graphql/types/reservation_unit/types.py
backend/tilavarauspalvelu/integrations/keyless_entry/client.py
backend/tilavarauspalvelu/services/first_reservable_time/first_reservable_time_helper.py
backend/tilavarauspalvelu/services/first_reservable_time/first_reservable_time_reservable_time_span_helper.py
backend/tilavarauspalvelu/services/first_reservable_time/first_reservable_time_reservation_unit_helper.py
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Add `effectiveAccessType` to Reservation Unit List GQL endpoint, for what access type is used for the selected filter date
- Use the new field in customer UI
- None
- [TILA-3888](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3888)
- [TILA-3893](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3893)
[TILA-3888]: …

First Reservable Time Access Type

---

apps/ui/components/application/ApprovedReservations.tsx
apps/ui/components/reservation-unit/Head.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/fragments.tsx
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/reservationUnit.ts
apps/ui/public/locales/en/application.json
apps/ui/public/locales/en/common.json
apps/ui/public/locales/en/reservations.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/fi/common.json
apps/ui/public/locales/fi/reservations.json
apps/ui/public/locales/sv/application.json
apps/ui/public/locales/sv/common.json
apps/ui/public/locales/sv/reservations.json

- displays the access type (and it's access code where applicable) in the reservations listing view for an approved seasonal appplication (see [ticket](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3842) for specs on what should be shown where)
- shows the access types and their validity periods in the instructions for each reservation series in the above mentioned listing view as requested in [TILA-3843](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3843)
- extracts `getReservationUnitAccessPeriods` to a reservationUnit helper function
- adds `ApplicationSectionReservationUnit` and `PindoraInfo` fragments
[//]: # "Help your fellow reviewer and write a short description of the fastest way to test your …

Display access type & code in an approved application's reservation listing

---

backend/locale/fi/LC_MESSAGES/django.po
backend/locale/sv/LC_MESSAGES/django.po
backend/tests/test_graphql_api/test_reservation/test_staff_modify.py
backend/tests/test_graphql_api/test_reservation/test_staff_repair_access_code.py
backend/tests/test_graphql_api/test_reservation/test_staff_repair_access_code_permissions.py
backend/tests/test_integrations/test_email/helpers.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified_access_code.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series_access_code.py
backend/tests/test_tasks/test_create_missing_pindora_reservations.py
backend/tests/test_tasks/test_update_pindora_access_code_is_active.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_repair_access_code_serializers.py
backend/tilavarauspalvelu/integrations/email/template_context/common.py
backend/tilavarauspalvelu/integrations/email/template_context/reservation.py
backend/tilavarauspalvelu/integrations/keyless_entry/service.py

- Update translation for `"The door code has changed"`
- Send `RESERVATION_MODIFIED` instead of `RESERVATION_MODIFIED_ACCESS_CODE` when access code is added/activated for a reservation
- None
- [TILA-3906](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3906)
- [TILA-3907](https://helsinkisolutionoffice.atlassian.net/browse/TILA …

Access code email modifications

---

backend/tests/test_graphql_api/test_recurring_reservation/test_change_access_code.py
backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/change_access_code.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/repair_access_code.py

- Fixes email sending in series change access code and repair access code endpoints
- None
- [TILA-3959](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3959)
[TILA-3959]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix email sending in series access code endpoints

---

backend/tilavarauspalvelu/api/graphql/types/reservation/types.py

- Fix permission checks for reservation access type fields. Reservee needs to see them for reservations from applications
- None
- [TILA-3962](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3962)
[TILA-3962]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

Remove permissions to access type fields on reservation

---

apps/ui/components/reservation/ReservationCard.tsx
apps/ui/gql/gql-types.ts

- Fix: reservation card missing the reservation unit name.
- Automated tests: e2e robot
- None
- None

Fix missing reservation unit name in the card

---

apps/admin-ui/gql/gql-types.ts
apps/ui/components/application/ApprovedReservations.tsx
apps/ui/gql/gql-types.ts
apps/ui/modules/queries/reservationUnit.tsx
apps/ui/modules/reservable.test.ts
backend/tilavarauspalvelu/api/graphql/types/reservation/types.py
packages/common/gql/gql-types.ts
tilavaraus.graphql

- Backport hotfix: https://github.com/City-of-Helsinki/tilavarauspalvelu-core/releases/tag/v1.21.1
- None
- None

Backport calendar hotfix

---

.github/workflows/build-ui-docker.yml
Dockerfile
apps/admin-ui/next.config.mjs
apps/admin-ui/src/env.mjs
apps/ui/env.mjs
apps/ui/next.config.mjs

- Temporary solution to Sentry upload breaking frontend build pipes.
- Disable source map upload for now.
- Add config token to pipe configuration to enable / disable source map uploads.
- None
- None

Disable sentry sourcemap upload

---

apps/ui/pages/404.tsx
apps/ui/pages/500.tsx
apps/ui/pages/_error.tsx
packages/common/src/components/ErrorContainer.tsx

- Reinstate previous 404 and 500 error pages to client ui and add them to the admin ui, in order to fix static translations
- None
- [TILA-3988](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3988)
[TILA-3988]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

fix: Error page translations

---

backend/tilavarauspalvelu/management/commands/data_creation/create_misc.py

- Adds "create missing pindora access codes" and "fic access code is active state" background jobs to tests data
- None
- [TILA-3972](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3972)
[TILA-3972]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Add periodic tasks for pindora updates to test data

---

apps/admin-ui/src/spa/my-units/recurring/RecurringReservation.tsx

- Fix: `my-units/recurring` considering `pk = 1` to be invalid. 
- None
- None

Fix pk = 1 considered invalid for recurring page

---

backend/tests/test_graphql_api/test_reservation_unit/test_access_types.py
backend/tilavarauspalvelu/api/graphql/types/reservation_unit/serializers.py

- See title
- https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/1725
- [TILA-3882](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3882)
[TILA-3882]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Don't allow adding new reservation units without active access type

---

apps/ui/components/reservation/ReservationInfoCard.tsx

- Add testid to reservation info card for access code.
- None
- None

Add testid for access code in info card

---

apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/i18n/locales/fi/errors.json
apps/ui/public/locales/en/errors.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/errors.json
packages/common/src/components/ErrorContainer.tsx

- "Anna palautetta" -> "Ota yhteyttä" button texts in error pages
- None

fix: Error page "give feedback" -> "contact us"

---

.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
.github/workflows/build-ui-docker.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml

- Add GHA `repository_dispatch` for `update-graphql-schema`. This is required to be in `main` to trigger in any PRs made.
- None

Add GHA `repository_dispatch` for `update-graphql-schema`

---

apps/admin-ui/src/helpers/date.ts
apps/admin-ui/src/spa/ReservationUnit/edit/form.ts

- Fix reservation unit date time validator missing `!`.
- Refactor replace time utilities with ones that return `Date` instead `ISO string`
- Fix don't require both `end` and `begin` for scheduling to be set.
- Manual testing: check Jira ticket.
- None
- [TILA-4006](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4006)
[TILA-4006]: …

Fix reservation unit cant be scheduled

---

.github/dependabot.yml

- Fix backend directory paths for dependabot
- None
- None

Fix backend directory paths for dependabot

---

apps/ui/gql/gql-types.ts
apps/ui/pages/recurring/[id]/index.tsx

- Block users from accessing ApplicationRound page when the round status is not OPEN
- Manual testing
- None
- [TILA-3858](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3858)
[TILA-3858]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Block users from accessing ApplicationRound page when they shouldn't

---

apps/ui/modules/reservationUnit.test.ts

- Fix: test flaking when run close to midnight.
- None
- None

Fix flaky test during midnight

---

backend/tilavarauspalvelu/api/graphql/types/application/filtersets.py

- Fixes duplicate results in application text search
- None
- [TILA-4016](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4016)
[TILA-4016]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix duplicate fields in application text search

---

apps/ui/components/reservation/ReservationTimePicker.tsx
packages/common/src/calendar/Calendar.tsx

- Remove unnecessary calendar event wrapper div that caused unknown props to be passed to DOM
- None
- None

Cleanup remove unnecessary wrapper div

---

apps/ui/components/search/SingleSearchForm.tsx
apps/ui/modules/search.ts

- use `ignoreMaybeArray()` in stead of the (too complicated) `mapSingleBooleanParamToFormValue`
- None
- [TILA-3934](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3934)
[TILA-3934]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

fix: show only reservable checkbox

---

apps/ui/components/reservation-unit/Images.tsx
apps/ui/components/reservation-unit/ReservationInfoContainer.tsx
apps/ui/pages/reservation-unit/[id].tsx
packages/common/src/helpers.test.ts
packages/common/src/helpers.ts

- Fix missing translation for too many reservations.
- Refactor cleaner utility function to convert list of things into a formatted string.
- Fix don't make post card sized modals.
- Manual testing: modals `ui`, too many reservations backend error (toast) translations.
- Automated testing: list formatting.
- None
- None

Fix missing too many reservations error translation

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/ReservationUnit/edit/index.tsx
apps/admin-ui/src/spa/notifications/page.tsx
apps/ui/gql/gql-types.ts
backend/config/settings.py
backend/tests/plugins.py
backend/tests/test_graphql_api/test_banner_notification/test_query_permissions.py
backend/tests/test_graphql_api/test_banner_notification/test_sorting.py
backend/tests/test_graphql_api/test_recurring_reservation/test_query.py
backend/tests/test_graphql_api/test_reservation/test_query.py
backend/tests/test_graphql_api/test_reservation_unit/test_filtering.py
backend/tests/test_graphql_api/test_reservation_unit/test_query_permissions.py
packages/common/gql/gql-types.ts
packages/common/src/queries/fragments.tsx
tilavaraus.graphql

- Remove unoptimized default fields of those that are translated by enabling `"EXPERIMENTAL_REMOVE_TRANSLATION_BASE_FIELDS": True`
- None
- [TILA-3427](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3427)
[TILA-3427]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

Remove unoptimized translated fields from graphql queries

---

backend/tests/test_graphql_api/test_reservation/test_query.py
backend/tests/test_graphql_api/test_reservation_unit/helpers.py
backend/tilavarauspalvelu/api/graphql/types/reservation/types.py
backend/tilavarauspalvelu/models/reservation_unit_pricing/queryset.py

- Add `appliedPricing` field to the reservation GraphQL type. This fetches information on the pricing that is/should be used for the reservation
- None
- [TILA-4045](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4045)
[TILA-4045]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

Add `appliedPricing` to Reservation GraphQL type

---

apps/admin-ui/src/component/ReservationTypeForm.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/AllocationColumn.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/reservation-units/Filters.tsx
apps/admin-ui/src/spa/reservations/Filters.tsx
apps/ui/components/recurring/SeasonalSearchForm.tsx
apps/ui/components/search/SingleSearchForm.tsx
apps/ui/components/search/styled.ts
packages/common/src/components/IconButton.tsx
packages/common/src/components/ShowAllContainer.tsx
packages/common/styled/util.ts

- Fix: layout issues when using responsive grid container
- Refactor: cleaner interface (no double containers with max size = 0).
- Refactor: replace `Children` with explicit items: `T | T[]`
- Refactor: improve type checking use `JSX.Element` instead of `ReactNode` and extend for HTML attributes.
- Manual testing: check that "Show more" filters works as expected (responsive).
- None
[//]: # "This pull request …

Refactor Show all container to use grid

---

.prettierignore
apps/admin-ui/src/common/fragments.tsx
apps/admin-ui/src/i18n/locales/fi/errors.json
apps/admin-ui/src/spa/application-rounds/[id]/review/ApplicationsTable.tsx
apps/admin-ui/src/spa/applications/[id]/index.tsx
apps/admin-ui/src/styles/variables.css
apps/ui/components/application/ApplicantInfoPreview.tsx
apps/ui/components/application/form.ts
apps/ui/modules/queries/application.tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx
apps/ui/public/locales/en/application.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/application.json
apps/ui/public/manifest.webmanifest
apps/ui/public/scripts/init-matomo.cjs
apps/ui/tsconfig.json
packages/common/src/queries/application.tsx
packages/common/src/queries/fragments.tsx
packages/common/styles/global.scss
packages/eslint-config-custom/react.mjs
packages/tsconfig/base.json
pnpm-workspace.yaml
scripts/gql-pluck.mjs
turbo.json

- Remove GraphQL convenience fragments.
- Run prettier for files that are excluded from eslint.
- None
- None

Refactor remove GQL convenience fragments

---

backend/tests/test_graphql_api/test_reservation/test_create.py
backend/tests/test_helauth/test_pipeline_additions.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/create_serializer.py
backend/tilavarauspalvelu/integrations/helauth/pipeline.py
backend/tilavarauspalvelu/integrations/helsinki_profile/clients.py
backend/tilavarauspalvelu/integrations/helsinki_profile/parsers.py
backend/tilavarauspalvelu/integrations/helsinki_profile/typing.py

- Store Reservation Prefill Info to user session, and use it if profile authentication has expired when creating a reservation
- None
- [TILA-4029](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4029)
[TILA-4029]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

Fix missing profile login info

---

backend/locale/fi/LC_MESSAGES/django.po
backend/locale/sv/LC_MESSAGES/django.po
backend/templates/email/html/reservation_requires_payment.jinja
backend/templates/email/text/reservation_requires_payment.jinja
backend/tests/factories/reservation_unit.py
backend/tests/test_graphql_api/test_reservation/helpers.py
backend/tests/test_graphql_api/test_reservation/test_approve.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_requires_payment.py
backend/tilavarauspalvelu/admin/email_template/forms.py
backend/tilavarauspalvelu/admin/email_template/utils.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
backend/tilavarauspalvelu/integrations/email/main.py
backend/tilavarauspalvelu/integrations/email/template_context/common.py
backend/tilavarauspalvelu/integrations/email/template_context/reservation.py
backend/tilavarauspalvelu/integrations/email/typing.py
backend/tilavarauspalvelu/models/reservation/model.py
backend/utils/date_utils.py

- Convert unused payment required template for handled payments
- Send "requires payment" email when approving reservations paid in webshop
- None
- [TILA-3808](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3808)
[TILA-3808]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Modify unused payment required template for handled payment use

---

backend/tests/factories/user.py
backend/tests/test_graphql_api/test_application/test_create.py
backend/tests/test_graphql_api/test_application/test_send.py
backend/tests/test_graphql_api/test_reservation/test_adjust_time.py
backend/tests/test_graphql_api/test_reservation/test_create.py
backend/tilavarauspalvelu/models/user/validators.py

- Allow Ext/Guest AD superuser to make reservations and applications
- None
- None

Allow external/guest AD superusers to make reservations/applications

---

.github/workflows/upload_sentry_sourcemaps.yml

- Fix sentry source map generation broken because it didn't run codegen before build.
- Build change: CI pipes either work or no.
- None
- None

Fix sentry source map generation codegen

---

apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEvents.tsx

- Fix allocation page overflowing on mobile.
- Manual testing: allocation page layout (CSS only change).
- None
- [TILA-4086](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4086)
[TILA-4086]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix allocation page mobile layout breaking

---

apps/admin-ui/src/spa/applications/[id]/index.tsx

- Fix `admin-ui` show rejected options if they are rejected in allocation tool also (e.g. `locked`).
- Manual testing
- None
- [TILA-4088](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4088)
[TILA-4088]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

Fix application show rejected if locked from allocation

---

apps/ui/modules/queries/fragments.tsx
apps/ui/modules/serverUtils.ts
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx
backend/tilavarauspalvelu/api/graphql/types/payment_order/types.py
tilavaraus.graphql

- Adds `reservation` field to payment order node. Deprecate `reservationPk`.
- None
- [TILA-4081](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4081)
[TILA-4081]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add reservation relation to payment order node

---

apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/spa/ReservationUnit/edit/components/SeasonalSection.tsx

- Fix invalid logo translation.
- Fix missing React key by adding a fragment. 
- None
- None

Fix translation logo

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/HomePage.tsx

- Custom user specific welcome message to Admin UI
- None
- None
- None

Custom welcome message to Admin UI

---

apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/spa/reservations/[id]/index.tsx
apps/ui/components/reservation/PaymentNotification.test.tsx
apps/ui/components/reservation/PaymentNotification.tsx
apps/ui/components/reservation/ReservationCard.tsx
apps/ui/modules/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/modules/urls.ts
apps/ui/pages/reservations/[id]/index.tsx
packages/common/src/common/util.ts

- Fix incorrect 12h time format (use `HH` instead of `hh`)
- Fix date-time separator not localised.
- Fix invalid translation key.
- Fix reservation payment button going to handled reservation payment instead of direct checkout.
- Add a common function to get payment link that switches correctly between the reservation type.
- Add payment button to reservation card for direct payments (when needed).
- Manual testing: both direct payments and handled reservation payments.
[//]: # "e.g. This PR breaks X and is …

Fix handled reservation payment links and texts

---

apps/admin-ui/src/schemas/reservation.ts
apps/admin-ui/src/spa/application-rounds/[id]/index.tsx
apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx
apps/admin-ui/src/spa/my-units/[id]/UnitCalendar.tsx

- Fix validate ReserveeType in `admin` create a single reservation.
- Fix don't allow tab focus to past reservation times in `my-units` Calendar.
- Fix nowrap in allocation button.
- Manual testing: see Jira ticket.
- None
- [TILA-4160](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4160)
[TILA-4160]: …

Fix reservation form validation

---

apps/admin-ui/src/lib/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/lib/application-rounds/[id]/allocation/modules/applicationRoundAllocation.ts

- Fix allocation times not sorted by day correctly.
- Fix allocation total number possible spaces incorrect by one.
- Manual testing: check Jira tickets.
- None
- [TILA-4070](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4070)
- [TILA-4069](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4069)
[TILA-4070]: …

Fix allocation sort bug

---

apps/admin-ui/src/component/MainLander.tsx
apps/admin-ui/src/component/Navigation.tsx
apps/admin-ui/src/component/PageWrapper.tsx
apps/admin-ui/src/pages/_app.tsx
apps/admin-ui/src/pages/auth/logout/index.tsx
apps/ui/components/reservation/SubventionSuffix.tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/src/browserHelpers.ts
packages/common/src/components/SearchButton.tsx
packages/common/src/reservation-form/MetaFields.tsx

- Small non-critical fixes to Admin UI, see commit messages for details
- None

Small fixes to Admin UI router refactor

---

apps/admin-ui/src/lib/my-units/[id]/CreateReservationModal.tsx

fix: timeCollisions translation key

---

apps/admin-ui/src/pages/reservations/[id]/edit.tsx
apps/admin-ui/src/pages/reservations/[id]/index.tsx
apps/admin-ui/src/pages/reservations/[id]/series/index.tsx

- Fix incorrect admin series page permission check.
- Refactor remove extra queries from permission checks.
- Manual testing: see Jira ticket.
- None
- [TILA-4193](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4193)
[TILA-4193]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Fix admin reservation series permission check

---

apps/admin-ui/src/hooks/useReservationCalendarData.ts

- Fix: Incorrect reservation calendar end time
- Manual testing: check Jira.
- None
- [TILA-4200](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4200)
[TILA-4200]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Incorrect reservation calendar end time

---

backend/tests/factories/user.py
backend/tilavarauspalvelu/dataclasses.py

- See title
- None
- [TILA-4166](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4166)
[TILA-4166]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Count "high" as strong login from ID token

---

backend/config/settings.py
backend/local_settings_example.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation_series.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation_unit.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_seasonal_booking.py
backend/tilavarauspalvelu/integrations/keyless_entry/client.py
backend/tilavarauspalvelu/integrations/keyless_entry/exceptions.py

- Add mocking to the Pindora client that can be used locally for testing
- None
- [TILA-4115](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4115)
[TILA-4115]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add local mocking to Pindora client

---

backend/locale/fi/LC_MESSAGES/django.po
backend/locale/sv/LC_MESSAGES/django.po
backend/tilavarauspalvelu/admin/application_section/admin.py
backend/tilavarauspalvelu/admin/reservation/admin.py
backend/tilavarauspalvelu/admin/reservation_series/admin.py
backend/tilavarauspalvelu/admin/reservation_unit/admin.py

- Add search to reservation, reservation series, application section, and reservation unit views by their external UUIDs
- None
- [TILA-4162](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4162)
[TILA-4162]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …

Add search by `ext_uuid` to admin panel views

---

backend/tilavarauspalvelu/api/graphql/types/application/serializers.py

- Use `APPLICATION_ADULT_RESERVEE_REQUIRED` error code in validation of age in application create
- None
- [TILA-4092](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4092)
[TILA-4092]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

Fix error code returned by application create age validation

---

backend/config/settings.py
backend/config/urls.py
backend/tests/test_rest_api/test_create_robot_test_data.py
backend/tilavarauspalvelu/api/rest/utils.py
backend/tilavarauspalvelu/api/rest/views.py
backend/tilavarauspalvelu/management/commands/create_robot_test_data.py

- Add script for generating robot test data
- Add a management command for running the script
- Add endpoint for running the command with authentication, rate limiting, and parallel run locking
- None
- [TILA-4172](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4172)
[TILA-4172]: …

Add script for creating robot test data

---

backend/tests/test_rest_api/test_create_robot_test_data.py
backend/tilavarauspalvelu/management/commands/create_robot_test_data.py

- `factory-boy` is a test dependency, which is not available in Platta environments. Migrations are failing in dev because of this. Use regular Django queryset methods instead.
- None
- None

Create robot data without using factories

---

.github/dependabot.yml
.github/workflows/upload_sentry_sourcemaps.yml

- Fix sentry source map upload (enable generating them in workflow).
- Replace old lint dependencies in dependabot.
- None
- [TILA-4194](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4194)
[TILA-4194]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

Fix sentry source map upload

---

apps/admin-ui/src/hooks/useCreateReservationSeries.tsx
backend/tests/test_frontend_queries/test_admin_ui_mutations.py
backend/tests/test_graphql_api/test_reservation_series/helpers.py
backend/tests/test_graphql_api/test_reservation_series/test_create_series.py
backend/tests/test_graphql_api/test_reservation_series/test_create_series_permissions.py
backend/tilavarauspalvelu/api/graphql/types/reservation_series/mutations/create_series.py
backend/tilavarauspalvelu/management/commands/data_creation/create_reservation_related_things.py
tilavaraus.graphql

- Add "municipality" meta field to test data
- Make "reservationDetail.user" a hiddden input for current user
- None
- None

Undine Fixes

---

apps/admin-ui/src/hooks/useStaffReservationMutation.ts
apps/admin-ui/src/pages/reservation-units/[pk]/index.tsx
apps/admin-ui/src/schemas/reservationMeta.ts
apps/admin-ui/src/schemas/reservationSeries.ts
apps/ui/components/application/funnel/OrganisationForm.tsx
apps/ui/components/application/funnel/form.ts
apps/ui/modules/search.ts
apps/ui/pages/applications/[id]/page3.tsx
apps/ui/test/search.mocks.ts
packages/common/src/components/form/ControlledCheckbox.tsx

- Fix validate email when creating new reservation series. `admin`
- Fix application form toggling no VAT number caused incorrect form validation errors `ui`
- Fix remove date start from seasonal search, caused query errors in test data. `ui`
- Fix remove `isArchived` from Create reservation unit mutation (removed from the API) `admin`
- Fix remove refetching new reservation units (they don't yet exist).
- Manual testing.
- None …

Undine misc frontend fixes

---

backend/tests/test_graphql_api/test_reservation/test_query.py
backend/tilavarauspalvelu/api/graphql/extensions/utils.py

- Fixes issue where some roles that don't have permission to access users can access reservees if they have access to the reservation's unit.
- None
- None

Override field permission checks in reservation node

---

backend/tilavarauspalvelu/api/graphql/types/application_round/queries/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/rejected_occurrence/queries/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/reservation_unit/queries/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/resource/queries/filtersets.py
backend/tilavarauspalvelu/api/graphql/types/space/queries/filtersets.py

- Add missing `distinct=True` on some Filters where they are needed
- None
- None

Fix missing `distinct=True` on filters

---

apps/ui/modules/search.ts

- Uses the localised version of `UnitOrderSet` in order for the options to be in alphabetical order according to the translated value
- None
- [TILA-4180](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4180)
[TILA-4180]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

Search page select options into localised alphabetic order

---

backend/templates/email/html/reservation_cancelled.jinja
backend/templates/email/text/reservation_cancelled.jinja
backend/tests/test_integrations/test_email/test_email_types/test_reservation_cancelled.py
backend/tilavarauspalvelu/integrations/email/template_context/reservation.py
backend/tilavarauspalvelu/integrations/email/typing.py

- Add handled payment due by date to cancel reservation email if cancellation was made due to no payment for handled paid reservation
- None
- [TILA-4226](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4226)
[TILA-4226]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

Add handled due by date to cancel email if not paid

---

apps/admin-ui/src/lib/reservation-units/ReservationUnitsDataLoader.tsx
backend/tests/test_graphql_api/test_reservation_unit/test_filtering.py
backend/tilavarauspalvelu/api/graphql/types/reservation_unit/queries/filtersets.py
tilavaraus.graphql

- See title
- None
- [TILA-4195](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4195)
[TILA-4195]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `onlyWithManagePermission` filter to reservation units

---

backend/tilavarauspalvelu/management/commands/create_robot_test_data.py

- Fix issue where some reservation unit options prevented deletion old data
- Fix issue where there could be multiple users with the same email
- None
- None

Fix few final errors in robot test data generation

---

backend/tilavarauspalvelu/services/export/reservation_unit_exporter.py

- Fix missing "Updated at" column name from reservation unit export
- None
- [TILA-4235](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4235)
[TILA-4235]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix missing column name in reservation unit export

---

backend/config/settings.py
backend/tilavarauspalvelu/apps.py
backend/tilavarauspalvelu/management/commands/data_creation/create_misc.py
backend/tilavarauspalvelu/management/commands/populate_celery_tasks.py
backend/tilavarauspalvelu/tasks.py
backend/tilavarauspalvelu/typing.py

- When migrations are run, create pre-defined Celery tasks to database (as disabled)
- Remove deprecated Celery tasks
- None
- [TILA-4127](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4127)
[TILA-4127]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

Auto create Celery Tasks

---

.github/workflows/test-backend.yml
backend/config/wsgi.py
backend/docker/Dockerfile

- Locale is not picked up in platta correctly, so set up the locale during application boot if missing (continue fixing from #2043)
- None
- None

Setup locale in `wsgi.py` if not set

---

.github/workflows/test-backend.yml

- [Previous fix](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/pull/2055) didn't work. Try this one instead.
- None
- None

Fix SonarCloud upload in main branch, again

---

backend/config/settings.py

- Fix issue in platta mid-hook resulting from #2071
- None
- None

Fix mid-hook database setting

---

.github/dependabot.yml
apps/admin-ui/package.json
pnpm-lock.yaml

- Dependabot: move breaking package updates to a separate group. 
- Chore: bump form-data due to critical security vulnerability.
- Automated tests: CI / tool update with security patch.
- None
- [TILA-4219](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4219)
[TILA-4219]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4219?atlOrigin=e …

Fix dependabot frontend

---

.npmrc
graphql.config.ts
package.json
pnpm-workspace.yaml

- Update pinned pnpm package manager version.
- None
- None

chore: bump pnpm to 10.17.1
