.github/workflows/sample_action.yml

This is more or less a POC for using github actions for CI. There is still some things ongoing and lack of documentation about openshift, so currently this doesn't actually run on every commit and is only setup to be triggered manually. Actual CI implementation will need to wait a bit.

TILA-82 Basic github actions file.

---

README.md
pytest.ini
tilavarauspalvelu/settings.py

This should make it easier to see and fix project level warnings.

Add specific third party warnings to filterwarnings to reduce noise

---

api/tests/conftest.py

Remove naive datetime warnings by using timezone-aware datetime-objects in tests. I didn't bother to get rid of deprecation warning from `NullableCurrentUserDefault`, since that is only temporary and will be removed/changed in upcoming versions.

Remove naive datetime warnings

---

api/application_period_api.py
api/applications_api.py
api/reservation_units_api.py
api/reservations_api.py
api/resources_api.py
api/services_api.py
api/space_api.py
api/urls.py
tilavarauspalvelu/settings.py

I also disabled some endpoints that clearly aren't ready to be open, lacks tests etc. I think it's best to open endpoints as we need and use them and prevent making endpoints for every model if we don't know for sure that they are needed separately. It keeps documentation clean and makes understanding the API easier.
I hope review from as many developers as possible, because understanding who the API works is crucial for whole team.

TILA-279 | Document API endpoints as OpenAPI using DRF spectacular

---

api/reservations_api.py

The display option was before *args so it was applied as first argument
not as kwarg => caused it to be display=True when it shouldn't

Fix optional AgeGroupSerializer display option

---

requirements.txt

the version 3.0.x is to be deprecated in April

Bump django to 3.1.7

---

api/reservation_units_api.py

Very simple and is registered automatically by drf-spectacular. This allows you to filter reservation units by primary key like this: http://localhost:8000/v1/reservation_unit/?ids=4,9

TILA-295 | Filter reservation units with comma separated list of ids

---

api/allocation_results_api.py
api/tests/conftest.py
api/tests/test_allocation_results_api_permission.py
permissions/api_permissions.py

First of all makes the allocation results api end point as readonly. 
Second, makes the allocation results viewable only for service sector and general admin. => service sector id is required parameter.

Tila 546 | Allocation results API permission changes

---

allocation/allocation_data_builder.py
api/hauki_api.py
applications/tests/test_reservation_creation.py
applications/utils/reservation_creation.py
opening_hours/hours.py

Remove the need for giving HAUKI_ORIGIN_ID as part of the resource_id in
get_opening_hours function.
Moves the HAUKI_ORIGIN_ID to be added to resource_id when doing the
query to HAUKI

Refactor get_opening_hours resource_id parameter

---

applications/models.py

Its manytomany field and its not required so blank=True to make it work in admin.

Make declined reservation units not required

---

api/reservation_units_api.py

Previously returned "small" sized image rather than the "medium" one.
TILA-552

TILA-552 | Fix getting medium sized image in res unit serializer

---

api/base.py

Previously using class based variable would be causing some unwanted behavior in rendering multiple translated fields
TILA-632

TILA-632 | Use instance variable for declaring fields in TranslatedFieldSerializer

---

.dockerignore
.env.example
.gitignore
Dockerfile
deploy/entrypoint.sh
docker-compose.yml
requirements.in
requirements.txt
tilavarauspalvelu/__init__.py
tilavarauspalvelu/celery.py
tilavarauspalvelu/settings.py

Configures celery for running backend tasks. 
Note that this isn't production ready, specifically docker related stuff, since we are using filesystem backend. 
But this gives use a way to start implementing backend tasks with celery without doing changes to infrastructure, and configuration is done so that moving this to redis or similar message queue should be very simple.

TILA-606 Configure celery for running backend tasks.

---

api/graphql/base_serializers.py
api/graphql/reservation_units/reservation_unit_mutations.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/spaces/space_types.py
api/graphql/tests/snapshots/snap_test_purposes.py
api/graphql/tests/test_purposes.py

Base classes for handling updating and creating objects with graphql while reusing drf serializers. Example usage with update and create of purposes.

Tila 707 create update structure

---

requirements.in
requirements.txt

Security fixes.
also bumps coverage to 6.0b1 because safety.

Bump django to 3.1.13 and pillow to 8.3.1

---

api/graphql/schema.py

The resolver method for unit_by_pk gql query  was missing and caused the
unit_by_pk not to work properly (not returning anything).
This fixes that by adding the resolver method which was got wiped out or
was missing in the first place

Add resolve method for unit_by_pk

---

api/graphql/base_mutations.py
api/graphql/tests/test_units.py
api/graphql/units/unit_serializers.py
permissions/api_permissions/graphene_permissions.py

Also finetunes permissions checks for auth serializer mutations to raise permission error.

TILA-769 | Unit mutation enchancements

---

api/graphql/tests/test_reservation_units.py
opening_hours/hours.py
opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py

Previously we were using the resource id from hauki as origin id from
hauki but those two are separate ids and that caused some problems in
OpeningHoursClient.
This fixes that so that the origin id is read which is the id that tvp
uses for resources.
TILA-750

TILA-750 | Read origin id from hauki

---

api/graphql/reservation_units/reservation_unit_types.py
opening_hours/hours.py

There were found two "unwanted features" which caused opening hours and nextavailableSlot apis to not work properly.

Opening hours fetch fix

---

requirements.in
requirements.txt

dependabot warned about sqlparse and pillow. Elastic apm had new 5.x version.

Upgrade  sqlparse, pillow and elasticapm

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations.py
api/ical_api.py
api/tests/test_ical_api.py
api/urls.py

This PR adds calendar URL for created reservations.
For example, when creating a new reservation like this:
```graphql
mutation {
createReservation(input: {
state: "created"
user: 1
priority: "100"
begin: "2020-01-01T00:00:00Z"
end: "2020-01-01T00:00:00Z"
reservationUnit: 1
}) {
reservation {
id
priority
calendarUrl
}
errors {
field
messages
}
}
}
``` 
...the response will look like this:
```json
{
"data": {
"createReservation": {
"reservation": {
"id": "UmVzZXJ2YXRpb25UeXBlOjIw",
"priority": "A_100",
"calendarUrl": "http://0.0.0.0:8000/v1/reservation_calendar/20/?hash=fcc8548de047b5da4210453e089830f0889ec4cbe5ac83876f831e4185ac0df6"
},
"errors": []
}
}
}
```
For the HMAC signatures for reservations, I calculated the digest for `reservation-<PK>` instead of just `<PK>`, because signing …

TILA-733: Add calendar URL for created reservations

---

api/graphql/tests/snapshots/snap_test_reservations.py

PR #281 (for TILA-733) was supposed to include snapshot for the reservation snapshot tests.
This PR adds the missing snapshot.

Add missing snapshot for reservation unit test

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

This PR adds application rounds to the reservation unit GraphQL API.
I did this by adding a `applicationRounds` field to the reservation unit type. For example:
```graphql
{
reservationUnits {
edges {
node {
name
applicationRounds {
name
applicationPeriodBegin
applicationPeriodEnd
status
}
}
}
}
}
```
The above returns reservation units with application rounds related to each:
```json
{
"data": {
"reservationUnits": {
"edges": [
{
"node": {
"name": "Test reservation unit",
"applicationRounds": [
{
"name": "Test Round",
"applicationPeriodBegin": "2021-09-27T08:37:14.153445+00:00",
"applicationPeriodEnd": "2021-10-25T08:37:14.153464+00:00",
"status": "DRAFT"
}
]
}
}
]
}
}
}
```
To get only the *active* application rounds, the `active: true` filter can be used:
```graphql
{
reservationUnits …
```

TILA-758: Add active application rounds to GraphQL API

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

After discussing with frontend developers, we came up with a couple of some modifications for fetching the reservations:
* Ability to filter reservations by multiple states (e.g. `["CREATED", "CONFIRMED"]`)
* Use `date` instead of `datetime` for filtering between timestamps (we don't really have a need to filter more granularly)
After these, we can filter by either a single state:
```graphql
{
reservationUnitByPk(pk: 1) {
name
reservations(state: "CREATED") {
begin
end
state
}
}
}
```
...or by multiple states:
```graphql
{
reservationUnitByPk(pk: 1) {
name
reservations(state: ["CREATED", "CONFIRMED"]) {
begin
end
state
}
}
}
```
Also, dates without hours and minutes will be used to filter by dates:
```graphql
{
reservationUnitByPk(pk: 1) {
name
reservations(from: "2020-01-01", to: …
```

TILA-737: Modifications for reservations related to reservation units

---

api/graphql/reservation_units/reservation_unit_mutations.py
api/graphql/tests/test_purposes.py

Purpose mutations (create and update) are serializer mutations
those needs to be based on AuthSerializerMutation to get permission to
function properly.
Adds permission tests to Purpose mutations.

Add Purpose mutations to base AuthSerializerMutation

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_types.py
api/graphql/schema.py
api/graphql/spaces/space_types.py
api/graphql/tests/test_reservation_units.py
api/graphql/units/unit_types.py
permissions/api_permissions/graphene_field_decorators.py
permissions/api_permissions/graphene_permissions.py

Decorator that is intended to be used with resolver functions for fields
and in schema for "byPk" fields
TILA-777

TILA-777 | Add check_resolver permission check decorator and use it in resolvers

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

There was a situation that caused the reservation not to be created even it should've been when the reservation would occur after next spring. 
The reason was that the reservation creation validator uses `ReservationUnitReservationScheduler` class which were initially made for fetching next available opening times until next spring (Point when the recurring reservation applications start) and thus it loads opening hours only to that point of time.
This adds new optional date parameter to scheduler class which is used for fetching opening hours until specific date.

TILA-892 | Use custom opening hours end date in ReservationCreateSerializer 

---

api/graphql/opening_hours/opening_hours_types.py
api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations.py
opening_hours/decorators.py
opening_hours/hours.py
opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

Adds new class to represent opening hours with start and end times using datetimes for handier comparing and handling.
Reads timezone information from hauki for opening hours and uses that in the `OpeningHoursClient` class. 
Note that UI is now receiving opening hours as default timezone (currently UTC0)

TILA-893 | Make openinghours client timezone aware

---

api/graphql/primary_key_fields.py

IntegerPrimaryKeyField was not displayable in mutation payloads.
Graphene tries to cast the field as int and it will fail so the field
must be int castable and also must be shown as null.
This adds override functions and casting to IntegerPrimaryKeyField to be
displayable in gql mutation payloads.

Makes IntegerPrimaryKeyField displayable in mutation payload

---

opening_hours/hauki_request.py

Previous PR related to this was missing these places. 
TILA-949 TILA-948

TILA-949 | Use HAUKI_API_KEY in post and put requests

---

tilavarauspalvelu/tests/test_fixtures.py

Added a new test that runs the `loaddata` management command with `fixtures/cases.json` as input, to make sure the fixtures get loaded successfully.

TILA-955: Add test for loading fixtures

---

reservation_units/admin.py

The translations for `Purpose` fields  were not modifiable in Django admin.
For some reason only the `name` field was specified in `PurposeAdmin`. This change fixes it so that all purpose fields can be edited.

Make all purpose fields editable in admin

---

api/graphql/reservations/reservation_serializers.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/snapshots/snap_test_reservations.py
api/graphql/tests/test_reservations.py

In `ReservationType` state had been defined as string type even though it is enum. This changes it to be enum instead of string.
In mutations though we are sticking with strings since there's a unsolved bug in gql+drf serializers with using enums and thus this adds some helping text for state field in mutations.
TILA-895

TILA-895 | Use state enum in Reservation query 

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py
terms_of_use/tests/factories.py

The PK fields for the different terms was mistakenly defined as integers even though the terms of use PKs are strings.
This PR fixes the reservation unit GraphQL type so that those PKs are the correct type.
TILA-877

TILA-877: Fix primary key type for terms

---

api/graphql/tests/snapshots/snap_test_reservation_cancel_reason.py

The snapshot for `test_getting_reservation_cancel_reasons` was outdated (test has been renamed / removed), which was giving warnings when running tests.
I updated the snapshot to make the warning go away.

Fix outdated reservation cancellation reason snapshot

---

tilavarauspalvelu/settings.py

We use azure persistent storage for /media and it does not allow chmod any kind of permission changes for the folders and files. By default storage has this setting on and by setting this to None should skip the chmod  when uploading files.
TILA-975

TILA-975 | Set FILE_UPLOAD_PERMISSIONS to None

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/test_equipments.py
api/graphql/translate_fields.py
permissions/api_permissions/graphene_permissions.py

This PR makes a couple of minor changes to the codebase to improve compatibility with future versions of Graphene:
* Fix some tests to use integer PKs instead of string PKs (new Graphene versions seem to be more strict about the types)
* Import `ResolveInfo` from the correct location (from the `graphene` package instead of the private `graphql` package)

Graphene compatibility fixes

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

The `ModelInFilter` from our `common_filters.py` causes problems with Graphene-Django 2.15 and above, because it inherits from both `BaseInFilter` and `ModelChoiceFilter`. Another problem with it is that it requires multiple PKs to be given as a string, like `"1,2,3"` instead of a list like `[1,2,3]`.
I noticed that for GraphQL APIs, we can actually skip `ModelInFilter` altogether and just use `ModelMultipleChoiceFilter` directly, which allows filtering by a single or multiple PKs given as a list. So instead of this:
```graphql
reservationUnits(reservationUnitType: "1,2,3") {
...
}
```
...we can do this:
```graphql
reservationUnits(reservationUnitType: [1,2,3]) {
...
}
```
And filtering by a single PK still works the same:
```graphql
reservationUnits(reservationUnitType: 1) {
...
}
``` …

Use ModelMultipleChoiceFilter instead of ModelInFilter for consistency and Graphene-Django 2.15+ compatibility

---

requirements.in
requirements.txt
tilavarauspalvelu/settings.py

This PR upgrades Graphene-Django to version 3.0.0b7, which is the latest version. Along with it, Graphene will be upgraded to version 3.0.
3.0.0b7 is a pre-release, but there hasn't been a new release for almost a year, so I'm not sure if there are any other options because the stable releases don't support Graphene 3.0. We need Graphene 3.0 for `null` value support for input fields (see https://github.com/graphql-python/graphene/issues/1362).
The Graphene-Permissions library has a small problem where it imports `ResolveInfo` from the wrong package, causing an `ImportError` with newer versions of Graphene. There is no fix for this yet, so the only way to avoid is to monkey patch it in `settings.py`. I will make a separate PR in the graphene-permissions project to have it fixed in a future …

TILA-929: Upgrade Graphene-Django to the latest version

---

api/graphql/tests/test_equipments.py
api/graphql/tests/test_purposes.py
api/graphql/tests/test_reservation_cancel_reason.py
api/graphql/tests/test_reservation_unit_cancellation_rules.py
api/graphql/tests/test_reservation_unit_types.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations.py
api/graphql/tests/test_resources.py
api/graphql/tests/test_spaces.py
api/graphql/tests/test_units.py

In Graphene 3.x, the test client `_client` in `GraphQLTestCase` has been renamed to `client`.
This PR fixes the related deprecation warnings caused by the Graphene upgrade.

Fix deprecated test client in GraphQL tests

---

requirements.in
requirements.txt

I have contacted the maintainers of [django-tinymce](https://github.com/jazzband/django-tinymce) regarding https://github.com/advisories/GHSA-r8hm-w5f7-wj39
and they have recently published a new version of the library which includes a patched version of TinyMCE (a bundled JS library).
Not super critical because it looks like we only use django-tinymce in the admin interface, but at least we can get rid of the Dependabot alert.

Upgrade django-tinymce to fix a security vulnerability

---

api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

After adding additional instructions for reservation units to the model in #341, the fields were already usable in the GraphQL API. So the only thing remaining to do was to add tests.

TILA-1004: Add tests for additional instructions

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_serializers.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/snapshots/snap_test_reservations.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations.py

This PR adds price-related fields for reservation units and reservations to the GraphQL API.
* `lowestPrice` (`Decimal`†)
* This is the minimum price for the reservation unit, used when defining the price range in the management UI.
* Optional, default value is 0.
* `highestPrice` (`Decimal`†)
* This is the maximum price for the reservation unit, used when defining the price range in the management UI.
* Optional, default value is 0.
* `priceUnit` (`String`‡)
* The unit of the price. Possible values are `per_15_mins`, `per_30_mins`, `per_hour`, `per_half_day`, `per_day`, `per_week`, and `fixed`.
* Optional, default value is `per_hour`.
* `price` (`Decimal`†)
* The list price of the reservation unit. This is for cases where the price is fixed and this value will be copied to the …

TILA-818: Add price-related fields to the GraphQL API

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
reservation_units/models.py

Adds the new `reservationStartInterval` field for reservation units in the GraphQL API.

TILA-999: Add reservation start interval to the GraphQL API

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
opening_hours/hauki_link_generator.py
opening_hours/tests/test_hauki_link_generator.py
permissions/api_permissions/graphene_permissions.py

Three things related to hauki admin url generation here:
- Read the unit's tprek_department id as the organization id. 
- Refactors hauki link generator to be urlencoded.
- Adds permission checks for displaying the link through api.
TILA-959 TILA-989

TILA-959 | Use unit's department id in hauki url generation

---

api/graphql/reservation_units/reservation_unit_types.py

Add missing `reservation_start_interval` field to the `reservationUnitByPk` type.
TILA-999

TILA-999: Add missing reservationStartInterval to the reservationUnitByPk type

---

Dockerfile

This should hopefully resolve the build error:
2021-12-10T12:03:14.9444100Z STEP 10: RUN subscription-manager repos --disable rhel-8-for-x86_64-baseos-beta-rpms
2021-12-10T12:03:34.8932008Z Error: 'rhel-8-for-x86_64-baseos-beta-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

Remove beta repos from Dockerfile

---

api/graphql/reservation_units/reservation_unit_mutations.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_reservation_unit_types.py
api/graphql/tests/test_reservation_unit_image.py
api/graphql/tests/test_reservation_unit_types.py
api/urls.py
permissions/api_permissions/graphene_permissions.py
requirements.in
requirements.txt
reservation_units/tests/factories.py

Introduces graphene file upload library which enables sending multipart request spec to be used in graphene by replacing the default graphqlview with the fileupload view.
Adds mutations for creating reservation unit image objects (with files [images]) 
https://github.com/jaydenseric/graphql-multipart-request-spec
TILA-970

TILA-970 | Reservation unit image mutations

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

Adds validation for reservation start interval.
Validations for only 15, 30, and 60 would've been very simple (just check that minutes are 0, 15, or 30), but 90 minutes makes it a bit trickier:
* If the reservation unit opens at 8:00, then valid reservation start times are 8:00, 9:30, 11:00, 12:30, etc.
* If the reservation unit opens at 9:00, then valid reservation start times are 9:00, 10:30, 12:00, 13:30, etc.
So I had to utilize the opening time of the reservation unit for the validation.
TILA-1010

TILA-1010: Add validation for reservation start interval

---

requirements.in
requirements.txt

This bumps Django from 3.1.13 to 3.1.14, which fixes  CVE-2021-44420.

Upgrade to Django 3.1.14 for security fixes

---

fixtures/cases.json
opening_hours/hauki_link_generator.py
opening_hours/tests/test_hauki_link_generator.py

Also update fixtures to have a value in unit's tprek_department_id.

TILA-989 | Require organization id for hauki admin url generation

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py

Added validation for enum fields:
* `ReservationUnit.price_unit`
* `ReservationUnit.reservation_start_interval`
I was only able to find these two fields with missing validation. The others seemed to be read-only (`Reservation.state`) or had validation already (`Resource.location_type`).

TILA-1046: Validate reservation unit's price unit and interval fields

---

api/graphql/reservations/reservation_types.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_age_groups.py
api/graphql/tests/test_age_groups.py

Adds age groups to the GraphQL API, so they can be queried like this:
```graphql
{
ageGroups {
edges {
node {
minimum
maximum
}
}
}
}
```
This is needed so that the frontend can show age group options in dropdown menus.
TILA-1053

TILA-1053: Expose age groups in GraphQL API

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/resources/resource_serializers.py
api/graphql/tests/test_resources.py

By default graphene is camelcasing, but we're missing some custom validation messages to be camelcased
TILA-928

TILA-928 | Camelcase field names in errors

---

api/graphql/applications/application_types.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_cities.py
api/graphql/tests/test_cities.py
permissions/api_permissions/graphene_permissions.py

Adds cities to the GraphQL API, so they can be queried like this:
```graphql
{
cities {
edges {
node {
name
}
}
}
}
```
This is needed so that the frontend can show the city options in dropdown menus.
TILA-1053

TILA-1053: Expose cities in the GraphQL API

---

api/graphql/reservations/reservation_types.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_metadata_sets.py
api/graphql/tests/test_metadata_sets.py
permissions/api_permissions/graphene_permissions.py

Adds ability to query metadata sets in GraphQL:
```graphql
{
metadataSets {
edges {
node {
pk
name
supportedFields
requiredFields
}
}
}
}
```
Example response:
```json
{
"data": {
"metadataSets": {
"edges": [
{
"node": {
"name": "Test form",
"requiredFields": [
"reservee_first_name",
"reservee_last_name"
],
"supportedFields": [
"reservee_first_name",
"reservee_last_name",
"reservee_phone"
]
}
}
]
}
}
}
```
TILA-951

TILA-951: Expose metadata sets in GraphQL API

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
reservations/tests/factories.py

Allows setting the metadata set by PK in reservation unit's create and update mutations, e.g.:
```graphql
mutation {
updateReservationUnit(input: {
pk: 123
metadataSetPk: 567
} {
...
}
}
```
Also querying the metadata set is possible via the `metadataSet` field:
```graphql
{
reservationUnitByPk(pk: 123) {
metadataSet {
name
supportedFields
requiredFields
}
}
}
```
TILA-1050

TILA-1050: Add ability to set/query metadata set for a reservation unit in the GraphQL API

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py

When checking buffer times in reservation creation validation we must
use the highest buffer time when checking the reservation overlaps with
buffers included
TILA-1055

TILA-1055 | Use highest buffer time in reservation creation validation

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py

This adds validation for required metadata fields.
When mutating a reservation, we go through each required field in the attached reservation unit's metadata set. If any of the required field is missing/empty, a validation error is raised.
TILA-1057

TILA-1057: Add validation for required metadata fields

---

requirements.in
requirements.txt

Upgrade Celery to version 5.2.2

---

api/graphql/choice_char_field.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservation_units.py

This adds a new `ChoiceCharField` which can be used for enum fields with choices.
It takes the choices as an argument, and includes a validator which makes sure a given value is part of the choices. So no separate validations should be needed in mutation serializers, for example.
This means that:
* In queries, enum strings are returned in `UPPERCASE` (as before)
* In mutation inputs, enum strings can be given in `UPPERCASE` or `lowercase` (previously they had to be given in lowercase)
* In mutation payloads, enum strings are returned in `UPPERCASE` (previously they were returned in lowercase)
Maybe we will get true enums [some day](https://github.com/graphql-python/graphene-django/issues/1280).

TILA-1046: Allow uppercase enum values

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

Adds `maxReservationsPerUser` for reservation units in the GraphQL API.
This allows the `maxReservationsPerUser` to be queried and also mutated in the create and update mutations.

TILA-1008: Expose max reservations per user in the GraphQL API

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py

This lets you remove a previously assigned form from a reservation unit.
TILA-1050

TILA-1050: Allow `metadataSetPk` to be `null` in GraphQL API

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations.py
reservations/models.py

Adds validation for `max_reservations_per_user`.
The validation logic is the same as Respa's:
* We exclude canceled and denied reservations
* We exclude reservations whose end time is in the past
* The remaining reservations for the given user are counted and compared against the max reservations per user for the given reservation unit

TILA-1009: Validation for max reservations per user

---

api/graphql/reservation_units/reservation_unit_mutations.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/tests/test_reservation_unit_image.py

Adds update mutation for `ReservationUnitImage` - the mutation allows updating the reservation unit image's type.
Also add `pk` to `ReservationUnitImageType` to make deletion and update possible.
TILA-1058 TILA-1063

TILA-1063 | ReservationUnitImage update mutation

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_confirm.py
api/graphql/tests/test_reservations/test_reservation_update.py

This way we can enable taking in the enum value as uppercase. Also as uppercase it will be inline with other choice / enum based fields

Change reservation state to ChoiceField in serializer

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/test_reservation_confirm.py
api/graphql/tests/test_reservations/test_reservation_update.py

Fixes the `confirmReservation` mutation so that metadata fields are validated correctly based on possibly existing values in the reservation instance.
Added a test case to make sure confirming a reservation (without providing the required fields in the mutation input) will work in the future too.
TILA-1057

TILA-1057: Fix metadata field validation in confirm mutation

---

Dockerfile

Celery queue is not working because of file permissions:
```
PermissionError
[Errno 13] Permission denied: '/broker/queue/3259677_fc2859e1-ea07-4661-8c02-40d6382431d2.celery.msg'
```
The problem seems to be that the Celery worker process can't write files to `/broker/queue`.
Using OpenShift terminal, I checked that adding read/write permissions for the group *should* fix it. But it's a bit difficult to test locally. So I'm not 100% sure if this solution works.

Add read and write permissions to broker subdirectories

---

requirements.txt

Bumps the Pillow version which is a dependency of `easy-thumbnails`.
Fixes Dependabot alerts.

Upgrade Pillow

---

api/graphql/duration_field.py
api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_serializers.py
api/graphql/reservations/reservation_types.py
api/graphql/resources/resource_serializers.py
api/graphql/resources/resource_types.py
api/graphql/services/service_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/snapshots/snap_test_resources.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_queries.py

This PR changes the GraphQL types for mutations and queries so that duration fields will use a new `Duration` scalar type instead of `String` for mutations and `Float` for query responses in the GraphQL schema.
After these changes, durations like `bufferTimeBefore` and `minDuration` should be set as integers in mutations:
```graphql
mutation {
updateReservationUnit(input: {
pk: 1
bufferTimeBefore: 900
maxReservationDuration: 1800
}) {
bufferTimeBefore
maxReservationDuration
}
}
```
Response:
```json
{
"data": {
"updateReservationUnit": {
"bufferTimeBefore": 900,
"maxReservationDuration": 1800
}
}
}
```
Queries will also return integers:
```graphql
{
reservationUnits {
edges {
node {
bufferTimeBefore
maxReservationDuration
}
}
}
}
```
Response:
```json
{
"data": {
"reservationUnits": { …
```

TILA-1054: Use a `Duration` scalar for duration fields

---

Dockerfile

Based on [this workaround](https://stackoverflow.com/a/65138098) -- copies the entitlement and configuration files only if they exist.
Tested this locally without any of the files existing, and then some of them existing (I verified this by logging into the container and checking whether those files exist). It should also work in the pipeline as before.
TILA-1106

TILA-1106: Copy entitlements and configs only if they exist

---

opening_hours/resources.py
reservation_units/tests/test_hauki_exporter.py
reservation_units/utils/hauki_exporter.py

In update hauki resource the id was not set to Resource object to be updated.
This changes the Resource object to contain resource id if it is set to ReservationUnit.

Fix hauki resource update

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/schema.py
api/graphql/tests/test_reservations/snapshots/snap_base.py
api/graphql/tests/test_reservations/test_reservation_queries.py

We need to show reservations which have been in state REQUIRES_HANDLING
or are => so every "requested" or reservations needed to be handled are
shown with this.
TILA-1105

TILA-1105 | Add filter for getting reservation required handling

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py

Allows `null` to be passed for fields that may return `null` values in the API.
TILA-1065

Allow null for certain reservation unit fields

---

Dockerfile

An attempt to fix the `403 Unauthorized` errors with some RedHat repos.
Based on various RedHat discussions where refreshing the subscriptions has worked.

Refresh RedHat subscriptions in Dockerfile

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/reservations/reservation_serializers.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
api/graphql/tests/test_reservations/test_reservation_confirm.py

Adds functionality to add/change/read the `require_reservation_handling` boolean value through the api.
Change confirm serializer to check the boolean value instead of the metadata_set too determine is the reservation state to be REQUIRES_HANDLING (or not)
TILA-1148

TILA-1148 | require_reservation_handling usage in apis

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/test_reservation_create.py

When a new reservation is created, we want to copy the SKU from the reservation unit to the reservation instance.
The SKU will be used later related to payments.
TILA-1137

TILA-1137: Copy SKU from reservation unit to reservation

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_update.py

Fixes an issue where the maximum reservations per user validation would fail when updating a reservation.

Fix reservation reservation max count validation for updates

---

api/graphql/reservations/reservation_types.py

There is no such field + the purposes pk can be fetch through the purpose in query. Like `{reservations{ edges { node { purpose { pk } } } } }`

Remove purpose pk from ReservationType fields

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

Exposes the `authentication` field in the GraphQL API for reservation units.
TILA-1139

TILA-1139: Expose `authentication` field for reservation units in the GraphQL API

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/test_reservation_units.py

The `authentication` field was missing from `ReservationUnitByPkType`, even though it was in `ReservationUnitType`.
TILA-1139

TILA-1139: Add `authentication` to reservation unit by PK type

---

spaces/admin.py
spaces/importers/units.py
spaces/management/commands/import_units.py
tilavarauspalvelu/settings.py

Add unit importer to django admin to UnitAdmin actions => so user can update unit information from tprek (to those where tprek_id is known)
TILA-1257

TILA-1257 | Unit importer to django admin

---

api/tests/test_application_status_api.py
permissions/api_permissions/drf_permissions.py

There were an error raised when application event status end point got request with empty data dict => check against empty
application_event_id and return forbidden when empty
TILA-1272

TILA-1272 | Check for empty app_event_id in event status perm check

---

api/graphql/tests/test_reservations/test_reservation_queries.py

The test was failing randomly due to the begin date being created to a random point of time.
Fix random fail by adding static begin times to reservations in the test

Set reservation begin dates to test_filter_reservation_state_accepts_multiple_values

---

README.md
deploy/uwsgi.yml
tilavarauspalvelu/settings.py

Application started dropping connections when the application was under load. These changes scale-up amount of workers when load increases. Static files are also served in an unconventional way. Documentation is updated to ease understanding of potential failures in the future.
* Improve application performance on-load.
* Improve documentation
Refs TILA-1394

TILA-1394 | static files serving

---

api/applications_api/views.py
api/tests/conftest.py
api/tests/test_application_api.py
applications/models.py
permissions/helpers.py

Shows applications to unit admins for those who have permissions
"can_validate_applications" even though application would have events to
other units => right to see application is when there is at least one event
to the unit admin's unit. (ReservationUnit that belongs to the unit)
TILA-1407

TILA-1407 | Show applications to unit admins

---

api/applications_api/views.py

To avoid multiple objects returned

Use distinct in ApplicationViewset queryset

---

applications/tests/factories.py

Tests can randomly fail when end date is same as start date. This commit fixes the issue to always have end date at least 1 day after start date.

Bugfix | Adjust end-dates to never be same as start date

---

api/applications_api/views.py
api/tests/conftest.py
api/tests/test_application_api.py

Shows applications to unit group  admins for those who have permissions
"can_validate_applications" even though application would have events to
other units => right to see application is when there is at least one event
to the unit group admin's unit. (ReservationUnit that belongs to the
unit that belongs to the group)
TILA-1407

TILA-1407 | Show applications to unit group admins

---

deploy/uwsgi.yml

It seems block size is not large enough with the default. This commit double the header block size.
This can be because some requests having longer urls than others and only narrowly passing the threshold. We do not want to increase this too much [as it could be a security risk](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#buffer-size), but only slightly to suit our current needs.
Refs TILA-1471

TILA-1471 | Increase header block size

---

README.md
api/graphql/application_rounds/application_round_types.py
api/graphql/applications/application_filtersets.py
api/graphql/applications/application_types.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/tests/test_applications/base.py
api/graphql/tests/test_applications/snapshots/snap_base.py
api/graphql/tests/test_applications/test_application_permissions.py
api/graphql/tests/test_applications/test_applications.py
api/graphql/tests/test_applications/test_applications_filters.py
applications/tests/factories.py
deploy/entrypoint.sh
permissions/api_permissions/graphene_permissions.py
pytest.ini
requirements.in
requirements.txt
reservations/tests/factories.py
setup.cfg
spaces/tests/factories.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/urls.py

Applications endpoint was translated to GraphQL in this branch for better specification in data fetches. This will improve performance when less information is queried and gathered in each request when only the necessary data has to be fetched instead of all possible values.
* Translate `/v1/applications/` endpoint from REST to GraphQL.
* Move performance investigation tooling to documentation instead of ready-made settings.
* Improve code coverage pytest settings.
Refs TILA-1569

TILA-1569 | Applications fetch in graphql

---

api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_filtersets.py

Adds `UnitsFiltersSet` and enables sorting `Unit` by name. I also added some tests to cover basic query cases.

TILA-1691: Allow sorting units by name

---

api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_types.py

Adds `service_sectors` field to `UnitType`.

TILA-1695: Add service sectors to UnitType

---

api/graphql/application_rounds/application_round_types.py
api/graphql/schema.py
api/graphql/spaces/space_types.py
api/graphql/tests/snapshots/snap_test_service_sectors.py
api/graphql/tests/test_service_sectors.py
permissions/api_permissions/graphene_permissions.py

This PR adds ServiceService to GraphQL. I also moved `ServiceSectorType` from `application_round_types.py` to `space_types.py`.
Example query:
```
{
serviceSectors {
edges {
node {
pk
nameFi
nameSv
nameEn
}
}
}
}
```

TILA-1720: Add ServiceSector to GraphQL

---

utils/query_performance.py

In QueryPerformanceOptimzerMixin class there was miney mini bug when select_for_parent type of optimizations.
Piece of code was calling push instead of append. This fixes that one.
TILA-1721

TILA-1721 | Use append instead of push then adding parent selects

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

The only way to interact with archived reservation units is the Django Admin, I also removed `is_archived` filter since there is no use for it.

TILA-1741: Hide archived reservation units by default

---

api/graphql/applications/application_event_serializers.py
api/graphql/applications/application_mutations.py
api/graphql/applications/application_types.py
api/graphql/schema.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query.py
api/graphql/tests/test_application_events/snapshots/snap_test_application_events_query_permissions.py
api/graphql/tests/test_application_events/test_application_event_schedule_result_create.py
api/graphql/tests/test_application_events/test_application_event_schedule_result_update.py
api/graphql/tests/test_application_events/test_application_events_query.py
api/graphql/tests/test_application_events/test_application_events_query_permissions.py
applications/models.py
permissions/api_permissions/graphene_permissions.py

Adds `ApplicationEventScheduleResult` to GraphQl. 
This can be queried through `ApplicationEventSchedule` in `ApplicationEventType`
Adds mutations to create and edit `ApplicationEventScheduleResult`s 
TILA-1758

TILA-1758 | ApplicationEventScheduleResult GraphQl API

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py
reservation_units/enums.py
reservation_units/models.py
reservation_units/utils/reservation_unit_state_helper.py
reservation_units/utils/tests/test_reservation_unit_state_helper.py

`state` is a calculated field.  Because the value depends on the current time, we can't really store it to the database. For these reasons I made a separate utility class that handles the state calculation and filter generation. I couldn't figure out an easier way to do this, but if you know how to improve this, please let me know ☺️ 
Oh I also switched strings to enums ☺️

TILA-1730: Filtering reservation units by state

---

api/graphql/applications/application_types.py

In application graphql types there was some *_id fields declared which
we don't need in graphql since we can just add the corresponding
relative type.
This removes the id fields and introduces relatative types if needed and
changes one id to _pk which is what we prefer.
TILA-1736

TILA-1736 | Remove obsolete id references and change necessary to pk

---

api/graphql/resources/resource_serializers.py
api/graphql/tests/test_resources.py

- Finnish name translation is required
- English and Swedish can be `null`
Tests are also updated to match the change.

TILA-1749: Fix resource update validation

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_confirm.py

When reservation has applying_for_free_of_charge on, reservation is moved to REQUIRES_HANDLING state on confirm mutate call.
Refs TILA-1767

Set reservation to REQUIRES_HANDLING on subsidy

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/tests/test_reservation_units.py

Originally, I thought that the pricing fields are managed via Django Admin, but that assumption turned out to be wrong. So, now they are part of the mutations.
Refs TILA-1773

TILA-1773: Add pricing fields to Reservation Unit mutation.

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/test_reservation_create.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

... with a limitation of two years. 
Previously reservations could be made only to next spring because of the seasonal reservation applications etc. but since from that spec we have been introduced few fields in the ReservationUnit which we can use to determine these times.
Also fixes one buggy in the scheduler where scrolling time over daylight saving using timedelta and the timezone
diff did not get noticed and thus it resulted those cases the winter diff (+02.00 instead of +03:00
TILA-1639

TILA-1639 | Reservations can be made to as long as reservation unit allows

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_create.py
api/graphql/tests/test_reservations/test_reservation_update.py
reservation_units/tests/factories.py

The logic of the calculation is described in [TILA-1765](https://helsinkisolutionoffice.atlassian.net/browse/TILA-1765). When reservation is updated, price is calculated only if begin or end time is updated or when reservation units are changed.

TILA-1765: Calculate reservation price on create/update

---

api/graphql/application_errors.py

There is now a new `ValidationErrorWithCode` exception class that can be used as validation errors in cases where we want to have a machine-readable code addition to human-readable error message. The class is not yet used anywhere so this is just a preparation PR for the actual use-case.
I tried to find a way to extend existing `ValidationError` and failed miserably. However, I learned that the GraphQL "standard" is to use provided `GraphQLError` and add any additional data under `extensions` field. So this ended up being my approach.
This WILL change the error response so it might require some frontend changes but that is fine. I got a seal of approval from the frontend devs 🦭
Here is an example how the response changes.
Current:
```graphql
{
"data": {
"createReservation": {
"errors": [ …
```

TILA-1814: Add validation error with code class

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

Add a new filter to Reservations GQL query: reservationUnit. Filter supports arrays so multiple Reservation Unit PKs can be used as a filter.

TILA-1829: Add reservationUnit filter

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/test_reservation_create.py

Reservations_min_days_before is not checked against current time
but the beginning of the current day. Previously, at 12:00 you could
only book a unit for the next day at 12:00, but now it is possible to
book it for 00:00 next day.
Similar logic is already done in the frontend.

TILA-1843: Update reservation time validation

---

api/graphql/schema.py
api/graphql/tests/snapshots/snap_test_users.py
api/graphql/tests/test_users.py

Previously it returned an array which was a bit confusing. I think this makes more sense since it will always return max 1 user.

TILA-1820: Change currentUser query to return a single object

---

reservation_units/admin.py
reservation_units/models.py

In reservation unit django admin autocomplete it had the autocomplete
field with pk__exact which caused all string searches to cause an error.
This can be solved by using iexact so it intreprets as string as well.
**EDIT**
added the unit's name to reservation unit's __str__ method to get it to django admin views.

Change exact search to iexact for searching from pk

---

api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_filtersets.py

With this filter api results only the units which the has some permission through service sector roles or unit roles.
Refs TILA-1882

TILA-1882 | Add filter for units to filter only with_permission

---

api/graphql/tests/test_reservations/base.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py
permissions/helpers.py

In permission helper function get_units_where_can_view_reservations gets units where user has permissions to view. It didin't take into account unit_groups.
This changes the function to get units from unit groups as well.
Refs TILA-1881

TILA-1881 | Take into account unit_groups when getting viewable reservations

---

api/graphql/reservation_units/reservation_unit_serializers.py
api/graphql/reservation_units/reservation_unit_types.py

For some reason the `help_text` argument in the custom `ValidatingListField` does not work. I tried to check it with a debugger. The value is clearly set, but it does not show in the GraphiQL.
As a quick fix, I moved the documentation under `PaymentTypeType`. There it works with `description` parameter.

TILA-1859: Document payment type codes

---

api/graphql/tests/snapshots/snap_test_units.py
api/graphql/tests/test_units.py
api/graphql/units/unit_filtersets.py

Adds filters for querying units with published reservation units and units with own reservation (and the possibility to order them by the count)
TILA-1837

TILA-1837 | Add new filters to Units query

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/snapshots/snap_test_reservation_units.py
api/graphql/tests/test_reservation_units.py

In ReservationType there is field based field checks that checks should the field be visible or nulled so the reservation check can and should be removed since reservations are to be viewable without logged in
Refs TILA-1927

TILA-1927 | Remove ReservationPermission check from ReservationUnit type's reservations

---

email_notification/sender/email_notification_builder.py
email_notification/tests/test_notification_builders.py

Previously the email notification builder was getting times and dates as is withouth taking into consideration the timezone. This changes that so it takes the timezone into account.
Refs TILA-1894

TILA-1894 | Make email notification builder to respect timezones

---

email_notification/sender/email_notification_builder.py
email_notification/tests/test_notification_builders.py

The reservation unit's name was rendered as part of the instructions (cancel, confirm and pending).
This removes the name of the reservation unit (but adds "-" between res units).
Refs TILA-1895

TILA-1895 | Remove reservation unit name from instructions in emails

---

reservation_units/pricing_updates.py
reservation_units/tasks.py
reservation_units/tests/test_pricing_updates.py

Adds a task which we can run once a day to update reservation unit pricings. Currently based on #607 so I'll update the PR after #607 is merged.

TILA-1864: Task for scheduled pricing update

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_create.py
api/graphql/tests/test_reservations/test_reservation_update.py
reservation_units/utils/reservation_unit_pricing_helper.py

Since reservation units can have two different pricings (active and future), we have to update reservation price calculation so that we'll use future pricing if it exists and reservation date matches to it.

TILA-1865: Update pricing calculation to use future pricing

---

requirements.in
requirements.txt

Older ortools has a protobuf dependency which has a [known vulnerability](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/security/dependabot/9).

TILA-1518: Bump ortools to latest version

---

api/graphql/tests/test_reservation_units.py
spaces/models.py
spaces/tests/test_unit_merchant_update.py

When unit's merchant is changed, we need to update all related reservation units with no own merchants defined. This leads to product mapping update.
This PR is based on #632 so check only the last three commits ☺️

TILA-1911: Update reservation unit product on unit update

---

email_notification/sender/email_notification_builder.py
email_notification/tests/test_notification_builders.py
email_notification/tests/test_senders.py

This is the way.
Refs TILA-1944

TILA-1944 | Remove leading zeros from reservation number in emails

---

requirements.in
requirements.txt

- Remove pins from pytest libaries and bump them to latest
- Bump pip-tools
- Bump py to solve security issue related to it.

Bump pytest, py, pip-compile

---

api/graphql/tests/test_reservations/test_reservation_queries.py
requirements.in
requirements.txt

- Added pytest to `requirements.in`
- Updated `requirements.txt` with `pip-compile && pip-sync`
- Set `maxDiff` to `None` in the flaky test :rage1:  
We have a [dependobot alert](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/security/dependabot/11) from `py` library. Looks like your previous testing library bump didn't update `pytest` to the latest version so I added it to `requirements.in` file. I ran the tests on my machine and everything seems to work fine 👍

TILA-1518: Update vulnerable py package by updating pytest

---

opening_hours/enums.py
opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

- Adds new resource states to State enum in openinhours.enum; maintenance, not_in_use
- Add util method to State enum to return states that are to be considered when the reservations are possible
- Make the opening hours client know the usage of `end_time_on_next_day` value
- Make the opening hours client interpret resource to be reservable whole day when start_time and end_time are both nulls.

TILA-1950 | Opening hours client enhancements

---

api/graphql/permissions/permission_types.py
api/graphql/tests/snapshots/snap_test_users.py
api/graphql/tests/test_users.py

- Adds permissions to role types in gql api
- Means that in apis using userType the user can query permissions
Refs TILA-1986

TILA-1986 | Add permissions to roles in userType

---

opening_hours/hours.py
opening_hours/tests/fixtures/hauki_opening_hours_response.json
opening_hours/tests/fixtures/hauki_opening_hours_response_resource_closed.json
opening_hours/tests/test_get_opening_hours.py
opening_hours/tests/test_opening_hours_client.py

Previously it failed to do so since the fromisoformat fails. Fixes that to checking the data before parsing.
Refs TILA-2005

TILA-2005 | Make get_opening_hours to read null start and end times

---

api/graphql/tests/test_reservation_units.py
reservation_units/utils/reservation_unit_pricing_helper.py

This was originally introduced using built-in round which does not comply the rounding specs.
Refs TILA-1975

TILA-1975 | Round resrevation prices using Decimal class quantize

---

api/graphql/tests/test_spaces.py
permissions/api_permissions/graphene_permissions.py

Previously we checked only for unit_pk the unit level permissions when doing unit mutations. This faults in most cases to general permission check and thus the update/create wouldn't work for unit admins not service sector admins.
This changes the permission check logic so that it can handle update/delete/creation for unit admins => checks the permissions from the space itself (space.unit)
Refs TILA-1963

TILA-1963 | Alter permission check for space mutations

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_update.py

Make reservee_id not mandatory or individual reservee even if defined in metadata to be mandatory.
Refs TILA-2036

TILA-2036 | Make reservee_id not mandatory or individual reservee

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_approve.py

- Added `price_net` field to `ReservationApproveSerializer`
- Changed `handling_details` to be required.
In the code we copy `handling_details` to `working_memo`. If `handling_details` is missing, the code will throw a key error exception. Since client is already always sending the field, I just marked it as required.
- No changes needed

TILA-2057: Add price_net and make handling_details required

---

api/graphql/reservations/reservation_serializers.py
api/graphql/tests/test_reservations/test_reservation_confirm.py

- Added price check. Order creation is skipped if price is zero
- No changes needed

TILA-2016: Skip order creation when reservation amount is zero

---

api/graphql/reservations/reservation_serializers.py
api/tests/test_webhook_api.py
api/urls.py
api/webhook_api/views.py
merchants/verkkokauppa/payment/requests.py
permissions/api_permissions/drf_permissions.py
requirements.in
requirements.txt
reservations/email_utils.py

- Updated `drf-spectacular` package
- Updated `Payment API` client to be up-to-date with the latest implementation
- Extracted reservation email sending to own file
- Added a new payment webhook endpoint to REST API
- Moar tests
There are some known changes coming to Payment Experience API but since those are not yet deployed, I added a TODO comment as a reminder. I'll update the code as soon as I get an update from the Verkkokauppa team. 

TILA-1971: Payment webhook endpoint to REST API

---

api/tests/test_webhook_api.py
api/urls.py
api/webhook_api/views.py

- Add order cancellation webhook endpoint
- Tests

TILA-1972: Add order cancellation webhook endpoint to REST API

---

api/graphql/tests/test_reservations/test_reservation_adjust_time.py
applications/__init__.py
users/__init__.py
users/models.py

- Remove deprecated ``default_app_config``
- User ``gettext_lazy`` instead of deprecated ``ugettext_lazy``
- Use timezone aware datetime in adjust time test

Fix deprecations

---

reservations/models.py

- REQUIRES_HANDLING to `ReservationQueryset.going_to_occur` 
In reservations queryset we have util queryset function to get reservations that are going to occur e.g not cancelled or denied. The method is used in various places and it was lacking the REQUIRES_HANDLING state which also means that the reservation is going to occur.
This adds REQUIRES_HANDLING state to going_to_occur method.
Refs TILA-2038

TILA-2038 | Include REQUIRES_HANDLING to going_to_occur qs method

---

api/graphql/reservations/reservation_filtersets.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Add `createdAt` to `orderBy` in `reservations` query

TILA-2112: Add createAt to reservation orderBy

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Add `handled_at` field to `ReservationType`

TILA-2124: Add handled_at field to ReservationType

---

api/graphql/reservations/reservation_mutations.py
api/graphql/tests/test_reservations/test_reservation_delete.py
merchants/verkkokauppa/order/exceptions.py
merchants/verkkokauppa/order/requests.py
merchants/verkkokauppa/tests/test_order_requests.py

- Added support for webshop order cancellation
- Cancel webshop order when reservation is deleted
- If cancellation is successful, also cancel our PaymentOrder
I just realized order status are still plain strings. I'll do a separate refactoring PR when I will change them to enums 🛠️ 

TILA-2033: Add webshop order cancellation support

---

api/graphql/merchants/merchant_mutations.py
api/graphql/reservations/reservation_filtersets.py
api/graphql/reservations/reservation_mutations.py
api/graphql/reservations/reservation_serializers/confirm_serializers.py
api/graphql/tests/test_orders.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_confirm.py
api/graphql/tests/test_reservations/test_reservation_delete.py
api/graphql/tests/test_reservations/test_reservation_queries.py
api/tests/test_webhook_api.py
api/webhook_api/views.py
merchants/models.py
merchants/tests/factories.py

- Add `order_status` to Reservation `order_by` fields
- Refactoring: renamed `payment_status` filter to `order_status` (see notes)
`ReservationType` has a field called `order_status` but the related filter was called `payment_status` which led a bit confusing queries. I renamed the filter so that now everything - field, filter and order_by - is using the same naming convention.
Filter is already used on the admin client, so this requires some syncing with the frontend code. @wuahi will work on this on the frontend side.

TILA-2029: Reservation - add sorting by order status and rename order status filter

---

.github/workflows/build.yml
requirements.in
requirements.txt

- Removed python-dev installation from build.yml
- Upgraded easy-thumbnails to get rid of [vulnerability](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/security/dependabot/12)
Python-dev is not needed anymore. Also, it is not available causing build to fail.

TILA-1518: Remove python-dev and upgrade easy-thumbnails

---

api/graphql/reservations/reservation_serializers/staff_create_serializers.py

- Uses time, not datetime, when checking start intervals for staff reservation
In staff reservation the opening hours does not matter so we can just check the times instead of datetimes.
There was also a bug that the used only current day to check the intervals and thus would fail when trying to reserve to future dates. This also is fixed when used only times.
Refs TILA-2074

TILA-2074 | Check interval for staff reservations from times only

---

api/graphql/reservations/reservation_serializers/confirm_serializers.py
api/graphql/tests/test_reservations/test_reservation_confirm.py

- Fix payment product requirement
- Removed payment_type check when price is zero
- Added tests
Payment product and payment_type check are not required when price of the reservation is zero.

TILA-2163: Fix payment product requirement

---

reservations/migrations/0040_recurring_reservation_fields_changes.py

Previously the recurring migration file, which introduced new fields including reservation_unit to recurring reservation model, blew up because it tried to set reservation_unit_queryset to be fk field. This fixes that by using the first reservation unit from the queryset
Refs TILA-2100

TILA-2100 | Set first res unit to recurring reservation from reservation

---

reservation_units/models.py
reservation_units/tests/factories.py
reservation_units/tests/test_reservation_unit_export.py
reservation_units/utils/export_data.py

- Adds bunch of new fields to `ReservationUnit` exporter
These fields were already on previous tag (0.17.1) but not in main since that version of the tag there weren't yet pricing fields.

TILA-1978 | Add new fields to reservation unit exporter

---

merchants/tests/test_models.py
merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/requests.py
merchants/verkkokauppa/order/types.py

- Use `from` with exceptions to get the previous exception
- Add `capture_exception` calls to get better error reporting in Sentry
- Fix flaky test
Sentry does not show exception stacks when `capture_message` is used. Hopefully `capture_exception` changes that. I also used `from` with exception to capture the parent exception.
This PR is mostly to help me figure out the parsing issue but also to test how Sentry SDK behaves with `capture_exception`. The actual fix to the bug comes later when I figure out what is causing it.

TILA-2219: Add more logging and better exception handling

---

email_notification/sender/email_notification_builder.py
email_notification/tests/base.py
email_notification/tests/test_notification_builders.py
tilavarauspalvelu/settings.py

- Adds `current_year` as email template variables
- Adds `varaamo_ext_link`, `my_reservations_ext_link` and `feedback_ext_link` to email template variables
- Those are to be configured via env variables `EMAIL_VARAAMO_EXT_LINK` and `EMAIL_FEEDBACK_EXT_LINK`
Note to contributor; Remember the steps below 👇

TILA-2134 | Emailt template context variables; current year and links

---

deploy/uwsgi.yml

- Enabled uWSGI statistics endpoint
This is required for monitoring. Stats will be read by [uwsgi-exporter](https://pypi.org/project/uwsgi-exporter/) that will expose the stats in Prometheus format. Then, [Prometheus](https://prometheus.io/) will read the stats from uwsgi-exporter.

TILA-1495: Enable uWSGI stats endpoint

---

requirements.in
requirements.txt
tilavarauspalvelu/settings.py
tilavarauspalvelu/urls.py

- Add [django-prometheus](https://github.com/korfuri/django-prometheus) dependency
- Enable `/metrics` endpoint
`/metrics` endpoint exposes Django internals (and custom metrics in the future) in Prometheus format. This does not yet include database stats. I will investigate how `postgis` engine works with `django_prometheus` a bit later.
Metrics endpoint is open just like any other endpoint. If there is need to secure it somehow, I will investigate that, too, a bit later.

TILA-1495: Enable prometheus statistics

---

api/graphql/reservations/reservation_serializers/adjust_time_serializers.py
api/graphql/reservations/reservation_serializers/create_serializers.py
api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_reservation_create.py

- Reservation validation `check_reservation_time` fix and enchancement
The check reservation_time checker compared reservation begin time to reservation_begins and *_ends rather it should compare against current_time in the making of the reservation.
Also adds checking current time against publish_ends and begins samely as reservation_begins
Refs TILA-2255
[TILA-2255]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TILA-2255 | Check reservation time to current time not reservation begin

---

requirements.in
requirements.txt
requirements_dev.in
requirements_dev.txt
tilavarauspalvelu/settings.py

- Use database engine from env if it is defined
Monitoring database requires that we use engine code from django_prometheus package instead of Django's default engine. This way we can configure the db engine via envs without breaking local dev environments.
This is documented in django-prometheus [README](https://github.com/korfuri/django-prometheus#monitoring-your-databases).
Refs TILA-1495

TILA-1495: Add possibility to override database engine

---

tilavarauspalvelu/settings.py

Refs TILA-2181
- Remove cropping the large images
- Only shrink large image height preserving the ratio.
[TILA-2181]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TILA-2181 | Don't crop large images; limit only height

---

merchants/verkkokauppa/constants.py
merchants/verkkokauppa/merchants/requests.py
merchants/verkkokauppa/order/requests.py
merchants/verkkokauppa/payment/requests.py
merchants/verkkokauppa/product/requests.py
utils/metrics.py

- Add helper classes for custom metrics
- Use new helpers with verkkokauppa requests
The new file wraps `prometheus_client` details so that we don't have to worry about them when we want to collect metrics. The initial setup is for Verkkokauppa and it collects number of calls, latencies and responses. These can be filtered by service, method, path and status code.
This PR might be a bit annoying to review without knowledge of how Prometheus metrics work, but feel free to ask me in Slack if things are unclear ☺️ 

TILA-1495: Add custom metrics for verkkokauppa

---

merchants/verkkokauppa/merchants/requests.py
merchants/verkkokauppa/product/requests.py

- Remove prefix forward slash from the path
Having the prefix slash in the second part overrides the defined path in the base part. This should fix the issue with Verkkokauppa API calls. Learned the hard way how `urljoin` works 😅 

TILA-2278: Remove prefix forward slash from the path

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/tests/test_reservation_units/snapshots/snap_test_reservation_units_query.py
spaces/models.py

Refs TILA-2283
- When generating hauki link within gql response use prefix "tprek:" in organisation id.
Hauki uses the department id with the prefix of the origin_id. In this department id case it needs to in form "tprek:<id>" to make the link work properly.
This adds computed property called "hauki_department_id" to Unit model which returns the tprek_department id with prefix "tprek:".

TILA-2283 | Add hauki_department_id property to unit

---

api/graphql/reservations/reservation_serializers/create_serializers.py
api/graphql/tests/test_reservations/test_reservation_create.py

- Fix `check_max_reservations_per_user`
When max_reservations_per_user is checked, we should consider only reservations from the same reservation units. Currently, people are unable to make new reservations because globally they have multiple reservations.

TILA-2185: Count reservations only from same resunit

---

reservations/pruning.py
reservations/tasks.py
reservations/tests/test_pruning.py

- Adds a task called `prune_recurring_reservations` which removes recurring reservations which does not have any reservations
Refs TILA-2102

TILA-2102 | Add task for deleting recurring reservation without reservations

---

api/graphql/reservations/reservation_serializers/staff_create_serializers.py
api/graphql/tests/test_reservations/test_reservation_create_staff.py

- Add recurringReservationPk to `ReservationStaffCreateMutation` 
In staff create reservation there should be possibility to give the recurring reservation within the creation of the reservation.
Refs TILA-2298

TILA-2298 | Add ability to give recurring reservation in staff create

---

email_notification/admin.py
email_notification/email_tester.py
email_notification/sender/email_notification_builder.py
email_notification/sender/email_notification_context.py
email_notification/sender/senders.py
email_notification/sender/tests/test_email_notification_builder.py
email_notification/sender/tests/test_email_notification_context.py
email_notification/templates/email_tester.html
email_notification/tests/test_notification_builders.py
requirements.in
requirements.txt
tilavarauspalvelu/settings.py

- Added [django-admin-extra-button](https://github.com/saxix/django-admin-extra-buttons) package
- Remove pinned version from `django-modeltranslation`
- Added `EmailNotificationContext` that contains all supported email template fields
- Updated `ReservationEmailNotificationBuilder` to support context
- Added new button to `EmailTemplate` list view that open testing form
- Created a custom testing form that sends emails in all three languages
- Updated tests to match the changes
I was surprised how tricky it is to add custom functionality to Django Admin without marrying the code to a specific Django version. Some people did the same by overriding Django's templates, but that felt even more complex and requires understanding of Django's internal implementation. Django's templates seem to …

TILA-2165: Email template test form for Django Admin

---

email_notification/admin.py

- Use the template user selected instead of hard-coded one
Yeah, I keep messing this up by forgetting to remove my test code 🤦 

TILA-2165: Use selected template when sending test email

---

email_notification/admin.py
email_notification/sender/email_notification_context.py
email_notification/sender/tests/test_email_notification_context.py

- Added a helper function to create context with mock content
- Use context in email template validation
It looks like email template validation failed because Jinja tried to render the template with an empty context. Now it is using the context I created in the previous ticket and that seems to fix the issue.

TILA-2211: Use fake context in validation

---

email_notification/sender/email_notification_builder.py
email_notification/sender/senders.py
email_notification/sender/tests/test_email_notification_builder.py

- Provide text and html contents via separate getters
- Use HTML content as attached alternative
- Update tests
Previously HTML content was rendered as text. Now it is rendered as HTML and email application can decide which version to show.

TILA-2322: Attach HTML content as alternative

---

email_notification/admin.py
email_notification/email_tester.py
email_notification/sender/senders.py
email_notification/templates/email_tester.html
email_notification/tests/test_admin.py
email_notification/tests/test_email_tester.py
email_notification/tests/test_senders.py

- Add a new sub-form for selecting a reservation unit
- Fill the form with reservation unit data if it is selected
This is not the prettiest or most user-friendly implementation, but it does the job. This was requested yesterday in the meeting.

TILA-2325: Add reservation unit selection to the email testing form

---

api/graphql/reservation_units/reservation_unit_types.py
api/graphql/schema.py
api/graphql/tests/test_reservation_units/snapshots/snap_test_reservation_unit_hauki_url.py
api/graphql/tests/test_reservation_units/test_reservation_unit_hauki_url.py
opening_hours/hauki_link_generator.py

- Changes the hauki url generation to create mass-edit url (with target_resources) if needed
- adds GQL api query for getting hauki url wth option to give other reservation units to edit aside with the "main" one.

TILA-2166 | Hauki admin url api for mass edits

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/test/test_create_order_params.py
merchants/verkkokauppa/order/test/test_order_from_json.py
merchants/verkkokauppa/order/types.py

- Order from_json method had an expectation that subscriptionId would be always present. This isn't the case and this adds handling for non existent subscription ids. Same goes for the phone.
- Send tax percentage value without comma to verkkokauppa
Refs TILA-2376

TILA-2376 | Make subscriptionId and phone not mandaroy for reading order

---

azure-pipelines-devtest.yml

- Disabled CI trigger batching
This will allow CI pipelines to be triggered even when previous runs are still waiting for approval.

TILA-1518: Disable CI trigger batching

---

api/graphql/reservation_units/reservation_unit_filtersets.py
api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_reservation_create.py
reservation_units/tests/test_reservation_unit_reservation_scheduler.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

- Adjust ReservationUnit published gql filter so that it checks between publish ends and begins
- Scheduler logic change for determining reservation period end date
- If the ReservatioUnit's reservation_ends is after the reservation start period it uses the the reservation_end date
- Raise validation error in reservation creation if reservation unit is draft or archived.
Refs TILA-2299

TILA-2299 | ReservationUnit published filter and reservation validation adjustments

---

reservations/migrations/0045_reservee_stats_field_updates.py
reservations/tests/test_recurring_reservation.py

To Recurring reservation was added UUID field which was unique. We must always handle unique field adds afterwards with custom migration code and this wasn't exception. This adds the custom setting up the uuid field for RecurringReservation.
Refs TILA-2345

TILA-2345 | Fix uuid migration

---

merchants/verkkokauppa/payment/exceptions.py
merchants/verkkokauppa/payment/requests.py
merchants/verkkokauppa/payment/test/test_refund_from_json.py
merchants/verkkokauppa/payment/types.py
merchants/verkkokauppa/tests/test_payment_requests.py
requirements.in
requirements.txt

- Added client for the new webshop instant refund endpoint
- Updated Django version because of [CVE](https://pyup.io/v/52945/f17/)
The response from webshop contains a lot more fields and data than what we need. I chose to just ignore those fields instead of writing unnecessary complex parsers.

TILA-2380: Add client for webshop refunds

---

.env.example
api/tests/test_webhook_api.py
api/urls.py
api/webhook_api/views.py

- Added missing configs to `.env.example`
- Added a new endpoint that handles refund webhooks from Verkkokauppa
Our model is still missing a field that is required a bit later. I left a TODO comment for this. There is already task for it.

TILA-2379: Refund webhook endpoint

---

opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py

When determining opening hours we want to check the length of the opening time not to be zero. If zero not include the time for convenience.
Refs TILA-2378

 TILA-2378 | Make zero length opening hours to be skipped by opening hours client

---

opening_hours/enums.py
opening_hours/hours.py
opening_hours/tests/test_get_opening_hours.py

Make hauki reader to be failproof when encountering unknown resource states. Previously it blew up when non-existent state was present.  This makes it default to UNDEFINED status.
Refs TILA-2377

TILA-2377 | Make hauki reader handle unknown resource states

---

api/graphql/reservations/recurring_reservation_serializers/create_serializers.py
api/graphql/tests/test_recurring_reservations/test_recurring_reservation_create.py
api/graphql/tests/test_recurring_reservations/test_recurring_reservation_update.py

- Make possible to empty the `RecurringReservation` description through the gql api mutations
Refs TILA-2101

TILA-2101 | Make possible to empty RecurringReservation description

---

api/graphql/merchants/merchant_types.py
api/graphql/tests/snapshots/snap_test_orders.py
api/graphql/tests/test_orders.py

- Added `refund_id` field to `PaymentOrderType`
PR is failing because there is a CVE in `cryptography` package. #776 upgrades the package so I'll update this one after #776 has been merged

TILA-2396: Add refund_id to PaymentOrderType

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/tests/test_helpers.py

- Fixed invalid reservation time in PaymentOrder
The old code didn't use get_default_timezone() so we ended up having different times in our database and in web shop.

TILA-2397: Fix invalid reservation time in payment order

---

api/graphql/reservations/reservation_serializers/deny_serializers.py
api/graphql/tests/test_reservations/test_reservation_deny.py

- Makes possible to deny also Reservations with state of CONFIRMED
- Makes impossible to deny reservation that end time has passed
- Send emails only when Reservation type is NORMAL

TILA-2162 | Reservation deny validation rule additions

---

api/urls.py

This excludes graphiql from staging and production. And we want it so.
Refs TILA-2406

TILA-2406 | Don't use graphiql when DEBUG is false

---

merchants/verkkokauppa/order/test/test_create_order_params.py
merchants/verkkokauppa/order/types.py
merchants/verkkokauppa/tests/test_order_types.py

- Replaced `isoformat()` with `strftime()` and custom format
Order Experience API does not support standard ISO 8601 format with UTC offset. That is why we have to manually define a custom format. This is a bit risky since Verkkokauppa assumes that this date has to be in Europe/Helsinki timezone. Any change in timezones can cause problems.

TILA-2464: Fix order creating issue with wrong datetime format

---

merchants/pruning.py
merchants/tests/test_pruning.py

- Added checks for case where payment does not exist
- Unit test that catches the old problem and confirms the fix
It did not handle the case where payment does not exist in Verkkokauppa. I added the checks and if status cannot be checked, it is treated as expired.

TILA-2428: Fix update_expired_orders

---

.github/workflows/build.yml
merchants/admin.py

- Changed merchant form fields to be required
- Fixed GitHub action. This should fix SonarCloud as well.
Verkkokauppa requires these fields so they must be required on our side as well.

TILA-2467: Change merchant form fields to be required

---

api/graphql/reservation_units/reservation_unit_types.py
utils/query_performance.py

- Fix bug in `QueryPerformanceOptimizerMixin` class 
- no prefetches were executed if used advanced optimization and the field did not exist in actual query.
- Fix Correct field_name for querying `reservationUnits` (was `reservationUnit`)
- Adds more query optimizations to reservationUnits query
Refs TILA-2442
There might be some things yet to do with QueryPerformanceOptimizer. Will see.

TILA-2442 | ReservationUnits query performance configurations

---

.github/actions/setup-python-env/action.yml
.github/workflows/build.yml

- Changed each step to be own job with leads to parallel running
This should decrease the waiting time of individual tests on PRs because each test is running at the same time. Pytest still takes annoyingly long so the total waiting time does not decrease.

TILA-1518: Parallelize GitHub actions

---

api/graphql/reservations/reservation_mutations.py
api/graphql/tests/test_reservations/test_reservation_deny.py
permissions/api_permissions/graphene_permissions.py

- Adds new permission class  `ReservationDenyPermission` and use in deny mutation.
- permission checks for staff user can either handle reservations or can create staff AND is self created one.
There should be possible for staff members to deny self created (staff created reservations).
Makes new permission for denying based on the
ReservationHandlingPermission called ReservationDenyPermission and use in deny mutation.
Refs TILA-2471

TILA-2471 | Staff can deny self created reservations

---

api/graphql/reservations/reservation_serializers/approve_serializers.py
api/graphql/reservations/reservation_serializers/deny_serializers.py
api/graphql/tests/test_reservations/test_reservation_approve.py
api/graphql/tests/test_reservations/test_reservation_deny.py

- Remove overwrite of working memo with handling_details in approve serializer and in deny serializer
The working memo was originally used as the handling details but there has been separation with handling details and working memo some time ago and the copying of the handling details value to working_memo is needed to remove now.
Refs TILA-2447

TILA-2447 | Don't overwrite working_memo with handling details

---

api/graphql/reservations/reservation_serializers/create_serializers.py
api/graphql/reservations/reservation_serializers/update_serializers.py
api/graphql/tests/test_reservations/test_reservation_update.py

- Disable profile data fetch in reservation update serializer
ReservationUpdateSerializer is subclass of reservationCreate so the prefill logic is present also there. This isn't what we wan't. This disables the data fetching from profile in reservation update serializer.

Don't prefill data from profile in reservation update

---

api/graphql/tests/test_reservation_unit_image.py
reservation_units/migrations/0084_reservation_unit_image_url_fields.py
reservation_units/models.py
reservation_units/tasks.py
reservation_units/tests/test_reservation_unit_image_save.py

- Generates `ReservationUnitImage`'s urls when its saved
- Changes the `update_url` task to take optional parameter for giving single res unit image
Refs TILA-2510

TILA-2510 | Generate image urls on reservation unit image save

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/test/test_create_order_params.py

- Use `round_decimal` to strip unnecessary decimals
We did not round the decimal when webshop order is created leading way too many decimals.

TILA-2499: Fix issue with too many decimals

---

merchants/verkkokauppa/exceptions.py
merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/test/test_create_order_params.py
merchants/verkkokauppa/tests/test_helpers.py

- Add reservation number to webshop order meta fields
- Add language support to meta field labels
The implementation might still change because I'm not sure if language should come from the reservation user or from `reservee_language` field

TILA-2485: Add reservation number and language support

---

api/tests/test_webhook_api.py
api/webhook_api/views.py

- Fixed webhook payload. Webshop documentation was wrong and that lead to wrong implementation
- Log invalid webhook calls to sentry
In normal use webhooks should not fail. Failures are indication of changes in webshop side or someone bombarding API with malicious payload. By sending these to Sentry we get proper alerts when things go haywire.

TILA-2517: Log invalid webhook calls

---

Dockerfile

- Add setuptools install to Dockerfile
uWSGI installation fails with the new PIP version. For some reason it works fine in GitHub actions and one difference is that we install `setuptools` in GitHub actions but not in the Dockerfile. I'll give this a try. Another possible fix is to use `--use-pep517` flag with `pip install` but I'll try that next if this does not work.
Because the only way to test this is to merge it and see how it runs in CI, I'll do it without reviews just to get forward with this ⚠️ 🙈 

TILA-2522: Add setuptools to Dockerfile

---

Dockerfile

- Removed previous build test
- Added `--use-pep517` flag to Dockerfile
uWSGI installation fails with the new PIP version. Because the only way to test this is to merge it and run it in CI, I'll merge this without reviews ⚠️ 🙈 

TILA-2522: Add --use-pep517 flag to Dockerfile

---

api/graphql/application_rounds/application_round_types.py
api/graphql/tests/test_application_rounds/snapshots/snap_test_application_round_query.py
api/graphql/tests/test_application_rounds/test_application_round_query.py

- Excludes DRAFT, CANCELLED and  EXPIRED applications from ApplicationRoundType's applicationsCount
In ApplicationRoundType (gql) there is field which tells how many applications there are in the round. Previously it told the amount of applications excluding DRAFTs but for now it should be excluding also CANCELLED and EXPIRED ones.
Refs TILA-2508

TILA-2508 | Don't include DRAFT, CANCELLED or EXPIRED in applicationsCount

---

allocation/tests/test_allocation_solver.py
allocation/tests/test_allocation_solver_baskets.py
applications/tests/test_allocation_result_mapper.py
requirements_dev.txt

- Upgrade urllib3 package in requirements_dev.txt
- Disable allocation tests
For some reason the tests are failing on my mac. The feature is not used so I just disabled these tests. We could remove the whole feature in the future but that might require a bit more work especially if there are some code written on the client side too.

TILA-1518: Skip allocation tests

---

api/graphql/tests/test_reservation_units/snapshots/snap_test_reservation_units_state_filter.py
api/graphql/tests/test_reservation_units/test_reservation_units_state_filter.py
reservation_units/tests/test_reservation_unit_reservation_state_helper.py
reservation_units/tests/test_reservation_unit_state_helper.py
reservation_units/utils/reservation_unit_reservation_state_helper.py
reservation_units/utils/reservation_unit_state_helper.py

- changes the ReservationUnitReservationStateHelper to return
reservation state as RESERVATION CLOSED when reservation unit's
reservation begins and *_ends dates are in past and the same
- Returns HIDDEN state when publish dates in the past and the same
- Shows correctly scheduled publishing reservation units when publish dates in the future
See commit messages for details
Refs TILA-2451

TILA-2451 | Reservation unit state helper fixes

---

api/tests/test_webhook_api.py
api/webhook_api/views.py

- Remove timestamp fields from webhook validation
We are not using these fields so just to avoid shadowboxing with all the mixed implementations on webshop side, I just removed'em.

TILA-2525: Remove timestamp fields from validation

---

Dockerfile.local
README.md
docker-compose.yml

- Created separate Dockerfile for local running
- Updated README to contain simplified instructions
Running core locally can be a pain in the 🍑 . So, I decided to simplify it for the frontend devs. We don't need all that RedHat crap and service runs just fine in with standard python image. This drops some configuration and RedHat requirements and service can be run with a single command.

TILA-2271: Separate Dockerfile for running the service locally

---

api/tests/test_webhook_api.py
api/webhook_api/views.py
merchants/verkkokauppa/payment/exceptions.py
merchants/verkkokauppa/payment/requests.py
merchants/verkkokauppa/payment/test/test_refund_status_from_json.py
merchants/verkkokauppa/payment/types.py
merchants/verkkokauppa/tests/test_payment_requests.py

- Added client support for the new endpoint in webshop
- Use client in the refund webhook handler
This endpoint wasn't available before but now it is so we are using it.

TILA-2465: Check refund status from webshop API on refund webhook

---

users/models.py
users/tests/test_resolve_user.py
users/utils/open_city_profile/birthday_resolver.py

- Add util property check whether user is supposed to be staff user (since django's is_staff won't work in this case)
- Read profile id only for regular users - not staff users
- Catch exceptions reading profile_id and send'em to sentry 
Refs TILA-2531

TILA-2531 | Read only regular user's profile_id

---

reservations/tasks.py

- Removed task scheduling from the code
We schedule tasks using Admin UI. It is quite likely that these lines are the reason why we see so many scheduling errors in Sentry.

TILA-1518: Remove task scheduling from the code

---

tilavarauspalvelu/settings.py

- Add missing cache settings to OpenShift config section
Forgot to add these settings to OpenShift section when I moved these settings around and removed the nesting. I'll merge this without review because just to move forward a bit faster. We can review the final state as soon as Redis cache works ☺️ 

Add session engine conf to OpenShit section

---

tilavarauspalvelu/settings.py

- Added Redis password setting
Just having SENTINEL_KWARGS does not seem to work. Perhaps separate PASSWORD setting solves the issue.
I'll merge this PR without reviews because I need to test these in dev environment.

TILA-2505: Add Redis password setting

---

spaces/models.py
spaces/tasks.py

Sometimes the tree hierarchies gets corrupted and need a rebuilding. This adds task for rebuilding the hierarchies and does partial_rebuild when saving Space instance.

TILA-2561 | Add task to rebuild space hierarchy and rebuild on save

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/tests/test_helpers.py

- Removed padding zeroes from the date
I did not know that Python's date formatting does not support values without padding zeroes. So, ended up building the proper format by hand.

TILA-2540: Remove padding zeroes from date

---

api/graphql/reservations/reservation_serializers/create_serializers.py
api/graphql/tests/test_reservations/test_reservation_create.py
users/tests/test_basic_info_resolver.py
users/utils/open_city_profile/basic_info_resolver.py

- Adjust address parsing
Sometimes we had addresses where city value container something like "Helsinki FI". This happened with foreign addresses that can have all kinds of weird address formats. Now, only address field is used from the foreign address and other fields are ignored.

TILA-2516: Adjust profile address parser

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Added `refund_uuid` to `reservations` query

TILA-2544: Add refund_uuid to reservations query

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Added reserveeName field to ReservationType
- Fixed some typing definitions to keep linters and Sonar happy
This fields returns the correct name based on the customer type. This way we don't have to have the same logic on the client side and they can just show the name.

TILA-2569: Add reserveName field to ReservationType

---

Dockerfile

- Upgraded NPM
For some reason sentry-cli installation failed. Let's see if upgrading NPM solves the issue.

TILA-2582: Upgrade NPM

---

users/models.py

Override the user's __str__ method to output the last login for the user in the django admin dropdowns.
Refs TILA-2547

TILA-2547 | Display last login for user display in django admin

---

api/graphql/merchants/merchant_types.py
api/graphql/tests/test_orders.py

- Hide checkout URL if order is not in `DRAFT` state

TILA-2613: Hide checkout URL if order is not in DRAFT state

---

api/graphql/opening_hours/opening_hours_types.py
opening_hours/decorators.py
opening_hours/hours.py
opening_hours/utils/opening_hours_client.py
reservation_units/utils/reservation_unit_reservation_scheduler.py
tilavarauspalvelu/settings.py

- Removed deprecated timezone handlings
- Removed USE_DEPRECATED_PYTZ settings. Not needed anymore.
We still had places where pytz library was used to handle timezones. This causes problems and confusing behaviour with the new Python version so I fixed all of them.
I also removed USE_DEPRECATED_PYTZ setting because it is not needed anymore.

TILA-2616: Remove deprecated timezone handling

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/tests/test_reservations/test_reservation_create.py

- Updated duration validation
This means that if reservation unit's interval is set to 15 minutes, allowed durations are 15, 30, 45 etc. If interval is 30 minutes, allowed durations are 30, 60, 90 etc.

TILA-2571: Validate duration being a multiple of interval

---

api/graphql/reservations/reservation_mutations.py
api/graphql/tests/test_reservations/test_reservation_approve.py
api/graphql/tests/test_reservations/test_reservation_require_handling.py
permissions/api_permissions/graphene_permissions.py

- Changes permission logic to handling permissions 
- Adds new mutation for refund mutation - it works as was previous mutation
This makes possible for reserver role staff user to perform handling permission based mutations to own reservations.
Within this change refund permission is introduced like the handling was originally working => so refund permissions are not changed but only the Approve and RequiresHandling
Refs TILA-2519

TILA-2519 | Modify reservation handling permission

---

api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_queries.py

- Added `is_handled` field to `ReservationType`

TILA-2608: Add is_handled field to ReservationType

---

api/graphql/applications/application_filtersets.py
api/graphql/tests/test_application_events/test_application_events_query.py

- Changes `ApplicationEvent` as model for the `ApplicationEventFilterSet` class.
This filterset class was using wrong class (Application) and caused oddities.
Refs TILA-2644

TILA-2644 | Use correct model in ApplicationEventFilterSet class

---

api/graphql/tests/base.py
api/graphql/tests/test_reservations/test_reservation_working_memo_update.py
permissions/helpers.py

- Modify can_comment_reservation permission helper to allow staff reserver to comment/save working memo for them own reservations
- Check service sector and unit permissions in `can_comment_reservation` permission
Refs TILA-2637 TILA-2592

TILA-2637 | Modify comment permissions to allow staff reserver comment its own reservations

---

api/applications_api/serializers.py

- Set user in `create` and `update` methods
In the REST API, creating and updating an application did not save the user. This is probably because of the updated `djangorestframework`. The simple fix was to just set it manually in create and update methods.
Would be really nice to get rid of these REST endpoints 😄 

TILA-2662: Set authenticated user in create and update

---

api/graphql/reservations/reservation_serializers/create_serializers.py
api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/reservations/reservation_serializers/staff_create_serializers.py
api/graphql/reservations/reservation_serializers/staff_reservation_modify_serializers.py
api/graphql/reservations/reservation_types.py
api/graphql/tests/test_reservations/snapshots/snap_test_reservation_queries.py
api/graphql/tests/test_reservations/test_reservation_create.py
reservation_units/models.py
reservation_units/tests/test_reservation_unit.py

- Fixed a bug with `get_next_reservation`
- Ignore `BLOCKED` reservations when buffers are checked
- When BLOCKED reservation is created/updated, buffer check is skipped

TILA-2628: Ignore blocked reservations when buffers are checked

---

tilavarauspalvelu/tests/test_anonymization.py
tilavarauspalvelu/utils/anonymisation.py

- Disable special roles and notifications when user is anonymized
- Disable general, service sector and unit roles when user is anonymized

TILA-2618: Remove roles when user is anonymized

---

api/graphql/tests/snapshots/snap_test_users.py
api/graphql/tests/test_users.py
api/graphql/users/user_types.py
api/tests/conftest.py
api/tests/test_users_api.py
api/users_api.py

- Fixed the logic with `get_reservation_notification`
We need to use `has_staff_permissions` instead of `is_staff`. Thise caused some changes to test data as well. It is actually a bit confusing that we have the `is_staff` flag but we an alternative definition for `staff_permissions`.

TILA-2620: Fix reservation notification permissions

---

api/graphql/reservation_units/reservation_unit_types.py
tilavarauspalvelu/utils/date_util.py

- Fixed `to` and `from` parameters when calling `with_same_components`.
- Refactoring: moved time adjustments to `date_util` file
I made this fix a while ago but I forgot to include `with_same_components` call.

TILA-2568: Fix date filter + refactoring

---

api/graphql/reservations/reservation_serializers/mixins.py
api/graphql/reservations/reservation_serializers/staff_adjust_time_serializers.py
api/graphql/tests/test_reservations/test_reservation_staff_adjust_time.py

- Updated `staffAdjustReservationTime` mutation to allow buffer modifications
- Added a new test
I'm still wondering if we need to add some additional validations for the new "buffer zones" 🤔 

TILA-2670: Allow buffer modifications

---

api/gdpr.py
api/models.py
api/tests/test_gdpr/test_gdpr_api.py
setup.cfg

- Deny deleting user data through gdpr api when user has reservations one month backwards
- Add flake local_settings to flake ignore.
- Add reservation begin and end to gdpr output data
- Add tests for reservation and application data
- Change applications to be returned list inside a list rather than single list with all the application data.
Refs TILA-2679

TILA-2679 | Deny user data delete through gdpr api when there's reservations in one month backwards

---

api/tests/test_application_status_api.py
applications/tests/test_reservation_creation.py
applications/utils/reservation_creation.py

- Create reservations as CONFIRMED from allocation results
Previous was created as CREATED but those states gets deleted by the pruning task
Refs TILA-1321

TILA-1321 | Create reservations as CONFIRMED from allocation results

---

.env.example
reservation_units/models.py
reservation_units/tasks.py
reservation_units/tests/test_purpose.py
tilavarauspalvelu/settings.py
utils/image_cache.py
utils/tests/test_image_cache.py

- Added a helper function for purging individual images
- Updated Purpose save so that it'll purge images every time Purpose is saved
- Unit tests for new functionality
Images are purged every time Purpose is saved. I didn't bother checking if new image is actually uploaded since this is just about the cache. All it causes is an addition backend hit before image is cached again. I decided to do this in as a background task because it is using HTTP calls that can delay the `save` call. Because cache purge is a secondary action, in case of error it does not prevent Purpose saving. However, errors are logged.
Vitalijus already set up an image cache for us in the dev environment. We just need to enabled it before this one is merged.

TILA-2676: Add support for image cache and purging of individual images

---

.env.example
tilavarauspalvelu/settings.py
utils/image_cache.py
utils/tests/test_image_cache.py

- Added `IMAGE_CACHE_HOST_HEADER` settings
- Renamed `IMAGE_CACHE_ROOT_URL`-> `IMAGE_CACHE_VARNISH_HOST`
I did not know that host header is required for purge to work but that seems to be the case 🤷

Refs TILA-2676: Add IMAGE_CACHE_HOST_HEADER setting

---

.env.example
.gitignore
tilavarauspalvelu/settings.py

- Added `celery.pidbox.exchange` to `.gitignore`
- Added `SESSION_COOKIE_DOMAIN`
This PR used to be about file upload, but yesterday we agreed that we just keep the CSRF-token disabled, because there is no easy way to make it work and with the limited time we have, we can't focus on figuring out how to make it work on both frontend and backend.
So, now it is just about small tweaks.

TILA-2410 - Small tweaks

---

api/graphql/resources/resource_filtersets.py
api/graphql/schema.py
api/graphql/spaces/space_filtersets.py
api/graphql/tests/snapshots/snap_test_resources.py
api/graphql/tests/snapshots/snap_test_spaces.py
api/graphql/tests/test_resources.py
api/graphql/tests/test_spaces.py
permissions/helpers.py

- Added `onlyWithPermission` filter to `spaces` query
- Added `onlyWithPermission` filter to `resources` query
- Created unit tests covering different permission cases
This changes allows listing only spaces/resources that user can **modify**.

TILA-2657: Add onlyWithPermission filter to spaces and resources queries

---

reservation_units/models.py
reservation_units/tests/test_reservation_unit_image_save.py

- Added image purge call to ReservationUnitImage save
- Added unit tests
There is no need to purge images when ReservationImageUnit item is deleted because these images are not referenced anywhere anymore. Client should not receive these image urls from the API. Yes, cached images are still visible but cache has 24h TTL so these images will disappears automatically.

TILA-2676: Purge image cache on Reservation Unit Image save

---

opening_hours/enums.py
opening_hours/tests/test_opening_hours_client.py
opening_hours/utils/opening_hours_client.py
reservation_units/utils/reservation_unit_reservation_scheduler.py

Takes into an account collapsing opening hours e.g when the reservation unit is open 10-18 and there is maintenance break 13-14 the opening hour needs to be splitted into two (10-13 and 14-18)
Refs TILA-2661

TILA-2661 | Take into account collapsing closed opening hours

---

api/graphql/tests/snapshots/snap_test_orders.py
api/graphql/tests/snapshots/snap_test_reservation_unit_cancellation_rules.py
api/graphql/tests/test_orders.py
api/graphql/tests/test_reservation_unit_cancellation_rules.py
api/graphql/tests/test_reservation_units/conftest.py
applications/tests/test_application_export.py
email_notification/tests/test_notification_builders.py
merchants/verkkokauppa/tests/conftest.py
opening_hours/hours.py
opening_hours/tests/conftest.py
opening_hours/tests/test_get_opening_hours.py
reservation_units/tests/test_reservation_unit_reservations.py
reservations/models.py
reservations/tests/test_reservation_statistics.py
users/tests/test_basic_info_resolver.py

- Fix returning opening hours start and end time when they are none
- Improvements to tests
- Remove duplicate tests
- Fix running HAUKI tests when .env variables were set (Before it was required to not have them set at all)
- Remove IDs from snapshot tests to allow reusing the same test db for faster test runs
- Some tests that fail in parallel require setting `--dist=loadscope` argument when running tests
- TILA-2772, TILA-2836

Opening hours fix

---

api/graphql/schema.py
tests/test_graphql_api/test_banner_notification/test_filtering.py

- Adds endpoint for fetching a single banner notification by ID
- [TILA-1588](https://helsinkisolutionoffice.atlassian.net/browse/TILA-1588)
[TILA-1588]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add endpoint for fetching a single banner notification

---

merchants/admin.py

- Increase paytrail merchant id maximum length to 16
- Remove minimum length from the ID
- The length should be 6 digits, but the City Of Helsinki test merchant ID is 7 digits
- TILA-2766

Paytrail Merchant ID

---

docker/Dockerfile
docker/entrypoint.sh
docker/worker.sh
tilavarauspalvelu/celery.py
tilavarauspalvelu/settings.py

Helps to debug celery errors
- Adds rotating log file to celery worker for better debugging. Logs are rotated on hourly basis and last 12 files are kept as backup.
- TILA-####

Add rotating file logging option to celery workers

---

opening_hours/utils/hauki_api_client.py

- Fix `build_url`, as it broke when the resource id had a `:` in it
- TILA-####

Fix `HaukiAPIClient.build_url` for origin prefixed resource IDs

---

api/webhooks/serializers.py
api/webhooks/views.py
tests/test_webhooks/test_order_payment_webhooks.py

- `payment_id` is not uuid, but `uuid + _at_ + yyyymmdd-hhmmss`
- TILA-####

Loosen webhook payment_id validation

---

api/webhooks/serializers.py
tests/test_webhooks/test_order_refund_webhooks.py

- Loosen validation on refundPaymentId field in refund webhook 
- TILA-####

Loosen validation on refundPaymentId field in refund webhook

---

merchants/verkkokauppa/helpers.py
merchants/verkkokauppa/order/test/test_create_order_params.py
merchants/verkkokauppa/tests/test_helpers.py

- Change verkkokauppa payment user info to reservation user from reservation reservee.
- TILA-2913

Use reservation user info for payment instead of reservee info

---

actions/application.py
actions/application_round.py
applications/admin/application.py
applications/admin/application_event.py
applications/admin/application_round.py
templates/admin/reset_allocation_confirmation.html
tests/factories/application.py
tests/test_actions/test_reset_application_allocation.py
tilavarauspalvelu/settings.py

- Add an option to reset application rounds' or applications' allocation from the admin panel
- [TILA-2771](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2771)
[TILA-2771]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add admin actions to reset application/application round allocation

---

api/graphql/types/application_event/filtersets.py
tests/test_graphql_api/test_application_event/test_filtering.py

- Fixes `textSearch` filter on application events to also consider partial matches where the match is a prefix
- TILA-####

Make application event text search consider partial matched by prefix

---

reservations/querysets.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py

- Fix a bug in the first reservable time deduction where affecting reservations could not be found if the filtered date was the same as the reservation's date
- Automated tests (regression test made)
-

Fix reservations not being found for exclusion if not on the same day

---

common/date_utils.py
common/utils.py
reservation_units/querysets.py
reservations/querysets.py
tests/test_graphql_api/test_application/helpers.py
tests/test_graphql_api/test_application_event/helpers.py
tests/test_graphql_api/test_application_event/test_create.py
tests/test_graphql_api/test_application_event/test_update.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py
tests/test_utils/test_date_util.py

- Fix issues where blocking reservations were not handled correctly when different timezone objects were used to make time objects timezone-aware. 
- Added utilities that should allow handling these situations correctly
- TILA-####

Fix first reservable time bug with blocking reservation

---

reservations/querysets.py
tests/test_graphql_api/test_reservation_unit/test_query_reservable_fields.py

- Fixes a bug that was discovered in manual testing
- This bug occurred when:
- Two ReservationUnits are in common hierarchy by a Resource
- The second ReservationUnit has a Space, which is completely unrelated to the other ReservationUnits Spaces
- The GraphQL query includes other filters (such as `pk`, `name_fi`, etc.) which filter out the second ReservationUnit
None

Fix ReservationUnits in common hierarchy by Resource but with unrelated Space

---

actions/application_event.py
api/graphql/types/application_event_schedule/serializers.py
applications/querysets/application_event_schedule.py
common/date_utils.py
tests/factories/application.py
tests/test_graphql_api/test_application_event_schedule/test_approve.py

- Add new schedule approve validation rules:
- These rules **_can_** be skipped with the `force` flag
- Allocated duration cannot be less than `event.min_duration`
- Allocated duration cannot be more than `event.max_duration`
- Allocated duration must be a multiple of 15 minutes
- Cannot allocate more events than `event.events_per_week`
- Cannot allocate more than one event per day
- Can only allocate on users' wished times
- These rules **_cannot_** be skipped with the `force` flag
- Cannot allocate to a reservation unit not included in the event's event reservation units
- Cannot allocate an already allocated period for the same reservation unit in any overlapping schedule based on events begin and end times, even from other …

Add new schedule approve validation rules

---

.github/workflows/test.yml
docker/Dockerfile
poetry.lock

- ~~Cache Postgres `test_tvp` database between runs to avoid re-running migrations~~
- ~~Improves CI time by 15s ~ 1 min (bottlenecked by CPU-intensive operations)~~
- ~~Can cause issues if migrations are changed in multiple PRs. Currently, you'd need to delete the [cache-postgres-v1](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/actions/caches) cache instance and rerun the pipeline if this happens. Maybe there is a way to detect if migrations have changed?~~
- Cache poetry installation between runs
- Improves CI time by 10s-30s
- Chech that migrations run correctly

Cache poetry installation between CI runs

---

elastic_django/reservation_units.json

- ES shows warnings about missing this file, which was removed by accident during a refactor.
Error:
> Index 'reservation_units' has no mapping, relying on ES instead.
- Error should not now anymore
- TILA-####

Add back elastic search mapping file

---

reservations/models/reservation.py
reservations/tests/test_reservation_reservee_name.py
tests/test_graphql_api/test_reservation/test_query.py

- For `reservation.reservee_name`, return `reservee_first_name` and `reservee_last_name` if `reservee_type`/CustomerType is not defined
- Optimise reservee name tests by removing database requirement
- [TILA-3022](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3022)
---
[TILA-3022]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update reservee_name method

---

api/graphql/types/reservation_units/mutations.py
opening_hours/management/commands/update_hauki_hashes.py
opening_hours/utils/hauki_api_client.py
opening_hours/utils/hauki_resource_hash_updater.py
tilavarauspalvelu/logging.py
tilavarauspalvelu/middleware.py
tilavarauspalvelu/settings.py
tilavarauspalvelu/utils/logging.py

- Log error traceback for GraphQL errors in Sentry middleware. This should help debugging during tests.
- Simplify Django logging configuration to the base minimum we need.
- Nothing to test
- TILA-####

Add traceback logging for graphql errors

---

.github/workflows/test.yml

- Temporary fix for CI faling due to [misconfigured Microsoft apt repo for Ubuntu 22.04](https://github.com/microsoft/linux-package-repositories/issues/130).
- CI should not fail.

Fix CI failing due to misconfigured apt repo

---

api/graphql/types/reservation/serializers/create_serializers.py
tests/test_graphql_api/test_reservation/test_create.py

- Fixes issues in profiling reservations from Helsinki profile if data received would be null, but the reservation field would require non-null value.

Fix reservation prefill failing due to null values

---

email_notification/helpers/email_builder_application.py
email_notification/helpers/email_builder_reservation.py
email_notification/helpers/email_sender.py
email_notification/tasks.py
tests/test_email/test_email_sender.py

- Use default language for all staff emails (before the reservee language was incorrectly used for the staff emails)
- [TILA-2666](https://helsinkisolutionoffice.atlassian.net/browse/TILA-2666)
[TILA-2666]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-2666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix using default language for all staff notifications

---

reservation_units/utils/first_reservable_time_helper.py
tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py

- Fixes issue in the first reservable time calculation where the algorithm would give the wrong first reservable time based on surrounding reservations and the minimum reservable time. This happened due to exiting too early when shortening a reservable time span based on surrounding reservations, leaving the reservable time span just long enough to fit a reservation, when subsequent reservations would have made it actually shorter, meaning another reservable time span should have been used instead. TL;DR: An off-by-one error.
[//]: # "Is this PR dependent on other changes outside this repository? Describe the …

Fix issue in first reservable time calculation when duration exactly minimum

---

api/graphql/types/reservation_unit/filtersets.py
api/graphql/types/reservation_unit/types.py
applications/models/application_section.py
elastic_django/reservation_units/query_builder.py
opening_hours/tests/test_hauki_link_generator.py
opening_hours/utils/hauki_link_generator.py
tests/test_graphql_api/test_reservation_unit/test_hauki_integration.py
tests/test_utils/test_reservation_unit_query_builder.py

- Fixes issue in `usable_reservation_unit_options` lookup property where it would check for all reservation unit options instead the specific applications sections. This fixes incorrectly showing `IN_ALLOCATION` as section status when all its options are rejected/locked.
- None
- [TILA-3339][TILA]
[TILA]: …

Fix usable reservation unit options lookup property

---

.github/workflows/test.yml
tilavarauspalvelu/settings.py

- This allows using the CI environment in Azure Pipelines for running deploy mid-hooks, which make database our migrations.
- None

Make CI environment require `DATABASE_URL`

---

applications/admin/application.py
applications/admin/application_round.py
locale/fi/LC_MESSAGES/django.po

- Resetting no longer only resets allocations but can also remove recurring reservations. Correct the confirmation page to reflect this.
- None

Correct text related to resetting applications and application rounds

---

api/graphql/types/unit/filtersets.py
spaces/models/unit.py
spaces/querysets/unit.py
tests/test_graphql_api/test_unit/test_ordering.py

- Fixes unit's unit group name ordering filters by replacing them with language-specific versions
- Use the alphabetically first unit group linked to the unit as the unit group name
- Frontend needs to change to support the new language-specific filters
- https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1241
- None

Replace unit group name filter with language-specific versions

---

locale/fi/LC_MESSAGES/django.po
opening_hours/utils/reservable_time_span_client.py
opening_hours/utils/time_span_element_utils.py
reservation_units/utils/first_reservable_time_helper/first_reservable_time_reservation_unit_helper.py
reservations/signals.py
spaces/signals.py
tests/test_external_services/test_hauki/test_merge_overlapping_time_span_elements.py
tests/test_models/test_reservation_statistics.py
tests/test_tasks/test_prune_reservation_statistics.py
tilavarauspalvelu/settings.py

- Fixes `merge_overlapping_time_span_elements` function messing up first reservable time calculation. 
- Previously, the function would merge time spans by modifying existing time spans, which are shared among multiple reservation units through the reservation unit hierarchy. This effect would compound with reservation time spans from sibling reservations units (i.e. don't affect each other, but do affect their parent) starting to affect each other.
- This PR fixes that by copying the merged time spans inside the `merge_overlapping_time_span_elements` function.
- Currently, there is no test to verify this, but one should be made in #1252
- Also fixes a small issues with the merging function itself in certain edge cases (see …

Fix merge overlapping timespans

---

api/graphql/types/rejected_occurrence/filtersets.py

- Changes the `reservation_unit` and `unit` filters to accept multiple ids for filtering. Frontend required this change.
- None
- None

Change RejectedOccurrenceFilterSet filters to accept multiple values

---

applications/tasks.py

- Fixes a null-constraint error with moving `Organisation.identifier` to `Reservation.reservee_id` for unregistered organisations. This previously broke reservation generation from applications.
- None
- None

Fix reservation generation breaking with unregistered organisations

---

applications/models/application_section.py
common/date_utils.py
tests/test_models/test_application_section.py
tests/test_utils/test_date_util.py

- Fix ApplicationSection.status in cases where all reservation unit options were locked/rejected but it still had allocated slots
- Fix generating reservations for allocated slots that end at midnight
- Manual testing is probably good also
- None
- [TILA-3450][TILA]
[TILA]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3450 …

Fix section status

---

common/management/commands/data_creation/main.py

- This is required to make db flush work in certain edge cases. Required to flush data in dev for test data creation.
- Tested already in Dev by editing a file there.
- None
- None

Add `allow_cascade=True` to test data creation flush

---

docker/Dockerfile

- This is done due to hitting pull rate limits for Docker Hub (for unauthenticated users) in Azure Pipelines. At the time, this is 100 pulls per 6 hours, which is shared with all Platta developers. ECR offers 1 pull per second (for unauthenticated users), which we shouldn't hit too often since CI also has retries for pulling images.
- Builds should work in GitHub CI and Azure Pipelines
- None
[//]: # "This pull request resolves …

Switch to ECR for pulling docker images

---

reservation_units/utils/first_reservable_time_helper/first_reservable_time_helper.py
reservation_units/utils/first_reservable_time_helper/first_reservable_time_reservation_unit_helper.py
reservations/migrations/0073_affectingtimespan.py
reservations/models/affecting_time_span.py
tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py

- Fixes a bug in the pagination optimization with reservation units without a hauki resource
- Fixes a migration dependency issue with creating the AffectingTimeSpans materialized view
- Fixes a bug with `AffectingTimeSpan.is_valid()` check indicating the view is invalid when it's actually the opposite
- None
- None

Fix FRT pagination issues

---

actions/recurring_reservation.py
applications/tasks.py

- See title. Move the code creating the statistics outside the transaction block.
- None
- None

Fix creating reservation statistics when creating seasonal bookings

---

api/graphql/types/unit/filtersets.py
tests/test_graphql_api/test_unit/test_filtering.py

- Fix Unit `publishedReservationUnit` filter incorrectly excluding units where the ReservationUnit is published but not yet reservable
- None
- [TILA-3501](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3501)
[TILA-3501]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

ReservationUnit reservation begins/ends doesn't affect published filter

---

reservation_units/tasks.py
tests/factories/unit.py
tests/test_models/test_reservation_unit_pricing_updates.py

- The task `company_code` ignore is now applied to `PaymentAccounting`s through `Unit` relation also
- None
- [TILA-3519](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3519)
[TILA-3519]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

Extend company code exclusion to units in tax percentage update task

---

tilavarauspalvelu/celery.py

- Needed due to `celery status` taking too long to respond, causing the celery worker pods to crash even if they are actually healthy.
- Needs to be tested in at least the development environment to make sure it works.
- None
- None

Add a better celery health check

---

actions/recurring_reservation.py
applications/enums.py
applications/tasks.py
opening_hours/utils/hauki_api_client.py
opening_hours/utils/hauki_api_types.py
opening_hours/utils/reservable_time_span_client.py
tests/test_utils/test_generate_reservations_from_allocations.py
utils/external_service/base_external_service_client.py

- Block generating reservation series for days that are marked as `override=True` and `state=closed` in HAUKI API
- None
- [TILA-3495](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3495)
[TILA-3495]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

Generate reservation series holidays

---

reservation_units/admin/reservation_unit/form.py

- Fix removing empty timeslots in Django Admin
- Before `timeslots` were looped and `i` timeslot was deleted, which was wrong since the list was looped in reverse order
- Manual testing
- None
- None

Django Admin: Fix removing empty timeslots

---

api/gdpr/urls.py
tests/test_gdpr_api/test_gdpr_api.py
tilavarauspalvelu/urls.py
users/admin/user.py

- See title. Also validate that given uuid is correct.
- None
- None

Make slash optional in GDPR path

---

tilavarauspalvelu/admin/reservation/admin.py

- See title. Crashes reservation admin page otherwise.
- None
- None

Fix a couple of reservation admin reservation unit refs

---

tests/test_graphql_api/test_reservation_unit/test_pricing.py
tilavarauspalvelu/api/graphql/types/reservation_unit/serializers.py
tilavarauspalvelu/api/graphql/types/reservation_unit_pricing/types.py
tilavarauspalvelu/models/reservation_unit_pricing/queryset.py

- Hide old reservation unit pricings in the GQL API
- Remove already deprecated "status" from GQL API fields
- None
- [TILA-3660](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3660)
[TILA-3660]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

Old pricing is hidden in GQL

---

tests/test_graphql_api/test_application_section/test_filtering.py
tests/test_graphql_api/test_equipment/helpers.py
tests/test_graphql_api/test_equipment/test_query_all.py
tests/test_graphql_api/test_reservation_unit/helpers.py
tests/test_graphql_api/test_reservation_unit/test_query_all.py
tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py
tests/test_graphql_api/test_unit/helpers.py
tests/test_graphql_api/test_unit/test_query_all.py
tilavarauspalvelu/api/graphql/queries.py
tilavarauspalvelu/api/graphql/schema.py
tilavarauspalvelu/api/graphql/types/equipment/filtersets.py
tilavarauspalvelu/api/graphql/types/equipment/permissions.py
tilavarauspalvelu/api/graphql/types/equipment/types.py
tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py
tilavarauspalvelu/api/graphql/types/reservation_unit/permissions.py
tilavarauspalvelu/api/graphql/types/reservation_unit/types.py
tilavarauspalvelu/api/graphql/types/unit/filtersets.py
tilavarauspalvelu/api/graphql/types/unit/permissions.py
tilavarauspalvelu/api/graphql/types/unit/types.py

- Add GQL endpoints for Reservation Unit, Unit and Equipment with only minimal fields and no pagination, which can be used for e.g. dropdown filters in the frontend
- None
- [TILA-3625](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3625)
[TILA-3625]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3625?atlOrigin=eyJpI …

GQL endpoints with no pagination

---

tests/test_graphql_api/test_order/test_query.py
tilavarauspalvelu/api/graphql/schema.py

- Prevent querying orders of deleted reservations from the GQL API
- Fixes an issue where querying an order of a deleted reservation caused python errors due to permissions checks trying to access the reservation's user
- None
- Slack

Hide orders of deleted reservations from the GQL

---

tilavarauspalvelu/api/rest/views.py

- Allow querying CSRF endpoints without triggering redirects if no redirect URL is given. Required since fetch API doesn't allow reading headers from redirect requests, where the CSRF token is currently located.
- None
- None

Give JSON from CSRF endpoint if no `redirect_to` is given

---

config/urls.py

- This is done to not reserve as many top-level paths, since we share the same domain with the frontend
- Requires changing OpenShift routing to route the /monitoring/ to the backend (already done). Otherwise the monitoring paths are not visible to the internet.
- None

Fix paths for new monitoring endpoints

---

tests/factories/payment_order.py
tests/helpers.py
tests/test_utils/test_create_test_data.py

- See title. Enables running test data generation in Platta dev environment.
- None
- None

Enable test data generation without mock verkkokauppa enabled

---

tilavarauspalvelu/tasks.py

- See title. Prevents scheduling the task due to copy-pasta name.
- None
- None

Fix `anonymize_old_users_task` task name

---

config/auth.py
tests/test_graphql_api/test_application_section/test_filtering.py
tests/test_graphql_api/test_recurring_reservation/test_update_series.py
tilavarauspalvelu/api/helauth/urls.py
tilavarauspalvelu/api/helauth/views.py

- `lang` param can be used to set keycloak UI language from the frontend
- `ui` parameter can be used to select which UI is making the login (`customer` or `admin`).
- If `customer`, hints to use `suomi.fi` login
- if `admin`, currently does nothing
- If hint is wrong, should display the login selection as normal
- Currently this is not working in Helsinki tunnistus, maybe it will be fixed at some point?
- None …

Add new login params

---

config/settings.py
tilavarauspalvelu/api/graphql/schema.py

- Now if the user logging in is inactive, login fails and redirects to a frontend error page (currently missing)
- Also logout inactive users during `currentUser` query
- Requires the frontend error page to be available https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1503
- …

Handle inactive users

---

config/settings.py

- See title.
- Inform Platta that the health-check can be re-enabled after this hits production
- [TILA-3702](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3702)
[TILA-3702]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

Remove celery ping health check due to unreliability

---

tilavarauspalvelu/models/reservation_unit/queryset.py

- Add output fields and better null-catching to pass vector updates in test server
- None
- None

Fix search vector update

---

tests/test_graphql_api/test_reservation_unit/test_text_search.py
tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py
utils/db.py

- This works more like the previous search, with the omission of commas being used to search in OR-fashion (not used based on search history)
- Should likely be changed back to OR when we have a "similarity" ordering so that results containing more of the given words are shown first, but those that contain some of them can still be shown (This should also weigh finding the search word from 
the name of the reservation unit more than from the description for example)
[//]: # "e.g. This PR breaks …

Change reservation unit text search to use AND instead of OR

---

tests/test_models/test_reservation_unit_pricing_updates.py
tilavarauspalvelu/tasks.py

- Set `is_activated_on_begins` to `True` in tax update task
- None
- [TILA-3711](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3711)
[TILA-3711]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set `is_activated_on_begins` to `True` in tax update task

---

tests/test_graphql_api/test_reservation_unit/test_text_search.py
utils/utils.py

- See title.
- None
- [TILA-3744](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3744)
[TILA-3744]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Check path for unauthenticated user when selecting search language

---

config/settings.py
config/storage.py

- Fixes [issues](https://sentry.hel.fi/organizations/city-of-helsinki/issues/49772/?environment=prod&project=16&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=1) in saving images with filenames containing non-ASCII letters by adding a custom FileStorage backend that has additional normalization to replace non-ASCII letters in filenames before saving them
- Test in that said images can be uploaded in Platta envs
[//]: # "e.g. This PR breaks X and is waiting for …

Add custom Storage to convert non-ASCII filenames to ASCII

---

tests/test_graphql_api/test_reservation/test_staff_create.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_create_serializers.py

- Create an access code in Pindora for staff reservations
- Differences compared to customer reservations:
- Always create the reservation, even if Pindora request fails
- Create reservation access code in an active state, except if reservation type is "BLOCKED"
- None
- [TILA-3773](https://helsinkisolutionoffice.atlassian.net/browse/TIL …

Create access code for staff reservations

---

tests/test_graphql_api/test_reservation/test_approve.py
tests/test_graphql_api/test_reservation/test_confirm.py
tests/test_graphql_api/test_reservation/test_requires_handling.py
tests/test_graphql_api/test_reservation/test_staff_modify.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/confirm_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/requires_handling_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_reservation_modify_serializers.py
tilavarauspalvelu/models/payment_order/actions.py
tilavarauspalvelu/typing.py

- Activate / Deactivate reservation access code in reservation API when necessary.
- Activate when a reservation is confirmed and doesn't require payment
- Activate when a reservation has been paid and doesn't require handling
- Activate when a reservation in approved in handling
- Deactivate if staff moves a reservation back to handling
- Activate if staff changes reservation type from blocked
- Deactivate if staff changes reservation type to blocked
[//]: # "e.g. This PR breaks X and is …

Add reservation access code (de)activation calls

---

tests/test_graphql_api/test_reservation/test_adjust_time.py
tests/test_graphql_api/test_reservation/test_staff_adjust_time.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/adjust_time_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_adjust_time_serializers.py
tilavarauspalvelu/models/reservation/actions.py
tilavarauspalvelu/typing.py

- Notify Pindora about the time of the reservation if required
- If access type remains 'ACCESS_CODE', reschedule the reservation
- If access type no longer 'ACCESS_CODE', delete the reservation
- If access type now 'ACCESS_CODE', create the access code
- None
- [TILA-3782](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3782) …

Update access code in Pindora on reservation reschedule

---

tests/test_tasks/test_create_missing_pindora_reservations.py
tests/test_tasks/test_update_pindora_access_code_is_active.py
tilavarauspalvelu/tasks.py

- Add task for creating missing Pindora access codes on reservations that should have them
- Add task for updating "is_active" state for reservations where the known state in Pindora doesn't match the expected state according to Varaamo
- None
- None

Add background tasks for updating Pindora info on failure

---

tests/test_graphql_api/test_reservation/test_approve.py
tests/test_graphql_api/test_reservation/test_requires_handling.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
tilavarauspalvelu/api/graphql/types/reservation/serializers/requires_handling_serializers.py
tilavarauspalvelu/typing.py

- Create an access code when approving a reservation without one. This can happen in a denied reservation returns to handling and is then approved.
- Modify return to handling mutation to not make the deactivate call if access code was removed.
- None
- [TILA-3796](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3796) …

Create an access code when approving a reservation without one

---

apps/admin-ui/src/component/RecurringReservationsView.tsx
apps/admin-ui/src/component/ReservationListButton.tsx
apps/admin-ui/src/component/ReservationsList.tsx
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/reservations/[id]/index.tsx
apps/ui/components/application/ApprovedReservations.tsx
apps/ui/public/locales/en/application.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/sv/application.json

- Recreating: https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1646
- Adds a "Cancelled" StatusLabelto recurring reservation listings, when the user has cancelled a reservation (vs e.g. being denied.
- Changes the overlapping reservations StatusLabel text to simply "Ei saatavilla"
- As a user with a recurring reservation series, cancel a reservation -> it should have a StatusLabel "Cancelled"
- As admin go see the same recurring reservation, and open the "Toistokerrat" accordion. It should also have a StatusLabel instead of the edit-, show in calendar- and deny-buttons
[//]: # "Is this PR dependent on other …

Add cancelled status label to recurring reservation lists

---

apps/ui/components/CancellationForm.tsx
apps/ui/components/application/Page2.tsx
apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/EditStep1.tsx
apps/ui/components/reservation/Step0.tsx
apps/ui/components/reservation/Step1.tsx
apps/ui/components/reservations/UnpaidReservationNotification.tsx
apps/ui/pages/applications/[id]/page3.tsx
apps/ui/pages/applications/[id]/preview.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/public/locales/en/common.json
apps/ui/public/locales/fi/common.json
apps/ui/public/locales/sv/common.json

- Recreating: https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/pull/1652
- Fix: use more consistent button labels for new / edit / cancel reservation ui
- Add: arrow icons to prev buttons.
- Fix: missing gap to edit page step1.
- Manual testing: check the texts / icons are correct for all languages / funnels.
- None
- …

Fix submit / cancel button labels more consistent

---

backend/tests/test_rest_api/test_reservation_statistics_export.py
backend/tests/test_rest_api/test_reservation_unit_export.py
backend/tilavarauspalvelu/api/rest/utils.py
backend/tilavarauspalvelu/api/rest/views.py
backend/tilavarauspalvelu/services/export/_base_exporter.py
backend/tilavarauspalvelu/services/export/reservation_unit_exporter.py

- Add new filtering to the reservation unit and reservation statistics JSON report API
- Added filtering:
- Reservation Units: `tprek_id`, `only` (reservation unit ids), `start`, `stop`
- Reservation Statistics: `begins_after`, `begins_before`, `tprek_id`, `only` (reservation ids), `start`, `stop`
- Better validation logic for the APIs
- Format datetimes and times with timezone info
- Added pagination data to response headers
- Sort JSON keys alphabetically
[//]: # "e.g. This PR breaks X and is …

Add filtering to Report APIs

---

apps/ui/components/reservation/EditStep0.tsx
apps/ui/components/reservation/EditStep1.tsx
apps/ui/components/reservation/ReservationCancellation.tsx
apps/ui/components/reservation/ReservationInfoCard.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx

- fix: missing reservation number in info card
- refactor: reservation number (pk) is shown as long as reservation has been made without control props.
- Automated tests: e2e robot
- None
- None

fix: missing reservation number in info card

---

backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_sync_access_code.py
backend/tilavarauspalvelu/integrations/keyless_entry/service.py

- Fixes Pindora series and seasonal booking sync operations to reschedule first and then set active state, so that any reservations moved to access codes get the access code generated info before trying to set active state
- None
- None

Reschedule and then set active in Pindora series sync operation

---

backend/tests/test_graphql_api/test_recurring_reservation/test_add_reservation.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_activate_access_code.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_deactivate_access_code.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/add_serializer.py
backend/tilavarauspalvelu/integrations/keyless_entry/service.py
backend/tilavarauspalvelu/models/reservation/queryset.py

Fixes two issues with the access code active state:
1. Adding new reservations to a series now correctly clears `access_code_is_active` and `access_code_generated_at` if the new reservation doesn't require access codes
2. Activating or deactivating an access code for a series or application section now respectively deactivates or activates the access code for all other reservations.
- None
[//]: # "This pull …

Fix access code active issues

---

backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation_series.py
backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_seasonal_booking.py
backend/tilavarauspalvelu/integrations/keyless_entry/client.py
backend/tilavarauspalvelu/integrations/keyless_entry/service.py

- Our current series cancellation operation wants to leave an empty series in Pindora. Allow this in `PindoraClient` as well.
- None
- [TILA-3919](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3919)
[TILA-3919]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

Allow empty series and sections in Pindora

---

apps/ui/components/reservation-unit/Head.tsx
apps/ui/modules/__tests__/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/pages/reservation-unit/[id].tsx

- Fix: show reservable in the future error message based only on the reservable datetime backend provides.
- Refactor: remove unnecessary utility function.
- Manual testing: check ticket.
- Automation: e2e robot.
- None
- [TILA-3905](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3905)
[TILA-3905]: …

fix: display proper error message when reservation begins in future

---

apps/ui/components/recurring/ApplicationRoundCard.tsx

- Removes the time from where the application round cards show the reservation period
- Go to recurrable reservations index page - note that the reservation period shows only date with no time specified
- None
- [TILA-3789](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3789)
[TILA-3789]: …

Remove time from reservation period in application round cards

---

backend/pyproject.toml
backend/sonar-project.properties
backend/tests/test_admin/test_django_admin_site.py
backend/tests/test_graphql_api/test_recurring_reservation/test_reschedule_series.py
backend/tilavarauspalvelu/api/rest/views.py
backend/tilavarauspalvelu/management/commands/create_missing_statistics.py
backend/tilavarauspalvelu/models/application_round/actions.py
backend/tilavarauspalvelu/models/reservation/queryset.py
backend/tilavarauspalvelu/models/reservation_statistic/model.py
backend/tilavarauspalvelu/models/reservation_statistic_unit/model.py
backend/tilavarauspalvelu/models/reservation_unit/queryset.py
backend/tilavarauspalvelu/signals.py
backend/tilavarauspalvelu/tasks.py
backend/tilavarauspalvelu/typing.py

Try to prevent two errors from happening in statistics update:
1. [Statistic already exists for this primary key](https://sentry.hel.fi/organizations/city-of-helsinki/issues/61358/?project=16)
2. [Reservation for this statistic doesn't exist](https://sentry.hel.fi/organizations/city-of-helsinki/issues/61376/?project=16)
Kind of difficult to prevent, but changed the bulk update rules a bit and let's see
- None …

Try to prevent reservation statistics update errors

---

backend/templates/email/html/partials/access_code.jinja
backend/templates/email/html/partials/access_code_with_instructions.jinja
backend/templates/email/text/application_in_allocation.jinja
backend/templates/email/text/partials/access_code.jinja
backend/templates/email/text/partials/access_code_with_instructions.jinja
backend/tests/test_integrations/test_email/test_email_types/test_reservation_approved.py

- Fix HTML formatting for "access code unavailable instructions" in emails
- None
- [TILA-3890](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3890)
[TILA-3890]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix HTML formatting for "access code unavailable instructions" in emails

---

backend/templates/email/html/partials/access_code_section.jinja
backend/templates/email/html/seasonal_reservation_modified_series.jinja
backend/templates/email/html/seasonal_reservation_rejected_series.jinja
backend/templates/email/text/partials/access_code_section.jinja
backend/templates/email/text/seasonal_reservation_modified_series.jinja
backend/templates/email/text/seasonal_reservation_rejected_series.jinja
backend/tests/test_graphql_api/test_recurring_reservation/test_deny_series.py
backend/tests/test_graphql_api/test_reservation/test_confirm.py
backend/tests/test_integrations/test_email/conftest.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_approved.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_confirmed.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified_access_code.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series_access_code.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_rejected_series.py
backend/tilavarauspalvelu/admin/email_template/forms.py
backend/tilavarauspalvelu/admin/email_template/utils.py
backend/tilavarauspalvelu/admin/email_template/view.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/deny_serializer.py
backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/reschedule_serializer.py
backend/tilavarauspalvelu/integrations/email/main.py
backend/tilavarauspalvelu/integrations/email/template_context/application.py
backend/tilavarauspalvelu/integrations/email/template_context/common.py
backend/tilavarauspalvelu/integrations/email/template_context/reservation.py
backend/tilavarauspalvelu/integrations/email/typing.py
backend/tilavarauspalvelu/models/application_section/actions.py

- Changes the seasonal booking emails to take in an application section instead of a series
- Changes how Pindora information is retrieved for these emails
- Changes rules for when series modify emails are sent
- Fixes some minor typing issues
- Fixes a bug where access code validity didn't account for valid before and after minutes
- None
[//]: # "This pull request resolves all or part of the following …

Add seasonal booking change access code template

---

backend/tests/test_graphql_api/test_reservation/test_adjust_time.py
backend/tests/test_graphql_api/test_reservation/test_confirm.py
backend/tests/test_integrations/test_email/helpers.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_approved.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_confirmed.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified.py
backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified_access_code.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series.py
backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series_access_code.py
backend/tilavarauspalvelu/admin/email_template/utils.py
backend/tilavarauspalvelu/integrations/email/template_context/common.py

- After fetching access code for emails, check if it is actually active in Pindora and don't include it if it isn't
- None
- [TILA-3938](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3938)
[TILA-3938]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

Don't include access codes in emails if it is not actually active

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/reservations/[id]/ReservationKeylessEntrySection.tsx
apps/admin-ui/src/spa/reservations/[id]/queries.tsx
backend/tilavarauspalvelu/integrations/keyless_entry/client.py

- Add support for changing recurring reservation access code in admin ui
- Clear Pindora caching after access code is changed, so new access code is fetched from Pindora, instead of using the cached old access code
- None
- [TILA-3841](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3841)
[TILA-3841]: …

Change Recurring Reservation Pindora Access Code in Admin UI

---

apps/ui/pages/reservations/[id]/index.tsx

- access code section is only shown for confirmed reservations which have not ended before yesterday, only show it if:
- `reservation.state` is `Confirmed`
- `reservation.end` is less than 24h before now
- `reservation.accessType` is `AccessCode`
- None
- [TILA-3894](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3894) …

fix: access code section display in reservation view

---

apps/ui/components/reservation-unit/Head.tsx

- Show unrestricted access type in the info section on reservation unit pages
- Search for reservation units with unrestricted access, and visit one of their pages: the access type should be displayed there
- None
- [TILA-3904](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3904)
[TILA-3904]: …

Display unrestricted access in reservation unit page infos

---

backend/tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py

- [`CI` env variable is always set to 'true' in GitHub Actions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables). During testing, we always use the "AutomatedTests" environment. The `CI` environment is used for migration checks, etc.
- None
[//]: # "This pull request resolves all or part of the following …

Fix test query count variable

---

README-ui.md
package.json

- Fix: `pnpm codegen` eating error reports occasionally. The actual error message disappears from stdout.
- Requires GNU parallel to run the codegen command outside of watch mode.
- Automated tests: CI / Tooling change.
- None
- None

fix: reporting codegen problems correctly

---

apps/ui/components/application/Page2.tsx

- Show the unit name along with the reservation unit name in the time selection view, on application Page2
- None
- [TILA-3933](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3933)
[TILA-3933]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

Add unit name to the application form time selector's reservation unit select element

---

apps/ui/components/reservation-unit/Head.tsx
apps/ui/modules/reservationUnit.ts

- Fixes the access type durations listing tooltip:
- Fixes the begin date to be in proper UI date format
- Fixes durations without end date to not show `null`, and to use the proper translation key
- None
- [TILA-3946](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3946)
[TILA-3946]: …

Fix access type durations listing tooltip

---

apps/admin-ui/gql/gql-types.ts
apps/admin-ui/src/spa/application-rounds/[id]/review/AllocatedEventsTable.tsx
apps/admin-ui/src/spa/application-rounds/[id]/review/queries.tsx

- When determining whether to show the "Ovikoodia luodaan" tooltip, we now also check `shouldHaveActiveAccessCode` in order to not show the tooltip unnecessarily
- None
- [TILA-3955](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3955)
[TILA-3955]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3955?atlOrigin=eyJpIjoi …

Fix access code tooltip display condition

---

apps/ui/components/application/ApprovedReservations.tsx

- fix access type duration list showing `null` for endDate in approved reservations (view application)
- None
- [TILA-3946](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3946)
[TILA-3946]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

fix: don't show null in application access type listing

---

backend/tilavarauspalvelu/admin/reservation_unit/form.py

- Fixes issue where reservations' access types were not changed when future access types were removed from their reservation unit in the admin panel
- None
- [TILA-3963](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3963)
[TILA-3963]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3963?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

Run `update_access_types_for_reservations` when access types removed

---

apps/ui/components/application/ApprovedReservations.tsx

- If any of the access types for a series of reservations is `AccessCode`, the access code + code value is displayed in stead of a list of the access types
- Also renames `ReservationUnit..`-variables to `ReservationSeries..` ones, as that is what they are and thinking about them as reservation units is misleading
- None
- …

Show code value if a multivalued access type includes access code

---

apps/ui/public/locales/fi/application.json
packages/common/src/components/statuses/ApplicationStatusLabel.tsx

- applications with `RECEIVED` status are now shown with correct type, icon and translation
- None
- [TILA-3961](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3961)
[TILA-3961]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

fix: applications with "received" status shown correctly

---

apps/ui/components/application/ApprovedReservations.tsx

- The access code value is shown in the "Ohjeet" dialog box, for multivalued access type reservation series (== always when the access type validity period is of type ACCESS_CODE).
- None
- [TILA-3966](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3966)
[TILA-3966]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3966 …

fix: always show access code value in the dialog

---

backend/tests/test_graphql_api/test_reservation/test_adjust_time.py
backend/tests/test_graphql_api/test_reservation/test_create.py
backend/tests/test_graphql_api/test_reservation/test_requires_handling.py
backend/tests/test_graphql_api/test_reservation/test_staff_adjust_time.py
backend/tests/test_graphql_api/test_reservation/test_staff_create.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/adjust_time_serializers.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/create_serializer.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/requires_handling_serializers.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_adjust_time_serializers.py
backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_create_serializers.py
backend/tilavarauspalvelu/models/reservation/actions.py
backend/tilavarauspalvelu/typing.py

- Make a second overlapping validation check during the endpoint, and remove the created reservation if an overlapping reservation is found
- Make second check also during staff create
- Also do overlapping checks during "return to handling" as this can change a "denied" (not going to happen) to "requires handling" (going to happen), which may make it overlap with newer reservations
- Also also do checks when rescheduling reservations
[//]: # "e.g. This PR breaks X and is waiting for frontend …

Prevent simultaneous overlapping reservation creation

---

backend/tilavarauspalvelu/management/commands/defragment_frontend_queries.py

- Add management command for defragmenting queries (=adding GraphQL fragments inline and removing duplicate fields) generated by the frontend in #1693
- This is in preparation for writing tests for the queries (makes deducing which models are needed easier)
- #1693
- [TILA-3868](https://helsinkisolutionoffice.atlassian.net/browse/TILA-38 …

Add management command for defragmenting frontend queries

---

backend/Makefile
backend/config/celery/health_checks.py
backend/docker/scheduler.sh
backend/pyproject.toml

- Use direct scheduler ref to custom beat scheduler since the project is not installed in editable mode during production so entrypoints are not available
- None
- None

Fix beat scheduler reference

---

backend/tilavarauspalvelu/admin/reservation_unit/form.py
backend/tilavarauspalvelu/models/reservation_unit_access_type/queryset.py

- Previously only showed if current one was access code
- Also show error if Pindora call fails
- None
- [TILA-3980](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3980)
[TILA-3980]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Show Pindora info in django admin if future access type is access code

---

apps/admin-ui/src/spa/application-rounds/[id]/allocation/AllocationCalendar.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/AllocationCard.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEventCard.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEvents.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/index.tsx
apps/admin-ui/src/spa/application-rounds/[id]/allocation/modules/applicationRoundAllocation.ts

- Fix allocation not showing selected application outline when it contained the last hour (end at 00:00).
- Fix allocation not preserving `unit` and `aes` query params when loading the page.
- Fix cleaner time formatting for slots (use our standard `begin–end` with trailing zeros format).
- Fix invalid html due to nested button element.
- Refactor remove unnecessary optionals.
- Manual testing: check allocation page reload / url share and application section ending at midnight.
[//]: # "e.g. This PR breaks X and …

Fix allocation selected show 24h

---

apps/ui/components/application/ApprovedReservations.tsx
apps/ui/gql/gql-types.ts
apps/ui/public/locales/en/application.json
apps/ui/public/locales/fi/application.json
apps/ui/public/locales/sv/application.json

- Show the unit name with the reservation unit name in the reservation series listing table, in the accepted application view
- Changes the "Toimipisteet" heading to a more suitable one: "Kausivaraukset"
- None
- [TILA-3932](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3932)
[TILA-3932]: …

add: unit name to be shown along reservation unit name

---

backend/tests/test_models/test_recurring_reservation.py
backend/tilavarauspalvelu/models/recurring_reservation/model.py

- Changes `series.used_access_types` lookup property to filter with "going_to_occur".
- Frontend should handle situations where `used_access_types` is empty
- [TILA-3978](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3978)
[TILA-3978]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3978?atlOrigin=eyJpIjoiNWRkNTljNzYx …

Only count reservations that are going to occur for series used access types

---

apps/admin-ui/src/spa/application-rounds/[id]/allocation/index.tsx

- Fix: on first landing to allocation page `unit` param gets reset by multiple useEffects causing an infinite render loop.
- Manual testing: check that Firefox doesn't crash on first landing to allocation page (through the "Jaa vuoroja" link).
- None
- None

Fix allocation page going to infinite rerender loop

---

apps/ui/components/recurring/StartApplicationBar.tsx
apps/ui/pages/recurring/[id]/index.tsx
apps/ui/styles/variables.css

- fixes a11y problems regarding the bottom banner, which shows up at the start of a recurring reservation application
- it pushes the page content up, so that no footer links get covered
- it takes into account the cookie consent banner, with which it shares space
- None
- [TILA-3996](https://helsinkisolutionoffice.atlassian.net/browse/T …

fix: recurring reservations starting bottom banner position

---

apps/admin-ui/src/spa/unit/[id]/ReservationUnitCard.tsx
packages/common/src/components/Card.tsx

- adds `LinkComponent` as an optional prop to `Card`, which is used to wrap the text links in `Card` instead of the default (`next/link`)
- complete/fix Card JSDoc @param listing
- None
- [TILA-3937](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3937)
[TILA-3937]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-3937?a …

fix: admin Card links

---

apps/ui/components/application/ApprovedReservations.tsx
apps/ui/components/reservation-unit/Head.tsx
apps/ui/modules/reservationUnit.ts
apps/ui/modules/util.ts
apps/ui/pages/applications/[id]/view/index.tsx

- Shows access types only for the duration of the seasonal application round
- Uses the application round season start/end dates as the access type period start/end dates, for periods which start before and/or end after the application round season
- Displays "-" as access type for a reservation series which has no `usedAccessTypes`
- empty `usedAccessTypes` aren't available from the BE until the code in #1745 …

Fix: Access type issues in approved reservations view

---

apps/ui/components/application/ApplicationSectionList.tsx
apps/ui/components/application/styled.tsx

- edit the list styling to keep the medium font weight in the info values, while having only ones within a `<span>` as `nowrap`.
- `nowrap` _could_ in principle be removed from all the application info values, but in the other ones there is good a case to be made for keeping them confined to be on a single line. Since purpose is a free text field it can be a lot longer, and it’s quite natural to have it wrap onto two or more lines if needed due to it being natural text and not "hard values" (== a number followed by a unit, or a range of dates..). The other values can not be long enough to warrant a second line by themselves. If they wouldn't fit on one line together with their label the entire value text should be on a new line. …

fix: make the purpose text able to wrap in view application page

---

apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx
apps/admin-ui/src/spa/my-units/[id]/ReservationUnitCalendarView.tsx
apps/admin-ui/src/spa/my-units/[id]/UnitCalendar.tsx
apps/admin-ui/src/spa/my-units/[id]/UnitReservations.tsx
apps/admin-ui/src/spa/my-units/[id]/index.tsx

- adds a button to make single reservations to the admin my-units view 
- refactors `reservationUnitPk` to be a searchParam (`reservationUnit`) for easier handling of the its state across all the relevant components - this also makes the reservation unit selection in the reservation unit tab persistant
- adds possibility to change the reservation unit to the `CreateReservationModal`
- None
[//]: # "This pull …

add: Make single reservation button to admin my-units view

---

apps/ui/hooks/useToastIfQueryParam.ts
apps/ui/middleware.ts
apps/ui/modules/urls.ts
apps/ui/pages/applications/[id]/view/index.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/pages/reservations/[id]/index.tsx
apps/ui/public/locales/en/errors.json
apps/ui/public/locales/en/reservationCalendar.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/fi/reservationCalendar.json
apps/ui/public/locales/sv/errors.json
apps/ui/public/locales/sv/reservationCalendar.json

- Fix: redirect initial reservations that got deleted back to reservation-unit instead of 404.
- Fix: don't 500 after login if the `createReservation` mutation fails, toast errors to user instead.
- Manual testing: overlapping reservations (postLogin), removed reservations should redirect out of funnel on refresh (not 404).
- None
- …

Fix reservation funnel error handling

---

apps/admin-ui/src/common/apolloClient.ts
apps/ui/hooks/index.ts
apps/ui/middleware.ts
apps/ui/modules/apolloClient.ts
apps/ui/pages/503.tsx
apps/ui/pages/_error.tsx
apps/ui/pages/reservation-unit/[id].tsx
packages/common/package.json
packages/common/src/apolloUtils.ts
packages/common/src/common/toast.tsx
pnpm-lock.yaml

- Add logging GraphQL as different errors in sentry based on the backend error code.
- Add 503 error page if middleware GraphQL query fails with networkError (no backend connection / gateway error / 503).
- Fixes redirect to 500 page when GraphQL query fails uncontrollably.
- Add `Network error` toast if client side GraphQL query fails with networkError.
- Fixes pure client side queries / mutations failing silently or with unrelated error message.
- Manual testing: drop backend pods to simulate 503 on frontend. both `admin` and `customer`
- Manual testing: check sentry logs in both environments for GraphlQL errors (ex. …

Add graphql error logging to sentry

---

backend/config/settings.py
backend/tests/factories/__init__.py
backend/tests/factories/_base.py
backend/tests/factories/hauki.py
backend/tests/test_integrations/test_hauki/test_hauki_api_client.py
backend/tests/test_integrations/test_hauki/test_hauki_resource_hash_updater.py
backend/tilavarauspalvelu/integrations/opening_hours/hauki_api_client.py
backend/tilavarauspalvelu/integrations/opening_hours/hauki_api_types.py
backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py

- Fixes Hauki resource update requesting too many resources at once, and going over Hauki's URI length limit. Adds a `HAUKI_RESOURCE_BATCH_SIZE` setting for configuring how many resources should be fetched in a batch.
- None
- [TILA-4075](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4075)
[TILA-4075]: …

Fix Hauki resource update too long URI

---

apps/admin-ui/src/common/const.ts
apps/admin-ui/src/component/MainLander.tsx
apps/admin-ui/src/component/Navigation.tsx
apps/ui/components/LoginFragment.tsx
apps/ui/components/application/ApprovedReservations.tsx
apps/ui/components/common/Navigation.tsx
apps/ui/components/reservation-unit/AddressSection.tsx
apps/ui/components/reservation/ReservationCancellation.tsx
apps/ui/components/reservation/ReservationInfoSection.tsx
apps/ui/middleware.ts
apps/ui/modules/applicationRound.ts
apps/ui/modules/reservationUnit.ts
apps/ui/modules/search.ts
apps/ui/modules/util.ts
packages/common/src/browserHelpers.ts
packages/common/src/calendar/Calendar.tsx
packages/common/src/components/statuses/ApplicationStatusLabel.tsx
packages/common/src/helpers.ts
packages/common/src/urlBuilder.ts

- Sets `ui` to "customer"/"admin" depending on who is logging in
- Sets `lang` as "fi"/"sv"/"en" based on the customer language selection
- Leaves `lang` unset for admin login, to allow for possible browser settings
- None
- [TILA-3565](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3565)
- …

Use language selection and customer/admin in login url searchParams

---

apps/admin-ui/src/common/fragments.tsx
apps/admin-ui/src/component/DenyDialog.tsx
apps/admin-ui/src/i18n/index.ts
apps/admin-ui/src/i18n/messages.ts
apps/admin-ui/src/spa/reservations/ReservationsTable.tsx
apps/admin-ui/src/spa/reservations/[id]/ApprovalButtons.test.tsx
apps/admin-ui/src/spa/reservations/[id]/ReservationTitleSection.tsx
apps/admin-ui/src/spa/reservations/[id]/index.tsx
apps/admin-ui/src/spa/reservations/hooks/__test__/mocks.ts
apps/ui/components/UnpaidReservationNotification.tsx
apps/ui/modules/reservation.test.ts
apps/ui/modules/reservation.ts
apps/ui/pages/reservations/[id]/confirmation.tsx
apps/ui/pages/reservations/[id]/index.tsx
packages/common/src/common/util.ts

- Adds due date display to admin reservation view
- makes `reservation.paymentOrder` a singular object in stead of an array (0-n -> 0-1)
- fixes two annoying i18n errors showing up on the admin side, due to missing translation keys
- None
- [TILA-4028](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4028)
- …

Add due date&payment status

---

apps/ui/components/reservation/EditStep0.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx

- Fix pink box "Huomio varatessa" missing from reservation funnel, edit reservation, and reservation unit pages after field rename from `termsOfUse` to `notesWhenApplying`.
- Manual testing: see the Jira ticket.
- None
- [TILA-4138](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4138)
[TILA-4138]: …

Fix pink box missing after GQL field rename

---

apps/admin-ui/src/i18n/locales/fi/reservationApplication.json
apps/ui/components/application/ApplicationCard.tsx
apps/ui/components/reservation/SummaryFields.tsx
apps/ui/public/locales/en/applicationCard.json
apps/ui/public/locales/en/reservationApplication.json
apps/ui/public/locales/fi/applicationCard.json
apps/ui/public/locales/fi/reservationApplication.json
apps/ui/public/locales/sv/applicationCard.json
apps/ui/public/locales/sv/reservationApplication.json
packages/common/src/reservation-form/MetaFields.tsx

- Fix invalid organisation (reservee type) translation in Application Cards `customer`.
- Manual testing: application card correct reservee type translations.
- None
- None

Fix applicant type not translated correctly

---

.github/workflows/upload_sentry_sourcemaps.yml

- The workflow [Upload frontend sentry sourcemaps](https://github.com/City-of-Helsinki/tilavarauspalvelu-core/actions/workflows/upload_sentry_sourcemaps.yml) does create separate UI and Admin-UI releases for the `prod` environment with their source maps uploaded in Sentry: e.g. https://sentry.hel.fi/organizations/city-of-helsinki/releases/v1.36.0-ui/?project=17
- However, the sessions and events subsequently recorded no longer seem to match them, so the maps are of no use: e.g. https://sentry.hel.fi/organizations/city-of-helsinki/releases/tilavarauspalvelu-ui%40v1.36.0-ui/?project=17
- The reason appears to be that when the data is sent from browser the value is like `"release":"tilavarauspalvelu-ui@v1.36.0-ui"` (because of the [config](https://github.com/City-of-Helsinki/tilavarauspalvelu …

TILA-4164: fix Sentry source maps upload

---

apps/admin-ui/src/component/MainLander.tsx
apps/admin-ui/src/component/Navigation.tsx

- uses `onClick` to open the a11y terms from `MainLander`, since SSR doesn't have `window.location.origin`
- None

fix: use onClick to open the a11y terms, to get the url correct

---

apps/ui/public/locales/en/errors.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/errors.json

- Use correct translation path for `USER_NOT_INTERNAL_USER`
- None
- [TILA-4199](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4199)
[TILA-4199]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use correct translation path for `USER_NOT_INTERNAL_USER`

---

apps/admin-ui/src/lib/reservation-units/[pk]/form.ts

- Fix reservationsMaxDaysBefore validation not raising an issue when trying to publish a reservation unit with the field not filled due to it defaulting to `0`
- None
- [TILA-4062](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4062)
[TILA-4062]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4062?atlOrigin=eyJpIjoiNW …

Fix reservationsMaxDaysBefore validation in Admin UI

---

backend/tilavarauspalvelu/admin/unit/admin.py
backend/tilavarauspalvelu/api/graphql/types/reservation/filtersets.py

- Fix duplicate reservations returned from GQL caused by missing `.distinct()`s and a unit belonging to multiple unit groups
- Add UnitGroups on Unit Django Admin page (Previously there was no way to
- None
- [TILA-4179](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4179)
[TILA-4179]: …

Fix duplicate reservations returned from GQL

---

apps/ui/hooks/useToastIfQueryParam.ts
apps/ui/modules/urls.ts
apps/ui/pages/reservations/[id]/index.tsx
apps/ui/pages/success.tsx
apps/ui/public/locales/en/reservations.json
apps/ui/public/locales/fi/reservations.json
apps/ui/public/locales/sv/reservations.json

- Redirects the user to the reservation page when returning from a successful online payment, Instead of keeping them waiting for the change in payment status from the backend which we're expecting
- Shows a "Payment status not verified" toast, informing the user of the situation
- Adds `alert` type toasts to `useToastIfQueryParam()`-hook
- Adds optional title/heading text to the `useToastIfQueryParam()`-hook's contents
[//]: # "e.g. This PR breaks X and is waiting for frontend changes before …

Fix handled payment polling

---

apps/admin-ui/src/lib/reservation-units/ReservationUnitsDataLoader.tsx

- Changes the permission filter from `onlyWithPermission` to `onlyWithManagePermission`
- requires the changes made in `add-manage-perm-res-unit-filter` branch in order to support the `onlyWithManagePermission`filter
- [TILA-4196](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4196)
[TILA-4196]: …

Use onlyWithManagePermission filter when querying for reservation units

---

backend/tests/test_graphql_api/test_user/test_current_user.py
backend/tilavarauspalvelu/api/graphql/types/user/queries/types.py

- Frontend queries user's roles and permissions for permission checks, so don't show inactive permissions through the GraphQL API
- None
- [TILA-4192](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4192)
[TILA-4192]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

Don't show inactive permissions through the GraphQL API

---

backend/tilavarauspalvelu/admin/application_round/admin.py
backend/tilavarauspalvelu/admin/application_round/form.py

- If not set, users cannot send applications. Require them in admin form
- Use `TabbedTranslationAdmin` for application round view
- None
- None

Make terms of use on application round required in Django admin

---

.oxlintrc.json
apps/admin-ui/next-env.d.ts
apps/ui/next-env.d.ts
apps/ui/public/locales/en/errors.json
apps/ui/public/locales/fi/errors.json
apps/ui/public/locales/sv/errors.json

- Fix adult reservee error required translations.
- Bump NextJs types to match the current installed version.
- None
- None

Fix translation of underage reservee

---

apps/admin-ui/src/lib/reservation-units/ReservationUnitsDataLoader.tsx
apps/ui/modules/search.ts

- adds the remaining two old commits from before the undine removal:
- uses `onlyWithManagePermission`-filter when listing reservation units for admin
- takes the selected language into account when sorting the items in the search page unit dropdown
- None
- [TILA-4245](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4245) …

Adds two straggler commits from the undine-back-to-graphene switch

---

packages/common/src/components/toast.tsx

- migrate to toast 11:
- show the icon
- reposition it within the updated structure (`.Toastify__toast-body` doesn't exist anymore)
- None
- [TILA-4261](https://helsinkisolutionoffice.atlassian.net/browse/TILA-4261)
[TILA-4261]: https://helsinkisolutionoffice.atlassian.net/browse/TILA-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

Fix: restore icon to toasts after updating toastify

---

apps/admin-ui/public/locales/fi/notification.json
apps/admin-ui/src/pages/my-units/[id]/index.tsx
apps/admin-ui/src/pages/my-units/[id]/recurring/index.tsx
apps/ui/pages/reservation-unit/[...params].tsx
apps/ui/pages/reservation-unit/[id].tsx
apps/ui/public/locales/en/notification.json
apps/ui/public/locales/fi/notification.json
apps/ui/public/locales/sv/notification.json
packages/common/src/components/TimeZoneNotification.tsx
packages/common/src/const.ts

- adds `TimeZoneNotification` component to `common` (in case it would be used in `admin-ui` too, eventually)
- show the notification on the reservation unit page and in the reservation funnel, if the browser time zone isn't `Europe/Helsinki` as expected
- None
- [TILA-3249](https://helsinkisolutionoffice.atlassian.net/browse/TILA-3249) …

Notify user if their timezone deviates from expected
